### ISSUE TITLE
Body Tree utility in MuJoCo (python)

### ISSUE THREAD

**Issue by joonhyung-lee** [google-deepmind/mujoco#1032]
Hi,

I'm a graduate student and I'm trying to use MuJoCo for my own robotics research.

I'm looking for some help with **Element Tree** function(utility).

Here is a screenshot, illustrating my question:
![Screenshot from 2023-08-25 22-42-10](https://github.com/deepmind/mujoco/assets/68883036/f23440fa-2b34-4028-91dc-3191eda558c0)
![Screenshot from 2023-08-25 22-42-07](https://github.com/deepmind/mujoco/assets/68883036/2dc4f585-5d40-4d54-88ed-507521500b94)
![Screenshot from 2023-08-25 22-42-02](https://github.com/deepmind/mujoco/assets/68883036/473d393f-8bcd-42aa-8595-a3f5e665185b)
https://www.youtube.com/watch?v=e0babIM8hBo

When I press the **'`'** key, it turns on something called **Body Tree**, where can I find the python code for this?
I ask this in order to get the region occupied by each geometry created in the mujoco world.

I appreciate your guidance on this matter, and any insights you can provide would be greatly beneficial to my project.

Thank you!

**Comment by quagla** [comment]
Hi @joonhyung-lee you can find the bounding box of each geom in `model.geom_aabb`. This is in the geom frame, so you will need to transform it to the world frame using `data.geom_xpos` and `data.geom_xmat`. Transform the first 3 numbers of `geom_aabb` (its center, which is **not** necessarily the same as `geom_pos`) then add the other three numbers (its half-sizes) multiplied by each column of `xmat` (the orientation of the box).

**Comment by joonhyung-lee** [comment]
Thanks for the details, I really appreciate it.
