### ISSUE TITLE
Custom fluid model 

### ISSUE THREAD

**Issue by Joviei** [google-deepmind/mujoco#1036]
Hi,

I'm a student, and I'm trying to use MuJoCo for calculating the passive force of liquid on an object using python.

I'm looking for some help with the mjcb_passive calculate, I got the  force field represented by" `X[m]` `Y[m]` `Z[m]` `Velocity [m s^-1]` `Velocity Angle[degree]`". How could I introduce this force field in the object joints.

Also, is there a way to implement in `dm_control`? 

Thank you!

**Comment by yuvaltassa** [comment]
You probably want to call [mj_applyFT](https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mj-applyft)
