### ISSUE TITLE
How to fix a part of joints of the model in simulation?

### ISSUE THREAD

**Issue by Uptomylimit** [google-deepmind/mujoco#1042]
Hi,

I'm a student and I'm trying to use MuJoCo for simulation.

I'm trying to fix part of joints of my model in simulation, so that a part of my model won't move. Is there any way to do this?

**Comment by Uptomylimit** [comment]
I have solved this problem by setting mjmodel.jnt_range to fix part of joints. 

However, I find that the  freejoint doesn't have joint_range to limit itself. Thus, can I replace the freejoint with 3 slide joint and 3 hinge joint?

**Comment by yuvaltassa** [comment]
A free joint is equivalent to 3 sliders and a ball, not 3 hinges.

Why don't you just remove the joints? Having joints with very tight ranges is not recommended.

**Comment by Uptomylimit** [comment]
> A free joint is equivalent to 3 sliders and a ball, not 3 hinges.
> 
> Why don't you just remove the joints? Having joints with very tight ranges is not recommended.

Because I want record the joint angles to initial my robot state.

**Comment by Uptomylimit** [comment]
Thanks for your answer!

Now I can remove the joints by calculating the relative position and create a new xml model to initial my robot state!
