### ISSUE TITLE
Difference between MjData.qpos and MjData.ctrl

### ISSUE THREAD

**Issue by STAY-Melody** [google-deepmind/mujoco#1048]
Hi!

In some Python scripts, I found that actuators are driven by transferring data to `mjdata.qpos` or `mjdata.ctrl`.

For the seven active joints of [franka robot](https://github.com/google-deepmind/mujoco_menagerie/blob/main/franka_emika_panda/panda.xml), what is the difference between these two ways? 

Which one is recommended for more accurate control?

Thanks!

**Comment by yuvaltassa** [comment]
qpos is the actual configuration, setting it is not control at all, it's something you do when you want to play back kinematics (or reset the state of course).

Reading [this](https://mujoco.readthedocs.io/en/2.3.7/computation.html#the-state) might help.

**Comment by maheshr24** [comment]
@yuvaltassa Hey so I use neural net to predict the joint angles, how can i give input I mean the input should be with ctrl. So how can I convert
