### ISSUE TITLE
Restriction on null space exploration

### ISSUE THREAD

**Issue by STAY-Melody** [google-deepmind/mujoco#1049]
Hi!

I found that `fetch_pick_and_place` env was realized with `mocap` which is implemented through the built-in inverse kinematics algorithm.

From the training results of `fetch_pick_and_place`, the 7-DOF fetch arm did not oscillate significantly by exploring in the null space. As far as I know,  null space exploration could be affected by the initial configuration of the manipulator. `fetch_pick_and_place` env is initialized with a high-manipulability configuration and there is no significant oscillation during the entire task.

I'm curious if it's possible to control the end-effector via `mocap` in a way that simultaneously restricts the redundant arm to reduce the exploration of the null space.

Thanks in advance!

**Comment by yuvaltassa** [comment]
You can put springs in the joints? If you want something more elaborate you'd have to implement that seperately.

**Comment by yuvaltassa** [comment]
Take a look at [this model](https://github.com/google-deepmind/mujoco/blob/main/test/engine/testdata/actuation/refsite.xml) see what you can learn from it. BTW, it's not clear to me why you need a mocap body.

**Comment by yuvaltassa** [comment]
Look at the model above. No mocap body required.

**Comment by yuvaltassa** [comment]
That should have any effect.
Define "crash": Falls down of the physics diverges?

Are you using implicitfast integrator?
Do you joints and actuators have damping?

**Comment by yuvaltassa** [comment]
Look at the translation default class. Your gain is 100N/m. That's like the stretchy resistance band you get in Pilates classes. I.e. only after it drops 1m you apply a force equivalent to 10Kg (I guess the robot weighs more than that). How could it possibly hold it up?

You need to tune the translation and rotation default classes for your actuators. These things have units, they are model dependent.

The model in the example above is an abstract example, you can't expect to just copy numbers from it.

PS I think you could have figured this out yourself if you tried a little harder 🙂

As a side note, we really hope to release some general sysID tutorial soon, might be helpful in this context.

**Comment by yuvaltassa** [comment]
It might help to read the implementation of [`mj_fwdActuation`](https://github.com/google-deepmind/mujoco/blob/main/src/engine/engine_forward.c) , and then re-read the [relevant documentation section](https://mujoco.readthedocs.io/en/latest/computation/index.html#actuation-model)
