### ISSUE TITLE
How to compute the friction generated by contact?

### ISSUE THREAD

**Issue by Uptomylimit** [google-deepmind/mujoco#1060]
Hi,

I'm a student and I'm trying to use MuJoCo for simulation.

I am confused of the friction force generated by contact.

In your document, I find that the constraint force is generated as follow:

<img width="241" alt="image" src="https://github.com/google-deepmind/mujoco/assets/56639313/95106418-0837-455a-af8b-9ebbd3830005">

I think that the contact force in the normal direction(x axis) is easy to understand. However, for friction generated by contact, I think that it is a kind of constraint, so it will be computed by the formula as shown above. So, Can you tell me the direction of v and r when computing the friction? And would pressure affect the magnitude of friction? And where is the "friction parameter" in computation as shown in the figure below?
<img width="643" alt="image" src="https://github.com/google-deepmind/mujoco/assets/56639313/e281d934-b186-4980-b5ea-a47691d7c09d">

**Comment by yuvaltassa** [comment]
Your question is not clear, are you just trying to get the fricitonal component of the contact force?

If yes, I think you are looking for [mj_getContactForce](https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mj-contactforce).

I believe this is used somewhere in the [tutorial](https://github.com/google-deepmind/mujoco#getting-started)
