### ISSUE TITLE
Get height of a hfield given x and y

### ISSUE THREAD

**Issue by JewelryForge** [google-deepmind/mujoco#1065]
Hi,

I'm a student and I'm trying to use MuJoCo for reinforcement learning based control with its C API.

I'm looking for some help with getting the height of a hfield given a x and y coordinate.

I find all APIs and the most relative function is `mj_rayHfield`, but it's too complicated and inefficient for a simplified problem.

Is there a straightforward way to achieve this?

**Comment by yuvaltassa** [comment]
There currently is no built in function for that. You're welcome to write one and send us a PR.

You should be able to figure out the math by either looking at the [collision](https://github.com/google-deepmind/mujoco/blob/7f8018a3f3611f2165bf0cd25a6b04d8c9307502/src/engine/engine_collision_convex.c#L508) or the [rendering](https://github.com/google-deepmind/mujoco/blob/7f8018a3f3611f2165bf0cd25a6b04d8c9307502/src/render/render_context.c#L401) code.
