### ISSUE TITLE
Jointpos sensor output

### ISSUE THREAD

**Issue by nilsvandergaag** [google-deepmind/mujoco#1077]
Hi,

I'm trying to implement a controller on a pendulum using a jointpos sensor, but at first it seemed like my simulation was exploding because the jointpos sensor always outputs a value in the range [0, 2pi), but after implementing that knowledge it actually seems to go beyond that. From the documentation it is not clear to me, so does anyone know if the jointpos sensor outputs a value between 0 and 2pi, or that after one turn it exceeds those bounds?

Thank you in advance!

**Comment by yuvaltassa** [comment]
`jointpos` sensors (and joint angles, for hinge joints) are unlimited, there is no jump. 
The angle can wind up or down as far as it wants.
Your problem is elsewhere.
