### ISSUE TITLE
Creating uniform lighting in an environment

### ISSUE THREAD

**Issue by jomian78** [google-deepmind/mujoco#1078]
Hi there, 

I'm trying to create an environment with uniform lighting such when I take a top down camera image from any place in the environment, the image will be the same (aside from a few objects I've added on the ground plane). The top-down camera I am using is attached to a rigid body (which represents a drone that is flying around the environment). 

I've encountered a several issues while doing this:
1) It seems that all rigid bodies in the environment emit some level of light by default. The default light emitted by the rigid body attached to my camera affects the images I take
2) Cameras appear to add some level of light (like a spotlight) to their images by default
3) I don't want the rigid body attached to the camera to cast a shadow on the top down image

I believe I've been able to remedy issues 1) and 2) by setting the "global glow" and "headlight" parameters in my xml file to 0:
`<visual>
    <global glow="0.0"/>
    <headlight active="0"/>
  </visual>`

However, when I add a global camera view of my environment for debugging purposes, the environment appears to be quite dark (I can't fully see the objects I've added when I'm viewing the environment from the global view - the camera images of individual objects are also relatively darker than I want). 

I tried adding a directional light in the center of the environment with the following code, but it ends up looking more like a spotlight:
`<light directional="true" pos="0 0 200" dir="0 0 -1" castshadow="false"/>`

Does anyone have any tips for using directional lights (or other types of lights) to create uniform lighting throughout the environment?

**Comment by yuvaltassa** [comment]
I think you want to use the `ambient` attribute.

Regarding debugging, simulate has a Visualization tab that lets you turn the headlight on and off and play with the lighting parameters.

![image](https://github.com/google-deepmind/mujoco/assets/6387526/62c1a867-668c-4571-9324-c37a848fc0b8)
