### ISSUE TITLE
Recompute inertia on the fly 

### ISSUE THREAD

**Issue by vikashplus** [google-deepmind/mujoco#1080]
I have a body with a few geoms. 

```xml
<body name="Object" pos="0 0 1">
    <geom name="geom1" type="box" size="0.02 0.02 0.02"/>
    <geom name="geom2" type="box" size="0.02 0.02 0.02"/>
    <geom name="geom3" type="box" size="0.02 0.02 0.02"/>
</body>
```

I'm trying to programmatically morph this body into random arbitrary objects by randomizing the `geom_types` and `geom_size`, `geom_pos`, `geom_quat`. I am also adjusting the `geom_rbound` and `geom_aabb` accordingly for proper collisions.

Is there a way to recompute inertial properties of this body after the shapes has been regenerated?

**Comment by yuvaltassa** [comment]
Is pyMJCF not a good solution?

**Comment by vikashplus** [comment]
I want to be able to do it programmatically post-load in the compiled model. My understanding is that pyMJCF is only for XML generation. Let me know if I am missing anything.

**Comment by vikashplus** [comment]
For my use case - 
- I need to be able to do it at a really high speed. 
- The models are huge and load time is significant.
- The sim instance can't be destroyed and recreated

**Comment by yuvaltassa** [comment]
In that case you need to re implement the inertia-inference logic in the compiler. It's not very complicated.
Let me know if you need help finding the code or have further questions.

**Comment by vikashplus** [comment]
It would be helpful if I could get a few pointers and I'll take it from there.

**Comment by yuvaltassa** [comment]
Start [here](https://github.com/google-deepmind/mujoco/blob/110ade14356cb99c5aa82e479998fcd2a9d8c4ed/src/user/user_objects.cc#L1386)
