### ISSUE TITLE
 Methods for Calculating Inverse Dynamics

### ISSUE THREAD

**Issue by jheyeo222** [google-deepmind/mujoco#1088]
Hi,

I'm a student and I'm trying to use MuJoCo for a project.

I received help previously on force and torque sensor https://github.com/google-deepmind/mujoco/issues/997, and I'm extremely grateful for your assistance.

First of all, I would like to apologize for asking this question.

I am interested in computing the mass matrix, Coriolis matrix, and gravity vector for inverse dynamics. 
I have consulted the official documentation and found functions like 'mj_fullM' for calculating the mass matrix, but I have been unable to locate functions for the Coriolis matrix and gravity vector. 
Could you please inform me if there are specialized functions or methods in Mujoco for these calculations?

**Comment by dhruvthanki** [comment]
Hi!
Mujoco computes the sum of both, Coriolis and gravity vector. Take a look at the table [General framework](https://mujoco.readthedocs.io/en/latest/computation/index.html?highlight=bias#general-framework) and [equation](https://mujoco.readthedocs.io/en/latest/computation/index.html?highlight=bias#equation-eq-motion). The sum is stored in `mjData.qfrc_bias`.

**Comment by jheyeo222** [comment]
> Hi! Mujoco computes the sum of both, Coriolis and gravity vector. Take a look at the table [General framework](https://mujoco.readthedocs.io/en/latest/computation/index.html?highlight=bias#general-framework) and [equation](https://mujoco.readthedocs.io/en/latest/computation/index.html?highlight=bias#equation-eq-motion). The sum is stored in `mjData.qfrc_bias`.

Thank you very much for your answer. I wish you good luck

**Comment by kevinzakka** [comment]
Hi @jheyeo222, here is some [sample code](https://github.com/kevinzakka/mjctrl/blob/main/opspace.py) for doing operational space control and it involved computing a mass matrix and gravity compensation.

**Comment by jheyeo222** [comment]
> Hi @jheyeo222, here is some [sample code](https://github.com/kevinzakka/mjctrl/blob/main/opspace.py) for doing operational space control and it involved computing a mass matrix and gravity compensation.

thank you,  I wish you success in your endeavors.
