### ISSUE TITLE
Chaining objects with each other (joints question)

### ISSUE THREAD

**Issue by manavkulshrestha** [google-deepmind/mujoco#1090]
Hi,

I'm a student and I'm trying to use MuJoCo for some crowd simulation.

I'm looking for some help with having objects move as if they were linked with each other through invisible chains. I understand that mujoco's joints work differently and that they do not restrict, but add degrees of freedom. However, I'm unable to understand how I would create dynamics that I need for my project. 

Say I wanted 3 balls that are connected to each other through some kind of string so that when I move one enough, the others would move with it. In something like pybullet, I would simply add some constraints to ensure they remain a fixed distance away from each other. How can I accomplish this with mujoco's joints?

**Comment by yuvaltassa** [comment]
You don't do this with joints, you do this with [tendons](https://mujoco.readthedocs.io/en/latest/XMLreference.html#tendon) or [equality constraints](https://mujoco.readthedocs.io/en/latest/XMLreference.html#equality)
