### ISSUE TITLE
multi-threading and data reproducibility

### ISSUE THREAD

**Issue by pmh5050** [google-deepmind/mujoco#1093]
Hello,

I'm a student, and I'm attempting to use MuJoCo for simulations.

I'm seeking assistance with multi-threading and ensuring data reproducibility.

According to the documents below, MuJoCo appears to be well-suited for parallel computing:
1) [Reproducibility](https://mujoco.readthedocs.io/en/latest/computation/index.html#reproducibility): `MuJoCo's simulation pipeline is entirely deterministic and reproducible.`
2) [Multi-threading](https://mujoco.readthedocs.io/en/latest/programming/simulation.html#multi-threading): `the unified data structure mjData which contains everything that changes over time.`

However, when I attempt to work with a thread pool, I encounter some issues related to reproducibility.

+ Each thread has its own mjData `data[i]`
+ Each thread performs the following command with every call:
```c++
mj_resetData(model, data[i]);
for(int t = 0; t < steps; t++)
{
    mj_step(model, data[i]);
}
```

It usually produces the same outcomes (e.g., `steps 151`, `steps 153`), but occasionally exhibits undesired behavior. I'm curious about what might be causing these different outcomes. Can you recommend a solution to address this issue?

`steps 151`
![steps151](https://github.com/google-deepmind/mujoco/assets/38609785/30a82a64-d63a-4cbf-85ae-ba9647a77c58)

`steps 152` (see the lower-right image)
![steps152](https://github.com/google-deepmind/mujoco/assets/38609785/40865b4a-0acb-4ff1-89a0-4a588ba43651)

`steps 153`
![steps153](https://github.com/google-deepmind/mujoco/assets/38609785/fbd41e22-74b2-44e9-b0b8-4af49c645eaa)

**Comment by aravindsiv** [comment]
From [here](https://mujoco.readthedocs.io/en/latest/computation/index.html#reproducibility): 

Have you tried disabling warmstarts like so:
```
<option>
  <flag warmstart="disable"/>
</option>
```
and checking if the behaviors persist?

**Comment by pmh5050** [comment]
I've come across similar information in  [#1000](https://github.com/google-deepmind/mujoco/issues/1000), but this approach won't resolve our problem.

**Comment by saran-t** [comment]
This is fairly clearly not a warmstart issue. Can you post your code?

**Comment by yuvaltassa** [comment]
There is something very strange about your your code snippet. Does `i` iterate over time or over threads? I would have expected

```C
mj_resetData(model, data[i]);
for(int t = 0; t < steps; t++)
{
    mj_step(model, data[i]);
}
```

**Comment by pmh5050** [comment]
I apologize for the confusion. I made a mistake when I wrote the code snippet. As you mentioned, the variable `i` iterates over threads.

**Comment by pmh5050** [comment]
I've identified the cause of this issue. It is related to the internal static variable of the IK library and is not related to MuJoCo. As a result, I am closing this issue, and I sincerely apologize for any inconvenience or time that may have been taken up. :cry:
