### ISSUE TITLE
Not able to control the cable length for actuating the manipulator

### ISSUE THREAD

**Issue by rishabkr29** [google-deepmind/mujoco#1096]
Hi,

I'm a student and I'm trying to use MuJoCo for My project work.

I'm looking for some help with developing the xml file for controlling the cable length for actuating the manipulator.

Here is a model which explains my question:

<mujoco>
 <compiler autolimits="true"/>
   <worldbody >

      <light diffuse=".5 .5 .5" pos="0 0 10" dir="0 0 -1"/>
      <geom type="plane" size="0.8 0.8 0.1" rgba="1 1 1 1"/>

      <body name = "1st Link" pos="0 0 0" euler="0 0 0" >
         <joint name="Revolute Joint" axis="0 0 1 " damping="0.1"/>
         <geom name="Revolute Joint" type="cylinder"  pos="-0.05 0 0.1" euler="0 0 0" size=".04 .01"  rgba="0 .9 0 1"/>
         <geom name="1st Link" type="box" pos="0.15 0 0.1" euler="0 0 0" size=".2 0.04 .01" />   
         <geom name="offset" type="box" pos="0.15 0 0.1" size=".01 0.09 0.01" /> 
         <site name="l1" pos="0.15 0.09 0.1" rgba="0 .9 0 1"/>   
         <site name="l2" pos="0.15 -0.09 0.1" rgba="0 .9 0 1"/>
      </body>

      <body name="Pully1" pos="0 0 0" euler="0 0 0">
         <joint name="Pully1" type="slide"  axis="0 1 0 " damping="0.1"/>
         <geom name="Pully1" type="cylinder" pos="-0.05 0.2 0.1" euler="0 0 0" size=".01 .01" rgba="0 .9 0 1"/>
         <site name="Pully1" pos="-0.04 0.2 0.1"  rgba="0 0 1 1"/>
         <site name="Motor1" pos="-0.1 0.2 0.1" rgba="0 .9 0 1"/>   
         <geom name="Motor1" type="box" pos="-0.1 0.2 0.1" size=".01 .01 0.01" rgba="0 .9 0.9 1"/>
      </body> 
        <body name="Pully2" pos="0 0 0" euler="0 0 0">
         <joint name="Pully2" type="slide"  axis="0 1 0 " damping="0.1"/>
         <geom name="Pully2" type="cylinder" pos="-0.05 -0.2 0.1" euler="0 0 0" size=".01 .01" rgba="0 .9 0 1"/>
         <site name="Pully2" pos="-0.04 -0.2 0.1"  rgba="0 0 1 1"/>
         <site name="Motor2" pos="-0.1 -0.2 0.1" rgba="0 .9 0 1"/>   
         <geom name="Motor2" type="box" pos="-0.1 -0.2 0.1" size=".01 .01 0.01" rgba="0 .9 0.9 1"/>
      </body> 
      
  </worldbody>

  <tendon>
    <spatial name="rope1" range="0 0">
      <site site="l1"/>
      <site site="Pully1"/>
      <site site="Motor1" />
    </spatial>
  </tendon>
   
  <tendon>
    <spatial name="rope2" range="0 0">
      <site site="l2"/>
      <site site="Pully2"/>
      <site site="Motor2" />
    </spatial>
  </tendon>

  <actuator>
    <position name="Motor1" joint="Pully1" ctrlrange="-.05 .05" kp="100"/>
  </actuator>
   <actuator>
    <position name="Motor2" joint="Pully2" ctrlrange="-.05 .05" kp="100"/>
  </actuator>

</mujoco>

Here is a screenshot 
![Screenshot 2023-10-14 000417](https://github.com/google-deepmind/mujoco/assets/110694658/58c48cf6-ad5c-4646-a853-e901b07676bc)
illustrating my question:

**Comment by yuvaltassa** [comment]
Examine the model shown in the video in [this section](https://mujoco.readthedocs.io/en/latest/XMLreference.html#actuator-adhesion) (link to model therein)
