### ISSUE TITLE
Extending actuator/plugin to have all parameters of actuator/general (to enable n-order ODEs for Plugins)

### ISSUE THREAD

**Issue by VasilyRakche** [google-deepmind/mujoco#1098]
Hi, 
I would like to define an `act_dot` within the plugin instance. So basically, to have [oscillator example functionality](https://github.com/google-deepmind/mujoco/blob/36b30e4500e2d1950b7992621cac3d193de3c980/test/engine/engine_forward_test.cc#L453) defined within the plugin. 

There is a possibility to avoid plugin of course and just define an `actuator/general`. However, plugin instance provide additional features and I think project code separation would be much better. I don't understand why `actuator/plugin` should not have all the features of `actuator/general` anyways.

Btw, I wrote a plugin successfully but realized too late I can not define `actdim` for it (to have custom ODEs with **n-order** dynamics).

Really appreciate your help.

**Comment by yuvaltassa** [comment]
You are right, we also realised this feature was missing, will update here when it's implemented.

**Comment by nimrod-gileadi** [comment]
I didn't add literally all the attributes, but I added the ones relevant for dyntype, and allowed plugins to specify an actdim (through a callback).
