### ISSUE TITLE
unity ads error

### ISSUE THREAD

**Issue by Anashb2007** [google-deepmind/mujoco#1099]
Plugin 'Assets/GoogleMobileAds/GoogleMobileAds.dll' has the same filename as Assembly Definition File 'Assets/GoogleMobileAds/GoogleMobileAds.asmdef'. Rename the assemblies to avoid hard to diagnose issues and crashes.

**Comment by saran-t** [comment]
Closing this issue since it doesn't seem to be related to MuJoCo. I think you wanted https://github.com/googleads/googleads-mobile-unity
