### ISSUE TITLE
MjData has no attribute solver_iter

### ISSUE THREAD

**Issue by NotAndres** [google-deepmind/mujoco#1107]
When using version 3.0.0 of MuJoCo and working with Gymnasium I'm getting the following error while trying to render any MuJoCo environment in "human" mode

'mujoco._structs.MjData' object has no attribute 'solver_iter'

Downgrading to version 2.3.7 fixes the issue.

I'm guessing the error is related to this line in the change log

Renamed mjData.solver_iter to solver_niter. Both this member and mjData.solver_nnz are now integer vectors of length mjNISLAND

**Comment by rodrigodelazcano** [comment]
Hey @NotAndres thank you for finding this, I made this PR https://github.com/Farama-Foundation/Gymnasium/pull/746 to fix it. Next time, for Gymnasium related issues it's best to post the issue first in the Gymnasium repo.
