### ISSUE TITLE
The support for AMD CPUs and integrated Radeon graphics is greatly needed

### ISSUE THREAD

**Issue by Nghiattk27** [google-deepmind/mujoco#1109]
My laptop is equipped with an AMD Ryzen 7 7730U CPU and integrated AMD Radeon graphics. I'm aware of the issue regarding the inability to display the Mujoco interface (https://github.com/google-deepmind/mujoco/issues/639, https://github.com/google-deepmind/mujoco/issues/894), and I've resorted to using an alternative solution (https://github.com/rohanpsingh/mujoco-python-viewer). While this workaround is temporary, I still hope for support from the Mujoco development team. However, when I updated to Mujoco 3.0.0, it seems that this temporary solution is no longer effective, and the problems with displaying the user interface persist for AMD's integrated chip and graphics card. I don't believe this is an insurmountable issue; it might be a coding error causing the interface display problem. Nevertheless, I am hopeful for a solution that would allow me to use Mujoco on my laptop.

**Comment by yuvaltassa** [comment]
We are in the process of acquiring an AMD-equipped machine in order to reproduce and hopefully finally resolve this issue

**Comment by Nghiattk27** [comment]
I'm very glad to hear that. I hope the issue will be resolved soon for the AMD user community

**Comment by saran-t** [comment]
Let's track progress in https://github.com/google-deepmind/mujoco/issues/639, I've asked for a bit of help debugging over there. I'm reasonably hopeful that we'll finally get this fixed!
