### ISSUE TITLE
[viewer/option/pause-update] option triggers full-screen model instead

### ISSUE THREAD

**Issue by vikashplus** [google-deepmind/mujoco#1110]
On simulate as well as the Python viewer, [viewer/option/pause-update] option triggers the full-screen model instead. This behavior seems to be new in mujoco 3.0.0. The mujoco 2.3.7 does not exhibit this issue. 
 

- Include the following context:
  - Operating system:: Ubuntu 18.08
  - MuJoCo version (and if the bug is new, the version where it used to work):: 3.0.0
  - For Python issues, what bindings are you using (i.e `mujoco`, `dm_control`)?:: `mujoco`, `dm_control`

**Comment by nimrod-gileadi** [comment]
I can reproduce this. Thanks for the report.
