### ISSUE TITLE
More descriptive error messages for unsupported features during model validation for MJX

### ISSUE THREAD

**Issue by driesmarzougui** [google-deepmind/mujoco#1113]
When doing [MJX validation](https://github.com/google-deepmind/mujoco/blob/dc8bac2f4dd7353208fa92d40bb3fafb7a82eb0a/mjx/mujoco/mjx/_src/device.py#L120) of a model with a currently unsupported feature (e.g. `cone="elliptic"`), the error message could be made more descriptive. Currently, it returns `NotImplementedError: {1} not implemented.`

**Comment by kevinzakka** [comment]
Fixed by e4a9f535a4fe05c2120ae9cd7afb17665f917e6b.

**Comment by btaba** [comment]
Thanks for the report @driesmarzougui ! This was pushed out
