### ISSUE TITLE
Python Viewer: Clear displayed error post successful model load

### ISSUE THREAD

**Issue by vikashplus** [google-deepmind/mujoco#1116]
1. Load a healthy model on the viewer using `python -m mujoco.viewer --mjcf=model.xml`
2. Now edit the model.xml to introduce a bug
3. Reload the viewer. The viewer correctly shows the compilation error 
4. Now undo/fix the model edit/error
5. Hit reload on the viewer to pick the new model. 
    - As there is no error, the model loads just fine
    - The old error from step 3 is on display. If my understanding is correct - there shouldn't be any error message on the display as the model load was successful 
![image](https://github.com/google-deepmind/mujoco/assets/12837145/c4b5d15c-8b2e-4106-8b11-5e6012adab6c)

Version: MuJoCo 3.9
OS: Ubuntu 18.04

**Comment by saran-t** [comment]
Can you check if this issue also happens with the native simulate app?

**Comment by kevinzakka** [comment]
@saran-t Native simulate reloads the model fine and the error message disappears.

**Comment by vikashplus** [comment]
@kevinzakka beats me to this. 
Thanks Kevin :)
