### ISSUE TITLE
What are the differences between subtree_com and xipos?

### ISSUE THREAD

**Issue by HyunyoungJung** [google-deepmind/mujoco#1119]
Hi, 
I am a student and currently using mujoco MJX to implement my own environment.
I'm looking for some help with difference between xipos and subtree_com in MjData.
There are two values used in  _pos_vel function in the MJX tutorial.

```python
def _pos_vel(
      self, data: mjx.Data
      ) -> Tuple[Transform, Motion]:
    """Returns 6d spatial transform and 6d velocity for all bodies."""
    x = Transform(pos=data.xpos[1:, :], rot=data.xquat[1:, :])
    cvel = Motion(vel=data.cvel[1:, 3:], ang=data.cvel[1:, :3])
    offset = data.xipos[1:, :] - data.subtree_com[
        self.model.body_rootid[np.arange(1, self.model.nbody)]]
    xd = Transform.create(pos=offset).vmap().do(cvel)
    return x, xd
``` 
According to the document, xipos is the cartesian coordinate of body com and subtree_com is also the com of kinematic subtre which in my understanding, is the same.
What are the differences between xipos and subtree_com?

**Comment by saran-t** [comment]
`xipos` is the CoM of the body itself disregarding any children, while `subtree_com` takes into account all children.
