### ISSUE TITLE
Question about the meaning of cvel

### ISSUE THREAD

**Issue by HyunyoungJung** [google-deepmind/mujoco#1120]
Hi,

I'm a student and I'm trying to use MuJoCo for RL training environment.

I'm looking for some help with an explanation of mjData.cvel.

The cvel is explained as com-based velocity in the document. 
Let's say there is one articulated system and one plane ground in the model.
**In this case, does the cvel mean the velocity of each body's COM expressed in the frame whose origin is at the com of the whole articulated system, and the direction is the same as in the world frame?**
**or is it the velocity of each body frame expressed in the frame whose origin is at the com of the whole articulated system, and the direction is the same as in the world frame?**

Thank you in advance.

**Comment by yuvaltassa** [comment]
https://mujoco.readthedocs.io/en/stable/APIreference/APItypes.html#c-frame-variables
