### ISSUE TITLE
[MJX] Sensor support

### ISSUE THREAD

**Issue by driesmarzougui** [google-deepmind/mujoco#1122]
Will the currently available MuJoCo sensors be ported to MJX as well?

**Comment by yuvaltassa** [comment]
Relatedly, regardless of what the answer is (I'll let @erikfrey reply), it should be in the [feature parity section](https://mujoco.readthedocs.io/en/latest/mjx.html#feature-parity) 🙂

**Comment by erikfrey** [comment]
Yes indeed!  We plan to port sensors to MJX.  Will add this to the documentation.
