### ISSUE TITLE
Feet velocity measure in Barkour-v0 training example in MJX tutorial

### ISSUE THREAD

**Issue by HyunyoungJung** [google-deepmind/mujoco#1123]
Hi,

I'm a student and I'm trying to use MuJoCo for RL training environment.

I'm looking for some help with _get_feet_pos_vel function of Barkour-v0 in [here](https://colab.research.google.com/github/google-deepmind/mujoco/blob/main/mjx/tutorial.ipynb#scrollTo=y79PoJOCIl-O).

Here is the function:

```python
def _get_feet_pos_vel(
            self, x: Transform, xd: Motion) -> Tuple[jax.Array, jax.Array]:
        offset = Transform.create(pos=self._feet_pos)
        pos = x.take(self._feet_index).vmap().do(offset).pos
        vel = offset.vmap().do(xd.take(self._feet_index)).vel
        return pos, vel
```
Here, the offset is from the knee joint to the foot not from the lower leg's center of mass to the foot. But the xd is expressed w.r.t COM of the body.
In my understanding transforming using offset doesn't give the feet velocity w.r.t feet body.
Is this a bug? or am I missing some important part of the implementation?

**Comment by btaba** [comment]
Hi @HyunyoungJung , thanks for the report. Indeed `offset = data.xipos[1:, :] - data.subtree_com[` should be `offset = data.xpos[1:, :] - data.subtree_com[`. We'll patch it
