### ISSUE TITLE
When I move the first axis in controlling the microgravity arm, the second axis moves unintentionally

### ISSUE THREAD

**Issue by Issey-724** [google-deepmind/mujoco#1125]
Hi,

I'm a engineer and I'm trying to use MuJoCo for simulation robot arm control in microgravity (in space).

For example, using the official Universal Robot model from the [Model Gallery](https://github.com/google-deepmind/mujoco_menagerie/tree/main/universal_robots_ur5e), I set the Gravity to **gravity="0 0 0"**. In this state, when I move only the first axis, the second axis tilts as if centrifugal force is acting. Since centrifugal force does not operate in a zero-gravity state, I do not understand the reason behind this phenomenon.

Here is a screenshot / video, illustrating my question:

[Screencast from 10-13-2023 06%3A34%3A23 PM.webm](https://github.com/google-deepmind/mujoco/assets/148838844/75cb5fc4-1c7e-4bf2-99fe-0ce437f66958)

I'm looking for some help with this problem.

- Is MuJoCo not compatible with microgravity simulations, or are there issues with MuJoCo's calculations?
- Are there any additional settings required to simulate microgravity, besides setting gravity to zero?

Universal Robot hasn't undergone any parameter changes besides setting gravity to zero.

**Comment by saran-t** [comment]
> Since centrifugal force does not operate in a zero-gravity state

Centrifugal force applies to any rotating body, nothing to do with gravity.
