### ISSUE TITLE
About mj_objectVelocity

### ISSUE THREAD

**Issue by Balint-H** [google-deepmind/mujoco#1126]
Hello,

Many thanks for the continuous support. I have a question regarding the function `mj_objectVelocity` from the API. When used on a body, the velocity returned by this seems to be the velocity of the body's CoM (i.e., the velocity from which the kinetic energy corresponding to that body can be calculated). Is there some configuration of this function, or other API functions or mjData fields that returns the velocity of the body frame itself (which was defined as the body's position in the XML)? Potential solutions I considered:

1. Placing a site at the body frame origin, calling `mj_objectVelocity` on that.
2. Calculate the relative point velocity from the angular velocity and combine with the CoM linear velocity

Am I misunderstanding something about body frames? Is there an easier more straightforward method for this?

 I'm using the C#/Unity bindings of MuJoCo. Here's my extension method for getting the global velocity of the body:

```c#

public static unsafe Vector3 GlobalVelocity(this MjBaseBody body, MujocoLib.mjtObj objType = MujocoLib.mjtObj.mjOBJ_BODY)
{
    MujocoLib.mjModel_* Model = MjScene.Instance.Model;
    MujocoLib.mjData_* Data = MjScene.Instance.Data;
    Vector3 bodyVel = Vector3.zero;
    double[] mjBodyVel = new double[6];
    fixed (double* res = mjBodyVel)
    {
        MujocoLib.mj_objectVelocity(Model, Data, (int)objType, body.MujocoId, res, 0);
        // Linear velocity is in the last 3 entries
        bodyVel = MjEngineTool.UnityVector3(MjEngineTool.MjVector3AtEntry(res, 1));
    }
    return bodyVel;
}

```

I'm interested in a variant that returns the velocity of the non-inertial body frame. The complicated version I have now is this (with a few helper functions omitted):

```c#

public static Vector3 GetBodyFrameVelocity(this mjBody)
{ 
    var velocity = mjBody.GetGlobalVelocity();
    var angularVelocity = mjBody.GetGlobalAngularVelocity();
    var framePosFromInertial = -mjBody.GetLocalCenterOfMassMatrix().GetPosition();
    return Vector3.Cross(TransformMatrix.MultiplyVector(framePosFromInertial), angularVelocity) + velocity;
}

```

**Comment by yuvaltassa** [comment]
> Is there an easier more straightforward method for this?

Yes. Pass `mjOBJ_XBODY` instead of `mjOBJ_BODY`. This is documented [here](https://mujoco.readthedocs.io/en/latest/APIreference/APItypes.html#mjtobj) (ish).

We could maybe rename `mjOBJ_BODY` → `mjOBJ_IBODY`, but I'm worried that will break people's code.

This is true for everything that accepts an `mjtObj` as a frame reference, like `mj_jac`, sensors etc.
