### ISSUE TITLE
How to identify the parameter of frictionloss, armature, damping and stiffness of a motor?

### ISSUE THREAD

**Issue by Uptomylimit** [google-deepmind/mujoco#1131]
Hi,

I'm a student and I'm trying to use MuJoCo for simulation.

I have done my simulation and now I want to transfer my simulation to real. 

However, I find that I don't know how to get the parameter of my real motor, so that I can write the parameter of frictionloss, armature, damping and stiffness in xml and make my simulation more reliable and real.

Can you tell me how to identify the parameter of frictionloss, armature, damping and stiffness of a real motor?

**Comment by yuvaltassa** [comment]
We intend to publish a tutorial soon on how to do this but the short answer is you need to match the trajectories from the real robot to the model. Nonlinear least squares works very well for this.
