### ISSUE TITLE
Query Regarding Obtaining Overlapping Volume Between Two Models in MuJoCo Environment

### ISSUE THREAD

**Issue by kankanzheli** [google-deepmind/mujoco#1150]
Hi,

I'm a student and I'm trying to use MuJoCo for research.

I am currently working with the MuJoCo environment and have encountered a challenge that I hope you can assist me with. Specifically, I am interested in determining the overlapping volume between two models within the MuJoCo simulation. I would like to know if there is a built-in function or method to achieve this, or if you could recommend a suitable approach to compute the overlapping volume.

Any insights or guidance on this matter would be greatly appreciated.

Thank you for your time and assistance. I look forward to your response.

**Comment by yuvaltassa** [comment]
There is currently no such function, sorry.
If you write it, feel free to send us a PR, this seems useful 🙂
