### ISSUE TITLE
Setting collision coefficients for geometry objects added through user_scn

### ISSUE THREAD

**Issue by kankanzheli** [google-deepmind/mujoco#1155]
Hi,

I'm a student and I'm trying to use MuJoCo for study.

I am currently using MuJoCo for obstacle avoidance experiments and need to introduce random geometry objects into the environment through the user_scn mechanism.

I am wondering how I can set collision coefficients (i.e., contype and conaffinity as they appear in the XML specifications) for these dynamically added geometric bodies. The goal is to have fine-grained control over which objects collide with one another.

Any guidance or example code on how to achieve this would be greatly appreciated.

Thank you for your time and assistance.

**Comment by yuvaltassa** [comment]
The `mjvScene` is purely visual. You cannot dynamically add colliding objects.
