### ISSUE TITLE
looking for help to getting start with environment physical simulation

### ISSUE THREAD

**Issue by SimonC1233** [google-deepmind/mujoco#1156]
Hi,

I'm a student who is new to Mujoco (and all simulators really), and I'm trying to use MuJoCo for physical simulation for my project.

I'm just getting start with this. At current stage, I'm trying to build a very simple case (maybe with just a cube on a ground or in water) with environment restrictions, i.e. frictions, viscosity or randomrized applied forces. And I want to understand how to customerize my environment model, for example adding equations of applied forces in it.

There are so limited inductions online of customerized physical model and I'm really new to robotic/simulation field,  so I'm desperatly looking for some help with suggestions just to begining. Much appreciated for any kinds of suggestions, like what part of Mujoco or keywords should I chenk in detail? or is there any guide project or code example to bring me in?

Many thanks!

**Comment by Balint-H** [comment]
The official tutorials on the main README are a good place to start. The tutorials in the DM Control repo are also helpful on understanding how to work with MJCF files.

While slightly outdated, (Pranav Bhounsule's tutorial series)[https://pab47.github.io/mujocopy.html] is also one I often recommend to take a look at.

I do recommend going through or at least skimming through the MuJoCo documentation's Programming/Simulation and Modeling sections. More information on specifically customizing a scene to your needs will be found in the XML reference.

If you want a visual way to build and manage scenes you could eventually take a look at the Unity plugin, but I don't recommend starting there immediately.

More information on yours goals will also inform what to try first.
