### ISSUE TITLE
Soft contact modelling documentation clarification 

### ISSUE THREAD

**Issue by Aditya-1729** [google-deepmind/mujoco#1165]
Hello,

I'm a student and I'm trying to use MuJoCo for a contact rich robotic task for my master thesis 

I went through the documentation to evaluate how the solimp and solref parameters influence the depth of indentation at contact. 
At equilibrium, I measured this depth and it matches the analytically derived depth using the equation:
 $r = \frac{(1-d)\times a_{0}} { stiffness}$
 (I simulated a ball falling from a certain height for this experiment, $a_0$ is the gravitational acceleration in this case.). 
   
This equation, however doesnt account for the mass of the object and consequently, changing the mass of the object didnt bring about a difference. This is counterintuitive to me because objects of different masses should produce different indentations at equilbrium. So, can you please comment on how can one account for object mass here?

**Comment by yuvaltassa** [comment]
The contact model is explicitly designed to be mass-invariant. However while `solimp` is always mass invariant, `solref` with [negative semantics](https://mujoco.readthedocs.io/en/latest/modeling.html#reference) is not. If you use negative semantics the transient penetration will be mass-dependent.
