### ISSUE TITLE
Can I speed up the integration?

### ISSUE THREAD

**Issue by nor-code** [google-deepmind/mujoco#1169]
Hi, @yuvaltassa
I try to train the robot to move along a given trajectory. I use Python, in the code below I create the environment in which the simulation will take place, can I speed up the integration time (x1.5 x3)? There are exists option, that accelerate integration?
(i.e. <option accelerateTime = "1.5"/> ) Because in simple Mujoco(in sense without python library) i can accelerate simulation.

![Снимок экрана от 2023-11-05 22-31-18](https://github.com/google-deepmind/mujoco/assets/42301816/4227fbfe-e117-45a4-b289-f8970ce7fcca)

**Comment by yuvaltassa** [comment]
Try to increase the timestep.
Why are you using RK4?
Read this

https://mujoco.readthedocs.io/en/latest/computation/index.html#numerical-integration

**Comment by nor-code** [comment]
@yuvaltassa , sorry, i think You don't understand what i mean exactly.  there is ability run simulation faster than real time mode in 2 or more times (as rewind video)? I use RK4 because need high precition.

**Comment by yuvaltassa** [comment]
You are right, I do not understand what you are asking. 
Your latests clarification did not help.
Feel free to try asking again.

**Comment by nor-code** [comment]
@yuvaltassa, let considered simple diff. eq. x'' = 0 (stone fall with 0 initial velocity). Suppose that has falling 5 second and we want know it velocity/coordinate every 0.005 [s]. For simulation of this process then we don't wait all 5 second. our CPU can solve it faster. And as I understand it, the engine solves equations in approximately real time, i.e. 1 second in the simulation = 1 second in our world? if this is so, then why is there no way to speed up the numerical integration. This will reduce training time.
P.S. I don’t know English well, so please excuse me if I express myself incorrectly.

**Comment by yuvaltassa** [comment]
Simulation in MuJoCo is usually much faster than real time (for example a humanoid simlates at ~200x real-time on a single CPU thread). Where are you seeing anything that limits it to real time? In the `simulate` viewer there is time keeping which introduces pauses in order to try and match real-time (or slower), but there is no such pausing anywhere else.

**Comment by nor-code** [comment]
@yuvaltassa thanks, now it is clear!
