### ISSUE TITLE
Custom XML/URDF pipeline

### ISSUE THREAD

**Issue by dibbla** [google-deepmind/mujoco#1189]
Hi,

I'm a student and I'm trying to use MuJoCo for custom RL environment for custom robot. I was using SolidWorks for modeling and exporting things into Mujujo for RL training.

I'm looking for some advices in working in this pipeline. I have created a simple wheeled leg robot in SolidWorks and export them with sw2urdf extension from ROS [link](https://wiki.ros.org/sw_urdf_exporter). However, although my robot seems good in SolidWorks, there were some joints that slipped out.

My exported assets can be found [here](https://drive.google.com/drive/folders/1xcBCoqocaM4FNglstmKCxgfUw3_X7Px4?usp=sharing). This folder is the direct output of ROS sw2urdf extension.  I just launch the viewer and drag the urdf into the viewer. The result is kind of hilarious.

![image](https://github.com/google-deepmind/mujoco/assets/72083122/412a1ee6-5a4c-4737-985d-205d244e537d)

I'm new to robotics, any suggestions to this issue/pipeline would be appreciated.

**Comment by yuvaltassa** [comment]
Can you please load your URDF in something else to confirm that the issue is with MuJoCo URDF import rather than `sw2urdf` ?

**Comment by dibbla** [comment]
> Can you please load your URDF in something else to confirm that the issue is with MuJoCo URDF import rather than `sw2urdf` ?

Hi Yuval! 

Thanks for the fast reply! I found indeed the sw2urdf broken. The key is to, not only create the reference axis in SolidWorks, but also create the corresponding coordinate system. That solves the problem.
