### ISSUE TITLE
[MuJoCo 3.0.0 python bindings]: viewer.user_scn.flags are not respected in the actual rendered viewer

### ISSUE THREAD

**Issue by lksmac** [google-deepmind/mujoco#1190]
Hi,

after upgrading to MuJoCo 3.0.0 (python bindings), changes I make to the `viewer.user_scn.flags` are **not respected** in the actual rendered viewer scene anymore.

Example:
```
viewer = launch_passive(m, d)
viewer.lock()
viewer.user_scn.flags[mujoco.mjtRndFlag.mjRND_SHADOW] = 0
viewer.user_scn.flags[mujoco.mjtRndFlag.mjRND_REFLECTION] = 0
viewer.sync()
```

The [documentation](https://mujoco.readthedocs.io/en/3.0.0/python.html#pyviewerpassive) states that:
"user_scn: an mjvScene object that allows users to add custom visualization geoms to the rendered scene. This is separate from the mjvScene that the viewer uses internally to render the final scene [...]"

My question: **How is it possible to change the flags of the internal mjvScene that the viewer uses for rendering?**

Thanks for the help.

**Comment by vikashplus** [comment]
I am programmatically trying to enable/disable Fog by changing the `viewer.user_scn.flags` which is also not working. I believe this is aligned with this thread's request.

**Comment by vikashplus** [comment]
Thanks @saran-t for this feature :)
