### ISSUE TITLE
Combining Composites (Cables)

### ISSUE THREAD

**Issue by tudorjnu** [google-deepmind/mujoco#1195]
Hi,

I'm a student, and I'm trying to use MuJoCo for simulation of a guidewire.

I've been trying to attach a site at the tip of the guidewire without the need to know the tip position. Is there a way to do this directly in `xml` or `pymjcf` is needed? 

I have a minimal example in which I'm trying to connect a body at the tip, but this doesn't seem to work as the body is placed at the first element. 

<details>
  <summary>minimal XML</summary>

```XML
<mujoco model="cable">
<extension>
        <plugin plugin="mujoco.elasticity.cable"/>
</extension>
<size memory="1G"/>
<worldbody>
<body name="core" pos="0 0 0" euler="0 0 {math.pi / 2}">
    <joint name="slider" type="slide" axis="1 0 0" stiffness="0" damping="0"/>
    <joint name="rotator" type="hinge" axis="1 0 0" stiffness="0" damping="5" armature="0.1"/>
    <composite prefix="test" type="cable" curve="s" count="31" size="0.3" offset="0.00025 0 0" initial="none">
        <geom type="capsule" size="0.0008" rgba="1 1 1 1" condim="1" density="6450" margin="0.02"/>
        <joint kind="main" damping="0.5" stiffness="0.01" margin="0.02"/>
        <plugin plugin="mujoco.elasticity.cable">
            <config key="twist" value="1e6"/>
            <config key="bend" value="1e9"/>
            <config key="vmax" value="0.005"/>
        </plugin>
    </composite>
</body>
<body name="head" pos="0 0 0">
    <geom size=".01"/>
</body>
</worldbody>
<equality>
    <connect name="right_boundary" body1="B_last" body2="head" anchor=".025 0 0"/>
</equality>
<contact>
    <exclude body1="B_last" body2="head"/>
</contact>
<actuator>
    <velocity name="slider_actuator" joint="slider"/>
    <general name="rotator_actuator" joint="rotator" biastype="none" dynprm="1 0 0" gainprm="40 0 0" biasprm="0 40 0"/>
</actuator>
</mujoco>
```

</details>

This leads me to the next question: Is it possible to connect two cables? This helps in creating different sections of different stiffness. 

Thank you!

**Comment by quagla** [comment]
Are you saying that you can't find `B_last`? That's because you added `prefix="test"` so you have to look for `testB_last`. Feel free to reopen if this doesn't help.

**Comment by tudorjnu** [comment]
Ohh, my bad. How about the follow-up question. Is it possible to connect two cables one after the other without the need to hard code the position?
