### ISSUE TITLE
Controller compensating bias forces doesn't behave as expacted

### ISSUE THREAD

**Issue by VasilyRakche** [google-deepmind/mujoco#1200]
Hi guys,

I have written a simple controller that should apply forces to counteract **all external forces on selected joints** (as a result I am expecting those joints will not move). The controller is written as follows:
```cpp
// mjcb_control callback 
void mycontroller(const mjModel* m, mjData* d)
{
  //write control here
    for (int i=0; i<m->nv; i++) {
      if (m->actuator_group[i] == 777) {                                                         
        d->qfrc_applied[i] = d->qfrc_bias[i];
      } else {
        d->qfrc_applied[i] = 0;
      }
    }


  if ( loop_index%data_frequency==0) {
    std::printf("q1:%f\tq2:%f\tq3:%f\n",d->qpos[0],d->qpos[1],d->qpos[2]);
    //   save_data(m,d);
    }
  loop_index = loop_index + 1;
}
```

I am defining simple actuators with certain groups for those for which I want to compensate all the forces (make their position stationary)
```JavaScript
<actuator>
  <general joint="joint_0" name="ACT0" group="777"/>
  <general joint="joint_1" name="RIGID1" />
  <general joint="joint_2" name="ACT2" group="777"/>
</actuator>
```

I am not introducing friction, contact and other constraints in order to make the task as simple as possible (just compensate carioles and gravity).

What I am getting is that all system becomes unstable. You can find minimal example in [VasilyRakche/pendulum_force_compensation](https://github.com/VasilyRakche/pendulum_force_compensation)

Appreciate your help.

**Comment by yuvaltassa** [comment]
I find this very confusing. You are writing directly to qfrc_applied but also to qfrc_actuation via the actuators?

I can recommend either / both
- Make a real MWE: one dof, one actuator and we might be able to diagnose.
- Read engine_forward.c carefully, I suspect you have a basic misunderstanding that I am not able to infer from what you wrote.
