### ISSUE TITLE
Reaction forces at an equality constraint

### ISSUE THREAD

**Issue by shubhamsk1999** [google-deepmind/mujoco#1217]
Hi,

I'm a student and I'm trying to use MuJoCo for simulating a humanoid robot holding a box with both the hands. I have added one ball joint by adding the box as a child of one of the hands and for the other hand I have added an equality constraint. This works fine and now I want to find out the reaction forces at each of these ports of interaction. How do I find out the forces for the equality constraint?

I know qfrc_constraint gives the generalized constraint force. But it combines all the constraints right? How do I get the forces at that particular equality constraint. 

Thank you

**Comment by yuvaltassa** [comment]
Attach the equality constraint to a site on a small static (no joints) child body of the hand. Put a [force sensor](https://mujoco.readthedocs.io/en/latest/XMLreference.html#sensor-force) on this static body. The measured force (between the static body and the hand) will equal the force through the constraint.
