### ISSUE TITLE
Unity plug-in import adds explicit inertial specification

### ISSUE THREAD

**Issue by erez-tom** [google-deepmind/mujoco#122]
MuJoCo computes the inertial properties of bodies without explicit [`inertial`](https://mujoco.readthedocs.io/en/latest/XMLreference.html#body-inertial) elements by looking at the density and mass of the geoms attached to the body.  However, the [load-save-load workflow](https://mujoco.readthedocs.io/en/latest/unity.html#importer-workflow) of the importer results in all bodies having a component explicitly specifying inertial properties.  This will be fixed in the next version of MuJoCo.

**Comment by yuvaltassa** [comment]
This was fixed a long time ago...
