### ISSUE TITLE
Control actuators via Python bindings

### ISSUE THREAD

**Issue by assadollahi** [google-deepmind/mujoco#1224]
Hi,

I'm a machine learning engineer and I'm trying to use MuJoCo for controlling an open-source 3d printable humanoid Kayra.

I'm looking for some help with Python bindings to modify the position actuators from outside, 
for example by controlling them using the same keyframes that I'm using for the real robot.

Here is a model which explains my question:

    <body name="4R_Link" pos="0 0 1.8" euler= "-0.0 0.0 0.0">
        <joint type="free"/>

        <inertial pos="0 0 0.1" mass="0.10" diaginertia="0.005 0.005 0.005"/>
        <geom mesh="4R_knee" type="mesh" material="white"/>

        <body name="3BR_Link" pos="0 -0.17 -0.225" euler="1.57 0 -1.57">
             <joint name="3BR_Joint" axis="0 1 0" pos="-0.10 0.0 0.14"/>

            <inertial pos="0 0 0" mass="0.10" diaginertia="0.005 0.005 0.005"/>
            <geom mesh="3BR_calf" type="mesh" euler="0 0 0" pos="0.0 0.0 0.0" material="white"/>

	<actuator>
		<position name="Right Calf 3BR" joint="3BR_Joint"/>
		<position name="Right Foot 1R" joint="1R_Joint"/>

For full source see https://github.com/assadollahi/kayra/blob/main/mujoco/kayraCircle.xml

I've been trying to follow the documentation here: 
https://mujoco.readthedocs.io/en/stable/python.html#named-access

But I can't seem to find an example that really modifies the actuator position of a joint in a body.

Here is a video, illustrating how I can move the joints via the MuJoCo UI:
https://youtube.com/shorts/2vDGm3jJlS8

**Comment by kevinzakka** [comment]
Hi @assadollahi, actuators in MuJoCo are controlled by giving them a control signal.

```python
model = ...
data = ...

# Named access.
data.actuator("Right Calf 3BR").ctrl = 1.57 

# Control all actuators.
data.ctrl[0] = np.random.uniform(-3.14, 3.14, size=(model.nu,))
```
