### ISSUE TITLE
MJX produces NaN values while regular mujoco doesn't.

### ISSUE THREAD

**Issue by Manchewable** [google-deepmind/mujoco#1225]
Hello, I'm playing around with mujoco version 3.0.1 and I have an issue where mjx produces NaN values while the regular version of mujoco doesn't. Currently, I'm just trying to simulate a box dropping onto the ground.

Here's a minimal example that reproduces the issue. If I use the regular mujoco as my backend,
```
MJCF_XML = """
<mujoco model="test">
  <option timestep="0.001" iterations="1" ls_iterations="4">
    <flag eulerdamp="disable"/>
  </option>

  <worldbody>
    <geom name="floor" type="plane" conaffinity="1" size="100 100 .2"/>

    <body name="cart" pos="0 0 0.5">
      <freejoint/>
      <geom name="cart" type="box" size="0.2 0.15 0.1" mass="1"/>
    </body>
  </worldbody>
</mujoco>
"""

if __name__ == "__main__":
    model = mujoco.MjModel.from_xml_string(MJCF_XML)
    data = mujoco.MjData(model)
    mujoco.mj_step(model, data)
    print(data.qpos)
```
This prints out `[0. 0. 0.49999019 1. 0. 0. 0.]`.

Now if I change the code to use mjx as the backend:
```
if __name__ == "__main__":
    model = mujoco.MjModel.from_xml_string(MJCF_XML)
    model = mjx.device_put(model)
    data = mjx.make_data(model)
    data = mjx.step(model, data)
    print(data.qpos)
```
This will print out `[nan nan nan nan nan nan nan]`.

Any insights as to where the problem could be? Thanks!

**Comment by erikfrey** [comment]
Oh good catch - there is indeed a divide by zero bug in the solver when no constraints are imposing any cost.  Will post a fix shortly.
