### ISSUE TITLE
[`MJX`] `data.cfrc_ext` is missing

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [google-deepmind/mujoco#1233]
Hi,

I'm a maintainer of Gymnasium & Gymnasium-Robotics, and I'm trying to use `MuJoCo-MJX` for "prototyping MJX-based RL environments in Gymnasium".

`data` does not seem to have the `cfrc_ext` member variable, is named something else or is it missing? The documentation does not indicate it would be missing https://mujoco.readthedocs.io/en/3.0.1/mjx.html#feature-parity

Here is the model tested: [Gymnasium/Ant](https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/envs/mujoco/assets/ant.xml) (though it should not matter for the question)

Thanks!

**Comment by yuvaltassa** [comment]
This will be added when sensors are implemented (this field is required for force/torque sensors), so it's "mentioned" in Feature Parity because Sensors are in the "Under Development" section.
