### ISSUE TITLE
Understanding wrap_xpos

### ISSUE THREAD

**Issue by mavex857** [google-deepmind/mujoco#1234]
Hi,

I try to use Mujoco for a simple RL task: Two sticks that sit on top each other connected by a hingejoint. I want to balance the upper stick in a certain position with two tendons to pull on the sides. The tendons start at the lower stick, wrap around the joint and end at the upper stick.
I am trying to calculate the "bentness" of the tendons in order to adjust the internal friction in the tendons. To do that, I need to know the position of all sites the tendon passes through. I think I can use `MjData.wrap_xpos` for that, but I don't fully understand what exactly it's showing me. The two tendons are called "left" and "right".
Let's put x as an alias for "left" or "right". tendon_x start at the site "lower_x", wraps around the sphere "tendon_wrap" (with sidesite "sidesite_x"), and finally ends in site "upper_x".
In the XML, I create tendon_left first, then tendon_right. Within that, the sites are specified in the order lower -> tendon_wrap -> upper.

Here is the part of the XML:
```
<worldbody>
        <light pos="0 1 1" dir="0 -1 -1" diffuse="1 1 1"/>
        <body>
            <geom name="lower" type="capsule" fromto="0 0 1 0 0 0.6" size="0.06" rgba=".5 0 0.5 1"/>
            <site name="lower_left" pos="-0.06 0 0.8"></site>
            <site name="lower_right" pos="0.06 0 0.8"></site>
            
            <geom name="tendon_wrap" type="sphere" size="0.06" pos="0 0 1" euler="0 0 0" rgba=".5 0 .5 1"></geom>
            <site name="sidesite_left" pos="-0.063 0 1"></site>
            <site name="sidesite_right" pos="0.063 0 1"></site>
            <body>
                <geom name="upper" type="capsule" fromto="0 0 1  0 0 1.4" size="0.04" rgba=".5 0 0.5 1" mass="0.2"/>
                <site name="upper_left" pos="-0.04 0 1.3"></site>
                <site name="upper_right" pos="0.04 0 1.3"></site>
                <joint name="joint" type="hinge" pos="0 0 1" axis="0 1 0" limited="true" range="-180 180"/>         
            </body>
        </body>
        
    </worldbody>
    <tendon>
        <spatial name="left" rgba="1 0 0 1">
            <site site="lower_left"></site>
            <geom geom="tendon_wrap" sidesite="sidesite_left"></geom>
            <site site="upper_left"></site>
        </spatial>
    
        <spatial name="right" rgba="0 0 1 1">
            <site site="lower_right"></site>
            <geom geom="tendon_wrap" sidesite="sidesite_right"></geom>
            <site site="upper_right"></site>
            </spatial>
    </tendon>
```
The original, initial output for `MjData.wrap_xpos`looks like this:
```
[[-0.06    0.      0.8    -0.06    0.      1.    ]
 [-0.0599  0.      1.004  -0.04    0.      1.3   ]
 [ 0.06    0.      0.8     0.06    0.      1.    ]
 [ 0.0599  0.      1.004   0.04    0.      1.3   ]
 [ 0.      0.      0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.      0.      0.    ]]
```

I assume it is structured like this:

```
[
#tendon_left:
[lower_left_x   lower_left_y   lower_left_z   sidesite_left_x    sidesite_left_y   sidesite_left_z],
[sidesite_left_x    sidesite_left_y   sidesite_left_z   upper_left_x   upper_left_y   upper_left_z],
#tendon_right:
[lower_right_x   lower_right_y   lower_right_z   sidesite_right_x    sidesite_right_y   sidesite_right_z],
[sidesite_right_x    sidesite_right_y   sidesite_right_z   upper_right_x   upper_right_y   upper_right_z],
#don't know what that is:
[0   0   0   0   0   0],
[0   0   0   0   0   0]
]
```
But I am really not sure, since the values don't change as expected when running the simulation.
After some steps of make the stick fall to the right, it looks like this:
```
[[-0.06    0.      0.8    -0.06    0.      1.    ]
 [-0.0335  0.      1.0497  0.2124  0.      1.2156]
 [ 0.06    0.      0.8     0.2615  0.      1.1524]
 [ 0.06    0.      1.0002  0.059   0.      1.2969]
 [ 0.      0.      0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.      0.      0.    ]]
```
Don't look at these specific numbers, but it is clear that my assumption about the structure must be wrong, since values that should therefore be same are not.

Can someone explain how exactly `MjData.wrap_xpos` is structured and how I can utilize it to get the positions of all sites that a tendon passes through?
Thanks!

**Comment by yuvaltassa** [comment]
I don't think your interpretation is wrong. Read [mj_tendon](https://github.com/google-deepmind/mujoco/blob/1885d518ebf80b6fe6c2ba595be06027ce7306da/src/engine/engine_core_smooth.c#L613) and [this block](https://github.com/google-deepmind/mujoco/blob/1885d518ebf80b6fe6c2ba595be06027ce7306da/src/engine/engine_vis_visualize.c#L1756) in engine_vis_visualize.c to gain a better understanding.
