### ISSUE TITLE
Unity complex terrain mesh misbehave

### ISSUE THREAD

**Issue by Norite-dev** [google-deepmind/mujoco#1236]
Hi guys,

I'm doing some simulations in Unity+Mujoco and find out,  that for some reason complex terrain meshes misbehave. The MJ body moves away in space, and the object (ball in my case) is rolling on some invisible terrain.
I'll attach video to demonstrate the issue. 

Operating system. Tried on MacOS 14.1.1 and Windows 10
MuJoCo version 3.0.1

Thank you in advance!

https://github.com/google-deepmind/mujoco/assets/81800286/d5f6ec02-38cc-4a0b-a436-4437a953a4a4

**Comment by erez-tom** [comment]
Is your terrain mesh a child of the root gameObject (and therefore a child of worldbody, and therefore static) or is it a child of some MuJoCo body?  If you grab the XML that's exported and load it in the standalone simulate app, does it suffer from the same problem?  If it's fine in simulate, then there may be a bug in synchronizing the transforms between Unity and MuJoCo -- if you can find it, we'd be grateful for a Pull Request!

**Comment by Norite-dev** [comment]
Thanks for quick response.

So, the terrain mesh is a child of an empty object with Mj_body component on it.  
I've just tried to export XML scene and found out that the terrain mesh looks pretty different. It looks like convex mesh around the original one.
![image](https://github.com/google-deepmind/mujoco/assets/81800286/32f20214-4db5-40ce-a3a0-28f92c39a85c)

Here is the original one:
![image](https://github.com/google-deepmind/mujoco/assets/81800286/b4f68ad3-9e56-4581-a0f9-1deaa7bedc4f)

**Comment by Norite-dev** [comment]
The mesh itself procedure-generated in Unity and then added to Mj_geom mesh and meshfilter components.

**Comment by erez-tom** [comment]
By default, MuJoCo will only allow collisions with the convex hull of a mesh.  If you're using the mesh as a terrain, you could consider using [heightfields](https://mujoco.readthedocs.io/en/latest/XMLreference.html#asset-hfield).

**Comment by Balint-H** [comment]
Are heightfields currently supported by the plugin? As far as I can tell no, but I might have missed something. I think we could reopen this issue or a new one to track implementing it. I'm interested at trying to add support for it.

**Comment by Norite-dev** [comment]
It would be awesome. And yes, so far there is no native support of height fields.

**Comment by Balint-H** [comment]
#1253 Now added basic support for heightfields with the Unity plugin. If you give it a go but run into any issues, let me know!
