### ISSUE TITLE
Support for 32 Index format for higher mesh size 

### ISSUE THREAD

**Issue by vidurvij-apptronik** [google-deepmind/mujoco#1244]
**Is your feature request related to a problem? Please describe.**
I am trying to import a mesh for my robot in Unity. It has high number of vertices, When I import the mesh directly in MuJoCo, it works but it seems like there is an issue with MuJoCo's unity plugin. It probably stems from the indexformat used to create new meshes in Unity. When I manually edit the StlParser.cs to remove the check for number of vertices and change the format for mesh to IndexFormat.UInt32, its working for MuJoCo version 3.0.1 but not for 2.3.7. I would love to have this supported natively,

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vidurvij-apptronik** [comment]
https://github.com/google-deepmind/mujoco/pull/1254

**Comment by vidurvij-apptronik** [comment]
Any progress on the pull request?

**Comment by yuvaltassa** [comment]
We can't accept your pull request without the CLA.
Closing the issue, we can continue the discussion in the PR.

**Comment by vidurvij-apptronik** [comment]
Can I repoen the discussion here! So I need to have a 32 bit index to store the meshes, so we can import higher resolution meshes. I am commenting here because I didn't get any reply there,
