### ISSUE TITLE
[MJX] trouble getting correct constraint forces

### ISSUE THREAD

**Issue by WangHanSolo** [google-deepmind/mujoco#1247]
Hi,

I'm a student and I'm trying to use MJX for robot simulations.

I'm looking for some help with getting the getting constraint force, `qfrc_constraint`, in mjx. 
In the attached XML, both mujoco and mjx sims settles to the state in the attached image.

I get the following values for `qfrc_constraint`: 
using mujoco: ` [ 0 0 5 0 0 0 0 0 5 0 0 0]` and using mjx: `[0 0 0 0 0 0 0 0 0 0 0 0]`. (rounded for readability)
Throughout the simulation, mujoco outputs rational values while mjx outputs 0s...

Even with the discrepancy above, the sim visualizations between mjx and mujoco are identical.  `gfrc_constraint` is somewhere in mjx but I need help finding it.

Any pointers is appreciated!

<details>
  <summary>minimal XML</summary>

```XML
<mujoco>
  <asset>
    <texture name="grid" type="2d" builtin="checker" rgb1=".1 .2 .3"
     rgb2=".2 .3 .4" width="300" height="300" mark="none"/>
    <material name="grid" texture="grid" texrepeat="6 6"
     texuniform="true" reflectance=".2"/>
     <material name="wall" rgba='.5 .5 .5 1'/>
  </asset>

  <default>
    <geom type="sphere" size=".05 .05 .05" />
    <joint type="free"/>
  </default>

  <worldbody>
    <light name="light" pos="-.2 0 1"/>
    <geom name="ground" type="plane" size=".5 .5 10" material="grid"/>
    <camera name="cam" pos="-.3 -1.8 .9" xyaxes="1 0 0 0 1 2"/>

    <body pos="0 0 .3">
      <joint/>
      <geom/>
    </body>
    <body pos="0 0 .6">
      <joint/>
      <geom/>
    </body>
  </worldbody>

</mujoco>
```

</details>

Here is a screenshot of the sim state where the above constraint forces were recorded.
![image](https://github.com/google-deepmind/mujoco/assets/43941252/0ab2bdfb-562e-4fb0-970e-8bce205de151)

**Comment by btaba** [comment]
Hi @WangHanSolo , I can't reproduce the error, the `qfrc_constraint` fields seems to match. Here is what I tried:

```python
model = mujoco.MjModel.from_xml_string(xml)
data = mujoco.MjData(model)
for _ in range(2000):
  mujoco.mj_step(model, data)
data.qfrc_constraint
```

and 

```python
mx = mjx.device_put(model)
dx = mjx.make_data(mx)

jit_step = jax.jit(mjx.step)

for _ in range(2000):
  dx = jit_step(mx, dx)
dx.qfrc_constraint
```
