### ISSUE TITLE
how to undrestand the body frame value of mjData ?

### ISSUE THREAD

**Issue by sunnymints** [google-deepmind/mujoco#1248]
**How to ask for help**

First, read our quick guide to
https://mujoco.readthedocs.io/en/stable/APIreference/APItypes.html?highlight=qpos#mjdata
https://colab.research.google.com/github/google-deepmind/mujoco/blob/main/python/tutorial.ipynb#scrollTo=VJz84c97c8Df
[asking good questions](https://github.com/google-deepmind/mujoco#asking-questions).
Below is a template for you to use:

Hi,

I'm a student and I'm trying to use MuJoCo for robot peg-hole task.

I'm looking for some help with  how to undrestand the body frame value of mjData ?
we load a ur5 robot and want to get it's wrist_3_link pose at each time.

`<mujoco model="ur5">
  <option gravity="0 0 0"/>
  <compiler angle="radian" meshdir="/home/jixiancheng/poture_1117/ur_description/meshes/ur5/collision/"/>
  <statistic meansize="0.2" extent="0.4" center="-3.42017e-10 -0.0501512 -1.90133e-10"/>
  <asset>
    <mesh name="fk" file="fk.STL"/>
  </asset>
  <statistic meansize="0.161957" extent="1.0432" center="0.388318 0.0842553 0.0891814"/>
  <asset>
    <mesh name="base" file="base.stl"/>
    <mesh name="shoulder" file="shoulder.stl"/>
    <mesh name="upperarm" file="upperarm.stl"/>
    <mesh name="forearm" file="forearm.stl"/>
    <mesh name="wrist1" file="wrist1.stl"/>
    <mesh name="wrist2" file="wrist2.stl"/>
    <mesh name="wrist3" file="wrist3.stl"/>
    <mesh name="peg20231110" file="peg20231110.STL"/>
  </asset>
  <worldbody>
	<body name="FK_link"  pos = "-0.35  0.02 0.3"  euler="1.5707963267948966 0 0">

      <geom euler="0 0 0" type="mesh" rgba="0.7 0.7 0.7 1" mesh="fk"/>

	
 </body>

    
    <geom quat="0 0 0 1" type="mesh" contype="0" conaffinity="0" group="1" density="0" rgba="0.7 0.7 0.7 1" mesh="base"/>
    <geom quat="0 0 0 1" type="mesh" rgba="0.7 0.7 0.7 1" mesh="base"/>
    <body name="shoulder_link" pos="0 0 0.089159" quat="0 0 0 1">
      <inertial pos="0 0 0" mass="3.7" diaginertia="0.0149724 0.0149724 0.0104063"/>
      <joint name="shoulder_pan_joint" pos="0 0 0" axis="0 0 1" range="-6.28319 6.28319"/>
      <geom quat="0 0 0 1" type="mesh" contype="0" conaffinity="0" group="1" density="0" rgba="0.7 0.7 0.7 1" mesh="shoulder"/>
      <geom quat="0 0 0 1" type="mesh" rgba="0.7 0.7 0.7 1" mesh="shoulder"/>
      <body name="upper_arm_link" quat="0.707107 0.707107 0 0">
        <inertial pos="-0.2125 0 0.136" quat="0.707107 0 0.707107 0" mass="8.393" diaginertia="0.133886 0.133886 0.0151074"/>
        <joint name="shoulder_lift_joint" pos="0 0 0" axis="0 0 1" range="-6.28319 6.28319"/>
        <geom pos="0 0 0.136" quat="0.5 0.5 -0.5 -0.5" type="mesh" contype="0" conaffinity="0" group="1" density="0" rgba="0.7 0.7 0.7 1" mesh="upperarm"/>
        <geom pos="0 0 0.136" quat="0.5 0.5 -0.5 -0.5" type="mesh" rgba="0.7 0.7 0.7 1" mesh="upperarm"/>
        <body name="forearm_link" pos="-0.425 0 0">
          <inertial pos="-0.2125 0 0.0165" quat="0.707107 0 0.707107 0" mass="2.275" diaginertia="0.0312168 0.0312168 0.004095"/>
          <joint name="elbow_joint" pos="0 0 0" axis="0 0 1" range="-3.14159 3.14159"/>
          <geom pos="0 0 0.0165" quat="0.5 0.5 -0.5 -0.5" type="mesh" contype="0" conaffinity="0" group="1" density="0" rgba="0.7 0.7 0.7 1" mesh="forearm"/>
          <geom pos="0 0 0.0165" quat="0.5 0.5 -0.5 -0.5" type="mesh" rgba="0.7 0.7 0.7 1" mesh="forearm"/>
          <body name="wrist_1_link" pos="-0.39225 0 0.10915">
            <inertial pos="0 0 0" quat="0.5 0.5 -0.5 0.5" mass="1.219" diaginertia="0.00342844 0.00262426 0.00262426"/>
            <joint name="wrist_1_joint" pos="0 0 0" axis="0 0 1" range="-6.28319 6.28319"/>
            <geom pos="0 0 -0.093" quat="0.707107 0.707107 0 0" type="mesh" contype="0" conaffinity="0" group="1" density="0" rgba="0.7 0.7 0.7 1" mesh="wrist1"/>
            <geom pos="0 0 -0.093" quat="0.707107 0.707107 0 0" type="mesh" rgba="0.7 0.7 0.7 1" mesh="wrist1"/>
            <body name="wrist_2_link" pos="0 -0.09465 -1.9413e-11" quat="0.707107 0.707107 0 0">
              <inertial pos="0 0 0" quat="0.5 0.5 -0.5 0.5" mass="1.219" diaginertia="0.0021942 0.00178515 0.00178515"/>
              <joint name="wrist_2_joint" pos="0 0 0" axis="0 0 1" range="-6.28319 6.28319"/>
              <geom pos="0 0 -0.095" type="mesh" contype="0" conaffinity="0" group="1" density="0" rgba="0.7 0.7 0.7 1" mesh="wrist2"/>
              <geom pos="0 0 -0.095" type="mesh" rgba="0.7 0.7 0.7 1" mesh="wrist2"/>
              <body name="wrist_3_link" pos="0 0.0823 -1.688e-11" quat="0.707107 -0.707107 0 0">
                <inertial pos="0 0 -0.00627169" quat="0.5 0.5 -0.5 0.5" mass="0.3389" diaginertia="0.000132134 0.00011486 0.00011486"/>
                <joint name="wrist_3_joint" pos="0 0 0" axis="0 0 1" range="-6.28319 6.28319"/>
                <geom pos="0 0 -0.0818" quat="0.707107 0.707107 0 0" type="mesh" contype="0" conaffinity="0" group="1" density="0" rgba="0.7 0.7 0.7 1" mesh="wrist3"/>
                <geom pos="0 0 -0.0823" quat="0.707107 0.707107 0 0" type="mesh" rgba="0.7 0.7 0.7 1" mesh="wrist3"/>
                <geom size="0.005 0.005 0.005" pos="0 0 -0.01" quat="0.5 0.5 -0.5 0.5" type="box"/>
                <geom pos="0 0 0.005" quat="0.5 0.5 -0.5 0.5" type="mesh" contype="0" conaffinity="0" group="1" density="0" rgba="0.7 0.7 0.7 1" mesh="peg20231110"/>
                <geom pos="0 0 0.005" quat="0.5 0.5 -0.5 0.5" type="mesh" rgba="0.7 0.7 0.7 1" mesh="peg20231110"/>
              </body>
            </body>
          </body>
        </body>
      </body>
    </body>
  </worldbody>
</mujoco>`

python code:
`d.qpos[:]=[0.17195291679571792, -1.2151152721500111, -2.042115573329094,
                              -1.4551581329978485, 1.5707963241241731, 0.17195291700664328]
mujoco.mj_forward(m,d)
viewer.sync()
`
we can use `d.xpos[7]` get correct position of `body name="wrist_3_link"` ，but   `d.xquat[7]`and `d.xmat[7]` can not get correct orientation:
  
Two questions:
1.
why at same setp,`d.xquat[7]`and `d.xmat[7]` get different value but the descriptions in the documents are consistent, what posture do they correspond to?

```
documents:
 mjtNum* xquat;             // Cartesian orientation of body frame              (nbody x 4)
  mjtNum* xmat;              // Cartesian orientation of body frame              (nbody x 9)
```
```
d.xquat[7]=[ 1.17520316e-09, -7.07106781e-01, -7.07106781e-01,
        -2.06301274e-09]
```

`R.from_matrix(d.ximat[7].reshape(3,3)).as_quat()=[ 7.07106782e-01,  1.54671852e-09, -7.07106781e-01, -1.69149738e-09]`

2.How to obtain the correct posture of body 8？
the correct posture should be (0.7071067690849304,0.7071067690849304,1.3474062143803422e-11,
 -1.498098645136281e-09) which get from ros and pybullet(The visualization effect of wrist_3_link posture is consistent).

Here is a screenshot / video, illustrating my question:
In the fig ,the red line is orientation of  the body which named "wrist_3_link" in the world frame.

![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=6006974854340824759 skey=@crypt_83af9c32_de7642cc9b2af3161599363e89060b58 mmweb_appid=wx_webfilehelper](https://github.com/google-deepmind/mujoco/assets/83362227/cbfa3bb9-1d0a-42af-968d-8407eaea0cc7)

**Comment by yuvaltassa** [comment]
Closing due to lcl of activity.
