### ISSUE TITLE
Specifying Collision Attributes for Dynamically Added Geometries in MuJoCo via Python

### ISSUE THREAD

**Issue by kankanzheli** [google-deepmind/mujoco#1255]
Dear MuJoCo Team,

I am currently working with MuJoCo and have a question regarding the customization of geometric bodies through Python using **user_scn**. Specifically, I am interested in whether it's possible to **assign collision coefficients to these geometric bodies** similar to how we can specify contype and conaffinity attributes in the XML configuration files.

In the XML setup, we can easily define these attributes for each body or geom to control the collision behaviors. However, when adding geometries dynamically through Python, I am unsure how to assign or modify these collision properties.

Could you please provide guidance on whether such collision attributes can be specified when adding geometries through Python, and if so, how it can be done? This functionality would be extremely useful for dynamically altering the simulation environment based on specific requirements.

Thank you for your assistance and for the continuous development of this powerful simulation tool.

Best regards

**Comment by yuvaltassa** [comment]
No. Visual geoms are purely visual and do not interact with the physics.

If you want to modify collision properties, you have to do it in the XML.
