### ISSUE TITLE
`mj_resetData` difference between setting `qpos` & `qvel` and running `mj_forward`?

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [google-deepmind/mujoco#1257]
code A:
```py
mujoco.mj_resetData(self.model, self.data)
```
code B:
```py
data.qpos = self.model.qpos0
data.qvel = self.init_qvel
data.ctrl = np.zeros(self.model.nu)
```
Is `mj_resetData` the same as setting `data->qpos = model->qpos0` &  `data->qvel = model->qvel0` & `data->ctrl = np.zeros(shape=ctrl.shape)` and the running `mj_forward(qpos, qvel)` once (coda A and B respectively)

If so, what is the purpose of `mj_resetData`, if not so how do does it differ with code above?

Thanks

**Comment by Balint-H** [comment]
There are many other persistent data across frames that is also reset. Mocap positions, actuator activations, etc. `mj_resetData` clears those as well.

Have a quick look at the source:
https://github.com/google-deepmind/mujoco/blob/c062a8db19b645e15cc4522779471e5c89b1581d/src/engine/engine_io.c#L1533
