### ISSUE TITLE
 [MJX] [Feature request] add `nstep` argument to `mjx.step` 

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [google-deepmind/mujoco#1258]
**Is your feature request related to a problem? Please describe.**
When using `mujoco` I can step with:
```py
mujoco.mj_step(self.model, self.data, nstep=n_frames)
```
but `mjx` does not have 
```
self.mjx_data = mjx.step(self.mjx_model, self.mjx_data)  # `nstep` argument missing 
```

The MJX tutorial notebook https://colab.research.google.com/github/google-deepmind/mujoco/blob/main/mjx/tutorial.ipynb#scrollTo=ccujYeJ5XOhx achieves the same behavior (effectively `nstep=self._physics_steps_per_control_step`) via this: 
```py
def pipeline_step(
    self, data: mjx.Data, ctrl: jax.Array
) -> mjx.Data:
  """Takes a physics step using the physics pipeline."""
  def f(data, _):
    data = data.replace(ctrl=ctrl)
    return (
        mjx.step(self.sys, data),
        None,
    )
  data, _ = jax.lax.scan(f, data, (), self._physics_steps_per_control_step)
  return data
```
Which has the downside of being really hard to read.

**Describe the solution you'd like**
add `nstep` argument to `mjx.step` which works the same as `mujoco.mj_step(nstep=...)`

**Describe alternatives you've considered**
The alternative would be to not change that in `mjx.step` and have all users who need this feature use the `pipeline_step` function shown above.

**Additional context**
I provide no additional context, be sure to ask if necessary

**Comment by btaba** [comment]
Hi @Kallinteris-Andreas , the nstep was added to the Python API to avoid the cost of doing loops with the GIL, but that isn't really an issue with jax, so we are unlikely to implement this in the MJX API (we want to maintain parity with C MuJoCo). 

Here's a simple implementation:

```python
def step(m: Model, d: Data, nstep: int = 1) -> Data:
  """Advance simulation."""
  d, _ = jax.lax.scan(
      lambda x, _: (mjx.step(m, x), None), init=d, xs=None, length=nstep
  )
  return d
```

**Comment by erikfrey** [comment]
Even simpler you can do:

```python
def step(m: Model, d: Data, nstep: int = 1) -> Data:
  """Advance simulation."""
  step_fn = lambda _, x: mjx.step(m, x)
  return jax.lax.fori_loop(0, nstep, step_fn, d)
```
