### ISSUE TITLE
Flexcomp pins not working with elasticity plugin

### ISSUE THREAD

**Issue by alyhatem** [google-deepmind/mujoco#1260]
Hi,

I'm a student and I'm trying to use MuJoCo for modelling an underwater biomimetic robot.
I'm looking for some help with using flexcomp. I'm using the elasticity plugin like in the sample models. I have two robotic fins that i want to connect using a flexible membrane. I figured out using pins to fix one side of the membrane to a geom. but as soon as i try to use the elasticity plugin, it doesnt work. I'm just editing one of the sample models provided.

Here is a model which explains my question:

<mujoco model="Flag">

  <statistic center=".4 0 .8" extent="1.3"/>

  <option wind="0 0 0" density="10" solver="CG" tolerance="1e-6">
  </option>

  <extension>
    <plugin plugin="mujoco.elasticity.membrane"/>
  </extension>

  <worldbody>
    <geom name="floor" type="plane" size="0 0 .1"/>
    <light diffuse=".6 .6 .6" specular="0.2 0.2 0.2" pos="0 0 4" dir="0 0 -1"/>
    <body name="box" pos="-0.1 0.45 1.5">
      <geom type="box" size="0.1 0.45 0.01"/>
      <joint name="JK1" axis="0 1 0" pos="-0.1 0 0" limited="false"/>
      <body name="pin" pos="0.3 0 0">
      <flexcomp type="grid" count="9 19 1" spacing=".05 .05 .05" mass="10"
                name="flag" radius="0.001">
        <edge equality="true" damping="0.001"/>
        <pin range="0 18"/>
        <plugin plugin="mujoco.elasticity.membrane">
          <config key="poisson" value="0.1"/>
          <config key="thickness" value="1e-2"/>
          
          <config key="young" value="3e6"/>
        </plugin>
      </flexcomp>
    </body>
    </body>

  </worldbody>

  <actuator>
    <position name="1" joint="JK1" kp="1000" ctrllimited="true" ctrlrange="-3.14 3.14"/>
  </actuator>

</mujoco>

Here is a video of what i want to do, this is without using the plugin

https://github.com/google-deepmind/mujoco/assets/153009749/238b83de-14e8-4bdd-8352-08ff746a2f1a

when i try to use the plugin it says: This body does not have the requested plugin instance, or sometimes its just unstable and doesnt work, depends on howe many vertices i have pinned

**Comment by yuvaltassa** [comment]
Try using latest MuJoCo (built from source), @quagla recently submitted a fix for this 7d8d4d398ee2d704edbfc07bd9ab67e458a2c77c

(Or wait for the next release)
