### ISSUE TITLE
mediapy seems not to work outside of jupyter?

### ISSUE THREAD

**Issue by assadollahi** [google-deepmind/mujoco#1261]
Hi,

I'm a engineer and I'm trying to use MuJoCo for my open-source humanoid Kayra.

I'm looking for some help with mediapy / rendering images without the conventional mujoco-viewer, 
as I'm planning to write a viewer that shows not only the robot but also provides an interface to see
the different forces, contact points etc over time as graphs and can listen to the whole keyboard.

I've concatenated two of the examples in the [introductory jupyter notebook](https://colab.research.google.com/github/google-deepmind/mujoco/blob/main/python/tutorial.ipynb) of mujoco to generate
a rendering of the scene as well as the matlibplots. 

(I didn't dare to file a bug report as I suspect that the problem is sitting in front of the screen)

I get the following error:

python3 plots.py
<IPython.core.display.HTML object>
Exception ignored in: <function GLContext.__del__ at 0x7f23419e72e0>
Traceback (most recent call last):
  File "/home/ramin/.local/lib/python3.10/site-packages/mujoco/glfw/__init__.py", line 41, in __del__
  File "/home/ramin/.local/lib/python3.10/site-packages/mujoco/glfw/__init__.py", line 35, in free
TypeError: 'NoneType' object is not callable

Here is a [repository](https://github.com/assadollahi/kayra) which refers to my question, the source code
I gobbled together is [plots.py](https://github.com/assadollahi/kayra/blob/main/mujoco/plots.py) in the mujoco folder.

When commenting out the line
media.show_image(renderer.render())
the script displays the matplotlib stuff.

I'm running on a Mac M2 / Python 3.9 and Ubuntu Linux, Python 3.10.12. Both machines report the same error.

**Comment by kevinzakka** [comment]
Working on a fix.

**Comment by kevinzakka** [comment]
Could you let us know if the latest release fixes your issues?

**Comment by kevinzakka** [comment]
Hi @assadollahi, can you check if the latest release (3.1.0) fixes your issue? We've added a `close` method that you should call to free up resources associated with the renderer object. You can use it as follows:

```python
# Option 1.
renderer = Renderer(...)
# Use renderer.
renderer.close()

# Option 2.
with Renderer(...) as renderer:
# Use renderer.
```

**Comment by kevinzakka** [comment]
Hi @assadollahi, going to close this. Feel free to re-open if you're still running into issues after updating to the latest release.
