### ISSUE TITLE
Why is there no `model->qvel0`

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [google-deepmind/mujoco#1272]
There exists `model->qpos0` which contains the initial position of the model.

But there does not exist `model->qvel0` to denote the initial velocity of the model.

What is the reason? Is it implicitly assumed that the initial value of `qvel` is always 0 (as far as the model is concerned)

Thanks!

**Comment by yuvaltassa** [comment]
Yes, initial velocities are always 0.

You can define a [keyframe](https://mujoco.readthedocs.io/en/latest/XMLreference.html#keyframe) with nonzero velocities and load it with [mj_resetDataKeyframe](https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mj-resetdatakeyframe).
