### ISSUE TITLE
difference between inertia matrix from MuJoCo and libfranka when simulating a frankaemika panda robot arm 

### ISSUE THREAD

**Issue by 304x** [google-deepmind/mujoco#1284]
Hi,

I'm a student and I'm trying to use MuJoCo for simulating a frankaemika panda robot arm.

I'm looking for some help understanding the inertia matrix mjData.qM.

The value of the inertia matrix from the MuJoco simulation (mjData.qM) differs significantly from the inertia matrix provided by the libfranka API (franka::model.mass) for exactly the same joint configuration. Even after being converted to the dense matrix and reshaped to the corresponding size (7 x 7) of the inertia matrix from libfranka using the mj_fullM method. 

What is the reason for this difference or is there something you have to take in account when using mjData.qM that I am missing ?

**Comment by yuvaltassa** [comment]
Sorry, we don't know what is happening inside libfranka. If you have specific questions about MuJoCo's inertia matrix we can answer them.
