### ISSUE TITLE
How to make the humanoid model do certain specific poses without being bothered by the physics

### ISSUE THREAD

**Issue by coder-rakeshpaul** [google-deepmind/mujoco#1287]
Hi

I'm a student trying to figure out how to give the humanoid a specific position. I get it that we can use keyframes in order to give the humanoid a starting initial pose and then physics takes over and the model falls down. 

I actually want to make the humanoid do a few poses (more like an actual movement, like swing the hand or lifting the leg from the ground)

Is this possible to achieve without using Reinforcement learning? I am not bothered about the physics at the moment and just want the humanoid to perform these actions. (There are other steps that I have to do later on in the project which will need the physics hence I am sticking to mujoco and not some other software)

**Comment by yuvaltassa** [comment]
If you have a sequence of poses, say from motion capture, you can just set `mjData.qpos` to those values, call [`mj_kinematics` and `mj_camlight`](https://mujoco.readthedocs.io/en/latest/computation/index.html#forward-dynamics) to propagate joints to Cartesian, and render a video.

If you want to track motion capture data in a physically realistic way, I recommend looking at @hartikainen's motion-capture tracking task in the [MuJoCo MPC project](https://github.com/google-deepmind/mujoco_mpc).
