### ISSUE TITLE
Why is the contact_rate different in a white image and in a plane?

### ISSUE THREAD

**Issue by george-asai** [google-deepmind/mujoco#1289]
Why do ncon values differ between white image and plane world_body?

・white_image
![スクリーンショット 2023-12-21 184046](https://github.com/google-deepmind/mujoco/assets/148616394/6ec7a153-67ec-4096-95d2-a883b24c3e44)

plane
![スクリーンショット 2023-12-21 183819](https://github.com/google-deepmind/mujoco/assets/148616394/f3f1a7cf-3a7f-4e79-966c-109e54089a67)

![スクリーンショット 2023-12-21 182858](https://github.com/google-deepmind/mujoco/assets/148616394/538d425b-a425-460c-81a9-eff33a8c8945)
![スクリーンショット 2023-12-21 182922](https://github.com/google-deepmind/mujoco/assets/148616394/f5bf9ffa-f978-459e-8a7e-021a4320e225)

They look the same, but the value of NCON is different. I would like to know the reason for this.

**Comment by yuvaltassa** [comment]
Umm, they don't look the same?

The configuration is different, so the number of contacts is different.
