### ISSUE TITLE
Computation of the gravitational term in rigid-body dynamics

### ISSUE THREAD

**Issue by kiwi-sherbet** [google-deepmind/mujoco#1290]
Hello,

I'm a graduate student currently working with MuJoCo's internal functions for robot control and its simulation capabilities.

Specifically, I'm looking for some help with computing the gravitational term in rigid-body dynamics. MuJoCo appears to support the calculation of inertia, Coriolis terms, and the Jacobian matrix via mjData. However, I could not find any functions for the gravitational term in generalized coordinates. Could you let me know if there exists a function within MuJoCo to compute this term? If such a function is not available, what alternative methods can I use?

Thank you!

**Comment by yuvaltassa** [comment]
This force is included (summed) in `mjData.qfrc_bias`, together with other bias forces.

If you want it separately, you can compute it manually by multiplying `(0, 0, -m*g)` by the [Cartesian body Jacobian](https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mj-jacbody)
