### ISSUE TITLE
wrong ortientation data of the end_effector (ur5 manipulator) 

### ISSUE THREAD

**Issue by marcos724** [google-deepmind/mujoco#1294]
hello!

i want to simulate a ur5 manipulator in MuJoCo. but i cannot get the correct `**orientation**` of the `end_effector.` 

in the `urdf.` file there is a link called `ee_link`, but in the `xml.` there is not that body/link. 
So, using PyBullet  and the `urdf. ` file;  the position and orientation can be get with some functions. but when use MuJoCo there is NOT such as body called `ee_link` and i dont know which body take as an `ee_link.` 
i have tried:
- in the `xml.` add a `site` in the `<body  wrist_3_link/>` as a end_effector. and , use the `data.site_xmat` function but i get the orientation data of the `wrist_3_link`.
- in the `xml.` i have create a body taking the `wrist_3_link `as a parent. and, use the `data.xmat `function but i kept getting orientation data  of the `wrist_3_link`.    
- in the `xml.` add a `site` in the body created, but still getting the orientation data of the `wrist_3_link.` 

i wonder if there is another way to get the `ee_link `orientation `data.`  

regards!

**Comment by yuvaltassa** [comment]
If you want all the URDF links you can turn off [this compiler flag](https://mujoco.readthedocs.io/en/latest/XMLreference.html#compiler-fusestatic) however what you tried should work, in particular option 1 is the recommended thing, I don't know why you would get the wrong orientation.
