### ISSUE TITLE
xml convex 

### ISSUE THREAD

**Issue by marcos724** [google-deepmind/mujoco#1295]
hello!
sorry to keep asking
i am using MuJoCo for a porject (Peg In Hole) . using a manipulator UR5 and F/T.sensor.
 
- i have met a problem with the `convex`.  creating a box with a hole in the center (shown on the picture).   i wonder if there is a way to add/change the `xml.` file.  as when i  hit the `'H'` key to see the convex hulls there **is no hole**.  

- anther question :  reading the `xml reference`,  is the range of friction  (0 to 1)?, if so,  meas that if i donot describe the friction in the `xml.` file, mujoco automatically assume as a 1?

regards!

![1](https://github.com/google-deepmind/mujoco/assets/124645807/9e0d5d23-1c0d-44b9-a5b6-a9d7f78e7991)
![2](https://github.com/google-deepmind/mujoco/assets/124645807/3e744ae3-57e7-4ddd-8a45-700bbe00eb9c)

**Comment by yuvaltassa** [comment]
1. You need to convex-decompose your mesh, using e.g. [CoACD](https://github.com/SarahWeiii/CoACD), or use signed distance functions. There are many past issues asking the same question.

2. Yes.
