### ISSUE TITLE
mujoco blackscreen

### ISSUE THREAD

**Issue by dffsd156** [google-deepmind/mujoco#1297]
I downloaded mujoco 2.1.1 version, compiled it, and pressed simulate,
 but the simulate window appear for 3 seconds and disappears immediately.
 What's the problem?

<details>
  <summary>minimal XML</summary>

```XML
<mujoco>
  <worldbody>
    <light pos=".4 -.4 .3" dir="-2 2 -1.5" diffuse=".6 .6 .6"/>
    <light pos="-.2 -.4 .3" dir="1 2 -1.5" diffuse=".6 .6 .6"/>
    <geom type="plane" size=".5 .5 .01"/>
    <body name="ball" pos="0 0 0.05">
      <freejoint/>
      <geom size=".03"/>
    </body>
    <body name="hammer" pos="-.05 0 0.18">
      <joint axis="0 1 0"/>
      <geom type="capsule" size=".01" fromto="0 0 0 -.15 0 0"/>
      <geom type="box" size=".02 .02 .03" pos="-.15 0 0"/>
    </body>
  </worldbody>
</mujoco>
```

</details>

Here is a screenshot / video, illustrating my question:
![화면 캡처 2023-12-30 234545](https://github.com/google-deepmind/mujoco/assets/155244350/7b81ce97-a9cd-4a47-87cd-ca1752f35c69)

**Comment by yuvaltassa** [comment]
Please give us the details of your hardware and software setup.

**Comment by dffsd156** [comment]
> Please give us the details of your hardware and software setup.

![cpu](https://github.com/google-deepmind/mujoco/assets/155244350/c1c3e80c-a3e0-42ff-afa3-3bf31eec0b48)
![graphic](https://github.com/google-deepmind/mujoco/assets/155244350/2be6abfe-7723-43ec-953b-17dec5567698)
![graphic1](https://github.com/google-deepmind/mujoco/assets/155244350/96a336dd-ee42-4461-8f4b-33648268796b)
![mainboard](https://github.com/google-deepmind/mujoco/assets/155244350/018265a9-71f4-4557-a177-19a4cf3927be)
![메모리](https://github.com/google-deepmind/mujoco/assets/155244350/9581ce9a-618c-4cc3-9c61-56a23ed3907c)

**Comment by yuvaltassa** [comment]
Why are you using version 2.2.1?

Does this issue also happen with the latest version?

**Comment by dffsd156** [comment]
> Why are you using version 2.1.1?
> 
> Does this issue also happen with the latest version?

Yes, I'm using mujoco 2.2.1 and when I download the latest version, only the version appears on the screen and the window disappears right away

**Comment by kevinzakka** [comment]
Closing because stale, please re-open if you are still running into this issue.
