### ISSUE TITLE
Color and texture change for the center of mass sphere

### ISSUE THREAD

**Issue by TenguBoss** [google-deepmind/mujoco#1320]
Hello Colleagues,

I am trying to find a way to change the color of the Center of Mass (CoM) sphere in `simulate` from ivory white to a custom color. Is this possible through an XML parameter? I have tried to find the setting on my own but I haven't been able. 

Update - just found it under `visual/rgba`

```
<visual>
      <rgba com="0.5 0.1 0.1 1"/>   <!-- nice red CoM sphere--> 
</visual>
```

The related question still stands: would it be possible to change the texture of the CoM sphere? For example, I would like to use the alternate black and white quads that are somewhat typical of CoM symbology.

Thank you,

BU

**Comment by yuvaltassa** [comment]
Decorative elements cannot be textured at the moment. You can make a bunch of textured sites and manually move them to where the CoMs are, if you like.
