### ISSUE TITLE
Joystick type joint (2 DoF)

### ISSUE THREAD

**Issue by brn-dev** [google-deepmind/mujoco#1334]
Hi,

I'm a student and I'm trying to use MuJoCo to create an environment for multi-agent reinforcement learning.

I'm trying to create a simple robot that uses joints behaving somewhat akin to joysticks. So basically, a ball joint that has the z-axis (rotational) degree of freedom removed.
What would be the best way to model this? Use two hinge joints perpendicular to each other?

Thanks for the help!

**Comment by quagla** [comment]
Yes.
