### ISSUE TITLE
Rigid connection between a cable end and a geom

### ISSUE THREAD

**Issue by wzx16** [google-deepmind/mujoco#1335]
Hi, I'd like to attach a geom to the end of a cable object. Currently, I'm using `weld` equality to build to the connection. However, since it's a soft connection, when the geom is dragged by the cable with a high speed, I can see the cable end moving far away from the welding point as the attached figure shows, which is not as expected. 

**Static status: closely connected**
![Screenshot from 2024-01-13 13-56-55](https://github.com/google-deepmind/mujoco/assets/28090369/8a3c3e04-56a4-4635-8d45-25f335e41f3a)

**On high speed movement, obvious gap**
![Screenshot from 2024-01-13 13-55-40](https://github.com/google-deepmind/mujoco/assets/28090369/f2540356-cee7-4b42-8cf9-172a1abe7d16)

According to the note in the official document for weld:

> Note that two bodies can also be welded together rigidly, by defining one body as a child of the other body, without any joint elements in the child body 

It seems I can avoid the spring like behavior by doing so. However, I couldn't find a way to modify my mjcf file to achieve that. I was wondering is this even possible for a cable object and a trail object, Like a box.

If that's not doable, could u give me some suggestion on tuning the solref params to avoid the 'softness' as much as possible? Here is my weld code:
` <weld body1="load" body2="RO_AB_last" relpose="{{weld_pos}} 0.707 0 0 -0.707" solref="-1e4 -1e3"/>`

**Comment by louisdehaybe** [comment]
@wzx16 Hi, please can you share your solution with me ?
