### ISSUE TITLE
How to route a Cable in MuJoCo ?

### ISSUE THREAD

**Issue by rishabkr29** [google-deepmind/mujoco#1336]
Hi,

I'm a student and I'm trying to use MuJoCo for thesis.

I'm looking for some help with cable routing. Basically I have seen the routing of tendon and wanted do something related to cable. Earlier I was defining the slider along the attachment point and the cylinder position itself but my slider was coming into the workspace (as I do not want it to come within the workspace) i shifted to this idea. Now I wanted to rout the cable and attach the slider to it and routing via cylinder body. Hope you understand my problem.

Looking forward for your quick  suggestion. 

Here is a screenshot / video, illustrating my question:
![PXL_20240115_064838211.jpg](https://github.com/google-deepmind/mujoco/assets/110694658/980e47c1-e9d5-4ead-9936-3ca96a7a7d3e)

**Comment by rishabkr29** [comment]
basically, I am trying to model cable driven actuator system and with the help of python binding I tried to actuate the manipulator. In this model the slider was leaving the contact and the cable was becoming slack which I don't want. so after checking all the modal parameter. I decided to reconfigure the actuation method. 
```<mujoco>

  <option timestep="0.01" gravity="0 0 -9.81" integrator="Euler" jacobian="dense">
    <flag energy="enable" constraint = "enable" contact="enable" sensornoise="enable"/>   <!--#flag enable and disable different part of simulation pipeline.-->
  </option>

  <!--warmstart is enabled-->

  <compiler autolimits="true"/>   <!--settings are global and apply to entire model-->

  <size  njmax="15000" nconmax="500"  nkey="1"/>     <!--Key frame -->

  <size memory="5M"/> 

  <extension>
      <plugin plugin="mujoco.elasticity.cable"/>
  </extension>

  <default>
    <geom solref="1e-2 5" solimp=".5 .99 1e-3" friction=".1"/>
  </default>

  <visual>
    <rgba haze=".3 .3 .3 1"/>
  </visual>

 <visual>
    <rgba rangefinder="1 1 0.1 0.1"/>
    <map znear=".005" zfar="20"/>
  </visual>

  <asset>
    <hfield name="terrain" ncol="201" nrow="201" size="30 30 5 .1"/>
  </asset>

  <asset>
    <texture type="skybox" builtin="gradient" rgb1="0.6 0.6 0.6" rgb2="0 0 0" width="512" height="512"/>

    <texture name="texplane" type="2d" builtin="checker" rgb1=".25 .25 .25" rgb2=".3 .3 .3" width="512" height="512" mark="cross" markrgb=".8 .8 .8"/>

    <material name="matplane" reflectance="0.3" texture="texplane" texrepeat="1 1" texuniform="true"/>
  </asset>

  <worldbody>

        <light diffuse=".5 .5 .5" pos="0 0 10" dir="0 0 -1" />

        <geom type="plane" size="0.4 0.4 0.05" rgba="1 1 1 1" />

        <geom type="plane" pos="0 0 -1" size="10 10 10" rgba="0.5 0.5 0.5 1" />

        <site name="test" pos="-0.05 -0.05 0.06"  size="0.008" rgba="0.8 .9 0 1" />

        <body name="Extrusion">
            <geom type="box" pos="0 0.4 0"   euler="0 0 0" mass="0.2" size="0.4 0.05 0.05" rgba="0.5 0.5 0.5 1"/>
            <geom type="box" pos="0 -0.4 0"  euler="0 0 0" mass="0.2" size="0.4 0.05 0.05" rgba="0.5 0.5 0.5 1"/>
            <geom type="box" pos="0.4 0 0"   euler="0 0 0" mass="0.2" size="0.05 0.4 0.05" rgba="0.5 0.5 0.5 1"/>
            <geom type="box" pos="-0.4 0 0"  euler="0 0 0" mass="0.2" size="0.05 0.4 0.05" rgba="0.5 0.5 0.5 1"/>
        </body>
<!--
        <body name="Table Leg">
            <geom type="box" pos="0.4 0.4 0" euler="0 0 0" mass="0.2" size="0.05 0.01 0.5" rgba="0.1 0.1 0.1 1"/>
        </body>
-->
        <body name="slider_M1" pos="-0.4 0.15 0.06" euler="0 0 135">
            <inertial pos="0 0 0" quat="0 0 0 1" mass="0.1" diaginertia="0.1 0.1 0.1" />
            <geom type = "box" size=".01 0.01 0.01" rgba="1 1 1 1"/>
            <site name="M1" pos="0 0 0"  size="0.008" rgba="0.8 .9 0 1" />
            <joint type="slide" axis="1 0 0" damping="0.1" armature="0.00001" name="slider_joint1"/>
       </body>

       <body name="slider_M3" pos="-0.4 -0.15 0.06" euler="0 0 -135">
            <inertial pos="0 0 0" quat="0 0 0 1" mass="0.1" diaginertia="0.1 0.1 0.1" />
            <geom type = "box" size=".01 0.01 0.01" rgba="1 1 1 1" />
            <site name="M3" pos="0 0 0"  size="0.008" rgba="0.8 .9 0 1" />
            <joint type="slide" axis="1 0 0" damping="0.1" armature="0.00001"  name="slider_joint3"/>
        </body>

       <body name="slider_M2" pos="-0.4 0.3 0.06" euler="0 0 135">
            <inertial pos="0 0 0" quat="0 0 0 1" mass="0.1" diaginertia="0.1 0.1 0.1" />
            <geom type = "box" size=".01 0.01 0.01" rgba="1 1 1 1" />
            <site name="M2" pos="0 0 0"  size="0.008" rgba="0.8 .9 0 1" />
            <joint type="slide" axis="1 0 0" damping="0.1"  armature="0.00001" name="slider_joint2"/>
       </body>

       <body name="slider_M4" pos="-0.4 -0.3 0.06" euler="0 0 -135">
            <inertial pos="0 0 0" quat="0 0 0 1" mass="0.1" diaginertia="0.1 0.1 0.1" />
            <geom type = "box" size=".01 0.01 0.01" rgba="1 1 1 1" />
            <site name="M4" pos="0 0 0"  size="0.008" rgba="0.8 .9 0 1" />
            <joint type="slide" axis="1 0 0" damping="0.1" armature="0.00001" name="slider_joint4"/>
        </body>
     
        <body name = "Link1" pos="-0.3 0 0.06">
            <geom name="1st Link" type="box" pos="0 0 0" mass="1" size=".1 0.02 0.01" />
            <joint name="1st Revolute Joint" pos="-0.1 0 0" type="hinge" axis="0 0 1" limited="true" range="-120 120" frictionloss = "0.02"  damping=".04" />
            <geom name="1st Revolute Joint" type="cylinder" pos="-0.1 0 0"  size=".02 .01" rgba="0 .9 0 1"  mass="0" group="1" />
            <geom name="offset1" type="box" pos="0 0 0" size=".01 0.05 0.01" />
            <site name="l1" pos="0  0.05 0"  size="0.005" rgba="0.8 .9 0 1" />
            <site name="l2" pos="0 -0.05 0"  size="0.005" rgba="0.8 .9 0 1" />  
            <site name="1st Joint" pos="-0.1 0 0"  size="0.0008" rgba="0.8 .9 0 1" />  


            <body name="DB0" pos="0 0.05 0" euler="0 0 135">
                <composite type = "cable" curve="s 0 0" count="10 1 1"  offset="0 0 0" prefix="D" size="0.1414" initial="ball">
                    <plugin plugin="mujoco.elasticity.cable"/>
                    <joint kind="main" damping="0.5" armature="0.00001"  />
                    <geom type="capsule" size="0.004" rgba=".8 .2 .1 1"/>
                </composite> 
            </body> 
            <body name="CB0" pos="0 -0.05 0" euler="0 0 -135">
                <composite type="cable" count="10 1 1" curve="s 0 0"  offset="0 0 0" prefix="C" size="0.1414" initial="ball" >
                    <plugin plugin="mujoco.elasticity.cable"/>
                    <joint kind="main" damping="0.5" armature="0.00001"  />
                    <geom type="capsule" size="0.004" rgba=".8 .2 .1 1"/>
                </composite>
            </body> 

            <body pos="0.2 0 0">
                <geom name="2nd Link" type="box" pos="0 0 0" mass="1"  size=".1 0.02 .01" rgba="0.9 .9 0 1" />
                <joint name="2nd Revolute Joint" pos="-0.1 0 0" type="hinge" axis="0 0 1" limited="true" range="-120 120" frictionloss = "0.02"  damping="0.04" />
                <site name=" 2nd Joint " pos="-0.1 0 0"  size="0.0008" rgba="0.8 .9 0 1" />  
                <geom name="2nd Revolute Joint" type="cylinder" pos="-0.1 0 0"  size=".02 .01" rgba="0 0 0 1"  mass="0" group="1"/>
                <geom name="offset2" type="box" pos="0 0 0" size=".01 0.05 0.01" />
                <site name="l3" pos="0 0.05 0"  size="0.005" rgba="0 .9 0 1" />
                <site name="l4" pos="0 -0.05 0" size="0.005" rgba="0 .9 0 1" />  
                <site name="EE" pos="0.1 0 0" size="0.01" rgba="0 0 0 1" />  
                
                <body name="EB0" pos="0 0.05 0" euler="0 0 140.19">
                    <composite type="cable" count="30 1 1"  curve="s 0 0" offset="0 0 0" prefix="E"  size="0.3905" initial="ball">
                        <plugin plugin="mujoco.elasticity.cable"/>
                        <joint kind="main" damping="0.5" armature="0.00001"  />
                        <geom type="capsule" size="0.004" rgba=".8 .2 .1 1"/>
                    </composite>
                </body> 
         
                <body name="FB0" pos="0 -0.05 0" euler="0 0 -140.19">
                    <composite type="cable" count="30 1 1" curve="s 0 0"  offset="0 0 0" prefix="F"  size="0.3905" initial="ball" >
                        <plugin plugin="mujoco.elasticity.cable"/>
                        <joint kind="main" damping="0.1" armature="0.00001" />
                        <geom type="capsule" size="0.004 " rgba=".8 .2 .1 1"/>
                    </composite>
                </body> 
        
            </body> 
        </body>
  </worldbody>

    <equality>

https://github.com/google-deepmind/mujoco/assets/110694658/1784fb96-1c15-4e75-bddc-a45cd06c057e




      <connect name="M1_boundary"  body1="DB_last"  body2="slider_M1" active = "true" anchor="0 0 0" /> #acnhor point is specified according to local coordinate of first body 
      <connect name="M3_boundary"  body1="CB_last"  body2="slider_M3" active = "true" anchor="0 0 0" />
      <connect name="M2_boundary"  body1="EB_last"  body2="slider_M2" active = "true" anchor="0 0 0" />
      <connect name="M4_boundary"  body1="FB_last"  body2="slider_M4" active = "true" anchor="0 0 0" />
    </equality>

<!--
    <contact>
      <exclude body1="DB_last"  body2="slider_M1" />
      <exclude body1="CB_first" body2="slider_M3" />
      <exclude body1="EB_last"  body2="slider_M2" />
      <exclude body1="FB_first" body2="slider_M4" />
    </contact>
-->

    <actuator>   
        <position name="x_axis1"     joint="slider_joint1"    ctrlrange="-0.2 0.2"  kp="100"/>
        <position name="x_axis2"     joint="slider_joint2"    ctrlrange="-0.2 0.2"  kp="100"/>  
        <position name="x_axis3"     joint="slider_joint3"    ctrlrange="-0.2 0.2"  kp="100"/>
        <position name="x_axis4"     joint="slider_joint4"    ctrlrange="-0.2 0.2"  kp="100"/> 
        <velocity name="x_dotaxis1"  joint="slider_joint1"    ctrlrange="-0.2 0.2"  kv="10"/>
        <velocity name="x_dotaxis2"  joint="slider_joint2"    ctrlrange="-0.2 0.2"  kv="10"/>
        <velocity name="x_dotaxis3"  joint="slider_joint3"    ctrlrange="-0.2 0.2"  kv="10"/>
        <velocity name="x_dotaxis4"  joint="slider_joint4"    ctrlrange="-0.2 0.2"  kv="10"/>
    </actuator>   

    <sensor>
        <force name="force_in_cable1"   site="l1"/>
        <force name="force_in_cable2"   site="l2"/>
        <force name="force_in_cable3"   site="l3"/>
        <force name="force_in_cable4"   site="l4"/>
        <torque name=" tau_at_1st "     site="1st Joint"/>
    </sensor>

</mujoco>

`

**Comment by rishabkr29** [comment]
> basically, I am trying to model cable driven actuator system and with the help of python binding I tried to actuate the manipulator. In this model the slider was leaving the contact and the cable was becoming slack which I don't want. so after checking all the modal parameter. I decided to reconfigure the actuation method.
> 
> ```
> 
>   <option timestep="0.01" gravity="0 0 -9.81" integrator="Euler" jacobian="dense">
>     <flag energy="enable" constraint = "enable" contact="enable" sensornoise="enable"/>   
>   </option>
> 
>   
> 
>   <compiler autolimits="true"/>   
> 
>   <size  njmax="15000" nconmax="500"  nkey="1"/>     
> 
>   <size memory="5M"/> 
> 
>   <extension>
>       <plugin plugin="mujoco.elasticity.cable"/>
>   </extension>
> 
>   <default>
>     <geom solref="1e-2 5" solimp=".5 .99 1e-3" friction=".1"/>
>   </default>
> 
>   <visual>
>     <rgba haze=".3 .3 .3 1"/>
>   </visual>
> 
>  <visual>
>     <rgba rangefinder="1 1 0.1 0.1"/>
>     <map znear=".005" zfar="20"/>
>   </visual>
> 
>   <asset>
>     <hfield name="terrain" ncol="201" nrow="201" size="30 30 5 .1"/>
>   </asset>
> 
>   <asset>
>     <texture type="skybox" builtin="gradient" rgb1="0.6 0.6 0.6" rgb2="0 0 0" width="512" height="512"/>
> 
>     <texture name="texplane" type="2d" builtin="checker" rgb1=".25 .25 .25" rgb2=".3 .3 .3" width="512" height="512" mark="cross" markrgb=".8 .8 .8"/>
> 
>     <material name="matplane" reflectance="0.3" texture="texplane" texrepeat="1 1" texuniform="true"/>
>   </asset>
> 
>   <worldbody>
> 
>         <light diffuse=".5 .5 .5" pos="0 0 10" dir="0 0 -1" />
> 
>         <geom type="plane" size="0.4 0.4 0.05" rgba="1 1 1 1" />
> 
>         <geom type="plane" pos="0 0 -1" size="10 10 10" rgba="0.5 0.5 0.5 1" />
> 
>         <site name="test" pos="-0.05 -0.05 0.06"  size="0.008" rgba="0.8 .9 0 1" />
> 
>         <body name="Extrusion">
>             <geom type="box" pos="0 0.4 0"   euler="0 0 0" mass="0.2" size="0.4 0.05 0.05" rgba="0.5 0.5 0.5 1"/>
>             <geom type="box" pos="0 -0.4 0"  euler="0 0 0" mass="0.2" size="0.4 0.05 0.05" rgba="0.5 0.5 0.5 1"/>
>             <geom type="box" pos="0.4 0 0"   euler="0 0 0" mass="0.2" size="0.05 0.4 0.05" rgba="0.5 0.5 0.5 1"/>
>             <geom type="box" pos="-0.4 0 0"  euler="0 0 0" mass="0.2" size="0.05 0.4 0.05" rgba="0.5 0.5 0.5 1"/>
>         </body>
> 
>         <body name="slider_M1" pos="-0.4 0.15 0.06" euler="0 0 135">
>             <inertial pos="0 0 0" quat="0 0 0 1" mass="0.1" diaginertia="0.1 0.1 0.1" />
>             <geom type = "box" size=".01 0.01 0.01" rgba="1 1 1 1"/>
>             <site name="M1" pos="0 0 0"  size="0.008" rgba="0.8 .9 0 1" />
>             <joint type="slide" axis="1 0 0" damping="0.1" armature="0.00001" name="slider_joint1"/>
>        </body>
> 
>        <body name="slider_M3" pos="-0.4 -0.15 0.06" euler="0 0 -135">
>             <inertial pos="0 0 0" quat="0 0 0 1" mass="0.1" diaginertia="0.1 0.1 0.1" />
>             <geom type = "box" size=".01 0.01 0.01" rgba="1 1 1 1" />
>             <site name="M3" pos="0 0 0"  size="0.008" rgba="0.8 .9 0 1" />
>             <joint type="slide" axis="1 0 0" damping="0.1" armature="0.00001"  name="slider_joint3"/>
>         </body>
> 
>        <body name="slider_M2" pos="-0.4 0.3 0.06" euler="0 0 135">
>             <inertial pos="0 0 0" quat="0 0 0 1" mass="0.1" diaginertia="0.1 0.1 0.1" />
>             <geom type = "box" size=".01 0.01 0.01" rgba="1 1 1 1" />
>             <site name="M2" pos="0 0 0"  size="0.008" rgba="0.8 .9 0 1" />
>             <joint type="slide" axis="1 0 0" damping="0.1"  armature="0.00001" name="slider_joint2"/>
>        </body>
> 
>        <body name="slider_M4" pos="-0.4 -0.3 0.06" euler="0 0 -135">
>             <inertial pos="0 0 0" quat="0 0 0 1" mass="0.1" diaginertia="0.1 0.1 0.1" />
>             <geom type = "box" size=".01 0.01 0.01" rgba="1 1 1 1" />
>             <site name="M4" pos="0 0 0"  size="0.008" rgba="0.8 .9 0 1" />
>             <joint type="slide" axis="1 0 0" damping="0.1" armature="0.00001" name="slider_joint4"/>
>         </body>
>      
>         <body name = "Link1" pos="-0.3 0 0.06">
>             <geom name="1st Link" type="box" pos="0 0 0" mass="1" size=".1 0.02 0.01" />
>             <joint name="1st Revolute Joint" pos="-0.1 0 0" type="hinge" axis="0 0 1" limited="true" range="-120 120" frictionloss = "0.02"  damping=".04" />
>             <geom name="1st Revolute Joint" type="cylinder" pos="-0.1 0 0"  size=".02 .01" rgba="0 .9 0 1"  mass="0" group="1" />
>             <geom name="offset1" type="box" pos="0 0 0" size=".01 0.05 0.01" />
>             <site name="l1" pos="0  0.05 0"  size="0.005" rgba="0.8 .9 0 1" />
>             <site name="l2" pos="0 -0.05 0"  size="0.005" rgba="0.8 .9 0 1" />  
>             <site name="1st Joint" pos="-0.1 0 0"  size="0.0008" rgba="0.8 .9 0 1" />  
> 
> 
>             <body name="DB0" pos="0 0.05 0" euler="0 0 135">
>                 <composite type = "cable" curve="s 0 0" count="10 1 1"  offset="0 0 0" prefix="D" size="0.1414" initial="ball">
>                     <plugin plugin="mujoco.elasticity.cable"/>
>                     <joint kind="main" damping="0.5" armature="0.00001"  />
>                     <geom type="capsule" size="0.004" rgba=".8 .2 .1 1"/>
>                 </composite> 
>             </body> 
>             <body name="CB0" pos="0 -0.05 0" euler="0 0 -135">
>                 <composite type="cable" count="10 1 1" curve="s 0 0"  offset="0 0 0" prefix="C" size="0.1414" initial="ball" >
>                     <plugin plugin="mujoco.elasticity.cable"/>
>                     <joint kind="main" damping="0.5" armature="0.00001"  />
>                     <geom type="capsule" size="0.004" rgba=".8 .2 .1 1"/>
>                 </composite>
>             </body> 
> 
>             <body pos="0.2 0 0">
>                 <geom name="2nd Link" type="box" pos="0 0 0" mass="1"  size=".1 0.02 .01" rgba="0.9 .9 0 1" />
>                 <joint name="2nd Revolute Joint" pos="-0.1 0 0" type="hinge" axis="0 0 1" limited="true" range="-120 120" frictionloss = "0.02"  damping="0.04" />
>                 <site name=" 2nd Joint " pos="-0.1 0 0"  size="0.0008" rgba="0.8 .9 0 1" />  
>                 <geom name="2nd Revolute Joint" type="cylinder" pos="-0.1 0 0"  size=".02 .01" rgba="0 0 0 1"  mass="0" group="1"/>
>                 <geom name="offset2" type="box" pos="0 0 0" size=".01 0.05 0.01" />
>                 <site name="l3" pos="0 0.05 0"  size="0.005" rgba="0 .9 0 1" />
>                 <site name="l4" pos="0 -0.05 0" size="0.005" rgba="0 .9 0 1" />  
>                 <site name="EE" pos="0.1 0 0" size="0.01" rgba="0 0 0 1" />  
>                 
>                 <body name="EB0" pos="0 0.05 0" euler="0 0 140.19">
>                     <composite type="cable" count="30 1 1"  curve="s 0 0" offset="0 0 0" prefix="E"  size="0.3905" initial="ball">
>                         <plugin plugin="mujoco.elasticity.cable"/>
>                         <joint kind="main" damping="0.5" armature="0.00001"  />
>                         <geom type="capsule" size="0.004" rgba=".8 .2 .1 1"/>
>                     </composite>
>                 </body> 
>          
>                 <body name="FB0" pos="0 -0.05 0" euler="0 0 -140.19">
>                     <composite type="cable" count="30 1 1" curve="s 0 0"  offset="0 0 0" prefix="F"  size="0.3905" initial="ball" >
>                         <plugin plugin="mujoco.elasticity.cable"/>
>                         <joint kind="main" damping="0.1" armature="0.00001" />
>                         <geom type="capsule" size="0.004 " rgba=".8 .2 .1 1"/>
>                     </composite>
>                 </body> 
>         
>             </body> 
>         </body>
>   </worldbody>
> 
>     <equality>
>       <connect name="M1_boundary"  body1="DB_last"  body2="slider_M1" active = "true" anchor="0 0 0" /> #acnhor point is specified according to local coordinate of first body 
>       <connect name="M3_boundary"  body1="CB_last"  body2="slider_M3" active = "true" anchor="0 0 0" />
>       <connect name="M2_boundary"  body1="EB_last"  body2="slider_M2" active = "true" anchor="0 0 0" />
>       <connect name="M4_boundary"  body1="FB_last"  body2="slider_M4" active = "true" anchor="0 0 0" />
>     </equality>
> 
> 
> 
>     <actuator>   
>         <position name="x_axis1"     joint="slider_joint1"    ctrlrange="-0.2 0.2"  kp="100"/>
>         <position name="x_axis2"     joint="slider_joint2"    ctrlrange="-0.2 0.2"  kp="100"/>  
>         <position name="x_axis3"     joint="slider_joint3"    ctrlrange="-0.2 0.2"  kp="100"/>
>         <position name="x_axis4"     joint="slider_joint4"    ctrlrange="-0.2 0.2"  kp="100"/> 
>         <velocity name="x_dotaxis1"  joint="slider_joint1"    ctrlrange="-0.2 0.2"  kv="10"/>
>         <velocity name="x_dotaxis2"  joint="slider_joint2"    ctrlrange="-0.2 0.2"  kv="10"/>
>         <velocity name="x_dotaxis3"  joint="slider_joint3"    ctrlrange="-0.2 0.2"  kv="10"/>
>         <velocity name="x_dotaxis4"  joint="slider_joint4"    ctrlrange="-0.2 0.2"  kv="10"/>
>     </actuator>   
> 
>     <sensor>
>         <force name="force_in_cable1"   site="l1"/>
>         <force name="force_in_cable2"   site="l2"/>
>         <force name="force_in_cable3"   site="l3"/>
>         <force name="force_in_cable4"   site="l4"/>
>         <torque name=" tau_at_1st "     site="1st Joint"/>
>     </sensor>
> 
> </mujoco>
> 
> `
> ```


https://github.com/google-deepmind/mujoco/assets/110694658/5e4ad4a4-19c5-45ac-95e7-7170b7bbb278

**Comment by quagla** [comment]
Thanks for the file and the video! 

If you don't want the cable to become slack, then you don't want to use the cable but the tendon, so I have to ask again why is the tendon not working for you? Is it because you don't want the tendon to stretch?

**Comment by rishabkr29** [comment]
> Thanks for the file and the video!
> 
> If you don't want the cable to become slack, then you don't want to use the cable but the tendon, so I have to ask again why is the tendon not working for you? Is it because you don't want the tendon to stretch?

Thanks for your quick response, From biomechanics perspective tendons are meant to be actuated by the muscles. I am not sure weather I can model the tendons as cable and actuate it with the slider or winch. If you share your thoughts it will be of great help. 

Looking forward of your quick response, I hope what I wanted to achieve out of it.

**Comment by quagla** [comment]
> Yes It should be inextensible and should behave like a rigid body.

I don't understand how the two requirements are possible. If it's inextensible it must become slack.
