### ISSUE TITLE
Can we measure the cable tension in MuJoCo ?

### ISSUE THREAD

**Issue by rishabkr29** [google-deepmind/mujoco#1339]
Hi,

I'm a student  and I'm trying to use MuJoCo for my thesis work.

I'm looking for some help with sensor, I am curious to calculate the tension in cable. Is there any way to measure the cable tension ?

**Comment by quagla** [comment]
I would suggest using a force sensor https://mujoco.readthedocs.io/en/latest/XMLreference.html#sensor-force attached to any body that forms the cable.
