### ISSUE TITLE
AttributeError: 'MjModel' object has no attribute 'actuator_actadr'

### ISSUE THREAD

**Issue by irvingZ11** [google-deepmind/mujoco#1340]
describe the bug:
AttributeError: 'MjModel' object has no attribute 'actuator_actadr'
and i did not find the attribute in my mujoco
my env is ubuntu2004 on wsl2, mujoco2.2.0

**Comment by joek5555** [comment]
Are you using the dm_control package? If so, please check the version to see if it is compatible with mujoco 2.2.0. [This link](https://github.com/google-deepmind/dm_control/releases) shows the different releases of dm_control and what version of mujoco they require. You might also need to update mujoco.

**Comment by irvingZ11** [comment]
> Are you using the dm_control package? If so, please check the version to see if it is compatible with mujoco 2.2.0. [This link](https://github.com/google-deepmind/dm_control/releases) shows the different releases of dm_control and what version of mujoco they require. You might also need to update mujoco.

thanks! I update mujoco and it works
