### ISSUE TITLE
How to build an accurate 3D model for MuJoCo?

### ISSUE THREAD

**Issue by zichunxx** [google-deepmind/mujoco#1352]
Hi! I want to import my `CAD` models from `SolidWorks` to `MuJoCo` and keep the kinematics tree structure. So, I first convert my models to `urdf` with `.stl` meshes and then convert the `urdf` file to the `.xml` file with the `MuJoCo` binary program. 

All went well with the above process, but I found that the model wasn't accurate enough that the hollow area couldn't be passed through. Here is the image to illustrate this phenomenon:

[![enter image description here][1]][1]

As shown in this image, the arm should pass through the annulus model but collision contact was triggered. It seems that the annulus is modeled as a whole piece without the hollow area. 

I have tried to use the [obj2mjcf][2] lib including [V-HACD][3] to refine the model with a higher resolution and more convex hulls. Before that, the `.obj` model is converted from `.STL` file with `Blender`. Besides, the `margin` of this `geom` is set to `0.001`. Unfortunately, none of these methods worked. 

How can I fix this? Thanks!

  [1]: https://i.stack.imgur.com/fKvyp.png
  [2]: https://github.com/kevinzakka/obj2mjcf
  [3]: https://github.com/kmammou/v-hacd

**Comment by yuvaltassa** [comment]
We don't recommend V-HACD, it is very old and suffers from multiple issues. See updated recommendation [here](https://mujoco.readthedocs.io/en/latest/computation/index.html#checking), the [recent](https://arxiv.org/abs/2205.02961) tool by @SarahWeiii et al. is [significantly better](https://colin97.github.io/CoACD/).
