### ISSUE TITLE
Request for Guidance on Integrating Control Buttons in MuJoCo Simulation

### ISSUE THREAD

**Issue by caulron** [google-deepmind/mujoco#1363]
Hello Developers,

I am currently working on a project involving a quadruped robot simulation using the MuJoCo environment. My goal is to enhance the simulation's interactivity by adding control buttons directly into the simulation window. These buttons are intended to provide functionalities like stopping and restarting the simulation without the need to close and reopen the window. I am using C++ for the simulation scripting. Any related documentation or threads that could be helpful are much appreciated.

Objective:
I am seeking to implement the following functionalities:

    Stop Button: To pause the ongoing simulation.
    Restart Button: To reset the simulation to its initial state without closing the window.

Challenges Encountered:

MuJoCo does not seem to have native support for integrating GUI elements like buttons directly into its simulation window. I am uncertain about the best approach to implement this functionality while ensuring compatibility with MuJoCo's API and simulation handling.

Questions:

1. Are there any existing solutions or recommended practices for integrating UI elements into a MuJoCo simulation environment?
2. What frameworks or tools would you suggest for creating a custom UI overlay or a separate window with control buttons for the simulation?
3. Could you provide any examples or documentation that might assist in implementing this feature?
4. Are there any specific considerations or pitfalls I should be aware of when integrating a custom UI with MuJoCo?

Thank you for your time and assistance. Any insights or guidance you could provide on this matter would be immensely valuable.

**Comment by caulron** [comment]
Yes sir, I am using C++.

**Comment by caulron** [comment]
Let me state again what I am aiming for. When I run the simulation, I need a restart button to go to the initial state, as in many games. This way, we shouldn't have to constantly close and reopen the Simulation Window. 

Is there any way to do this? Has anyone ever needed something like this before?

**Comment by yuvaltassa** [comment]
The backspace key does this as does the reset button (or the load keyframe slider, if that's what you want).

Are you using [simulate](https://mujoco.readthedocs.io/en/latest/programming/samples.html#sasimulate)?

This is a code sample that shows you exactly how to do what you want.

**Comment by caulron** [comment]
We are not using simulate. We were using Simulation.cpp file that we coded. 

However, I will examine the link about (simulate) and see if I can implement it into our Simulation code. 

Thanks! :)
