### ISSUE TITLE
Running the MJX tutorial notebook in Colab on a TPU

### ISSUE THREAD

**Issue by goncalog** [google-deepmind/mujoco#1385]
Hi,

I'm a hobbyist and just starting to use MuJoCo. I'm currently trying to run your MJX tutorial on a TPU in Colab. How can I do it? I'm able to select the TPU runtime but get an error on `if subprocess.run('nvidia-smi').returncode:`.

Thank you!

**Comment by btaba** [comment]
Hi @goncalog , as per the notebook "A Colab runtime with GPU acceleration is required". To run the colab with a TPU instance, you'll need to use a Cloud TPU VM (as per https://stackoverflow.com/a/75734517), and so it's just easier to run the colab with a GPU instance. Hope that helps!
