### ISSUE TITLE
[MJX] efc_pos missing in mjx.Data

### ISSUE THREAD

**Issue by EnricoMingo** [google-deepmind/mujoco#1388]
Would it be possible to expose the ```efc_pos``` in ```mjx.Data``` as it is normally exposed in ```mjData```?
This is a convenient way to check the position error in the constraints, are there other ways in mjx?

Thank you!

**Comment by erikfrey** [comment]
Hi @EnricoMingo - this is a reasonable request, I'll look into exposing `efc_pos` in our next release.

**Comment by EnricoMingo** [comment]
Thankyou!
