### ISSUE TITLE
support for visual/⁠global/lookat

### ISSUE THREAD

**Issue by vikashplus** [google-deepmind/mujoco#1407]
**Is your feature request related to a problem? Please describe.**
Better specification of default camera to control the opening view of a model. Currently, we only support `visual/⁠global/azimuth` and `visual/⁠global/elevation`

**Describe the solution you'd like**
support `visual/⁠global/lookat`

**Additional context**
Say you have a large house scene and you want to control which room should we start in. Or maybe it should be the entrace. This feature will enable this capability.

**Comment by yuvaltassa** [comment]
This is vale controlled by `<statistic center/>`

**Comment by yuvaltassa** [comment]
[Documentation](https://mujoco.readthedocs.io/en/latest/XMLreference.html#statistic-center)

**Comment by vikashplus** [comment]
Exactly what I needed. Thanks @yuvaltassa 

Should we add a line in the doc next to `visual/⁠global/elevation/azimuth`
> The lookat point can be specified using `statistic/ center`
