### ISSUE TITLE
Visualizing custom coordinate frames

### ISSUE THREAD

**Issue by rtkg** [google-deepmind/mujoco#1417]
Hi,

I'm an engineer and I'm trying to use MuJoCo for developing multi-body control schemes of robot manipulators.

I'm looking for some help with visualizing custom coordinate frames (e.g., for displaying an end-effector reference frame or a given SE3 trajectory). I'm using the Python bindings and the interactive viewer in passive mode:

`viewer.launch_passive(model, data)`

I don't see a straightforward way to visualize custom frames (or other geometries for that matter). Am I missing something?

**Comment by yuvaltassa** [comment]
Yes, [you are](https://mujoco.readthedocs.io/en/latest/APIreference/APItypes.html#mjtframe). You probably want to use sites from this. There's a section in the basic [tutorial](https://github.com/google-deepmind/mujoco?tab=readme-ov-file#getting-started) about controlling visualization flags.

I recommend playing with the [simulate](https://mujoco.readthedocs.io/en/latest/programming/samples.html#sasimulate) app a little, even if you work via Python, as its GUI basically exposes all these knobs and is an easy way to understand the available options.
