### ISSUE TITLE
Is mj_jac implemented in mujoco-mjx

### ISSUE THREAD

**Issue by gautica** [google-deepmind/mujoco#1418]
Hi,
It is great to see that mujoco supports GPU with MJX, I would like to ask that if **mj_jac** function is implemented in JAX, I need to obtain Jacobian matrix for the end-effector of robots. If not, is there a way to compute it from current version 3.1.2. Thank you.

**Comment by gautica** [comment]
I see, that a function **jac()** is implemented in support.py, which I think is the same as **mj_jac()**. But it is not imported in __init__.py, so cannot be imported from outside.

**Comment by erikfrey** [comment]
Hi @gautica - perhaps this should be public, I'll look into this.  Thanks for pointing it out.
