### ISSUE TITLE
Python Viewer can't load mjb-s

### ISSUE THREAD

**Issue by vikashplus** [google-deepmind/mujoco#1421]
Steps to reproduce 
1. Start python viewer using `python -m mujoco.viewer`
2. Drag-drop a MJB model (==> fails to load)

What does work  
1. Start a native viewer 
2. Drag-drop a MJB model. 
 
Include the following context:
  - Operating system: Tested it on mac and ubuntu 20.04
  - MuJoCo version. 3.1.2
  - For Python issues, what bindings are you using (i.e `mujoco`, `dm_control`, `mujoco-py`)? mujoco

**Comment by rs545837** [comment]
Hi @vikashplus what error does it show, when it fails to load the model.

**Comment by vikashplus** [comment]
> XML parse error 8:
> Error=XML_ERROR_PARSING_TEXT ErrorID=8(0x8) Line number=1
