### ISSUE TITLE
Use of mj_transitionFD with muscle-actuated models

### ISSUE THREAD

**Issue by andreh1111** [google-deepmind/mujoco#1423]
Hi,

I'm a PhD student and I'm using MuJoCo, [MyoSuite](https://github.com/MyoHub/myosuite) in particular, for my research.

I have some doubts related to the use of `mj_transitionFD` with models having **muscles** as actuators.

Why do the first _2*nv_ rows of _B_ contain only zeros? Should I multiply _B_ by _A_ to get the derivatives of _qpos_ and _qvel_ w.r.t. _ctrl_ since they are a consequence of _act_ (whose derivatives w.r.t. _ctrl_ is correctly present in the last _na_ rows of _B_)?

Thanks a lot for your amazing work.

**Comment by yuvaltassa** [comment]
It sounds like you know the answer already? The system is 3rd order so actuators can only affect activations, not positions and velocities directly. This is the reason the first nv rows are 0.
