### ISSUE TITLE
Question about mj_step computation time when model->opt.tolerance = 0.

### ISSUE THREAD

**Issue by DMackRus** [google-deepmind/mujoco#1430]
Hi,

I'm a 3rd year PhD student and I'm trying to use MuJoCo for gradient-based trajectory optimization for contact manipulation in clutter.

The high level element of my questions is, if the model tolerance is set to 0 and the iterations is set to some number, should all calls to the function "mj_step" be roughly equivalent? Or is this too simple an understanding and there is a reason why this would not be the case.

My understanding was that when you set the model->opt.iterations = some number and model->opt.tolerance = 0 the inner optimization algorithm that is used to compute body/joint accelerations should always take the same number of iterations. I was presuming this would mean that calls to mj_step should take **roughly** the same amount of time, irregardless of issues like numbers of contacts (for the same model). Is this assumption true, or is it far too simplistic.

I have a use case where I have written my own finite-differencing function. (I cannot use **mjd_transitionFD** as it does not quite provide me with the utility I need). I remove elements from my state vector automatically when I believe they are not important to the optimization problem (possibly because they are stationary or too far away from the robot end-effector)

I am not reducing my finite-differencing time as much as I would expect ( I halve the number of mj_step calls needed, but I only reduced my finite-differencing time by maybe 20 %). A possible solution to this would be the answer to my overall question. Since the bodies i don't care finite-differencing are not in contact, the time saves i gain by not evaluating them are minimal?

I have not attached my XML as I didn't think its important, but happy to add it if requested.

**Comment by DMackRus** [comment]
Thanks Yuval!

I will certainly checkout that test speed tool you mention as I think it sounds quite informative for me.

I was comparing against my own finite differencing code. I think I must have something strange going on which is resulting in not achieving the time saves i was hoping for, but thank you for clearing up my questions, it at least solidifies that my bug is indeed a bug.

**Comment by EladSharony** [comment]
Hi @DMackRus, I recently released [DiffMjStep](https://github.com/EladSharony/DiffMjStep), which might be what you are looking for.

**Comment by DMackRus** [comment]
Hi, not what I was looking for at the time but this seems very cool and will definitely check it out! Thanks!
