### ISSUE TITLE
How can I implement a rangefinder sensor?

### ISSUE THREAD

**Issue by eleninisioti** [google-deepmind/mujoco#1439]
Hi, 

I am looking for examples of implementing rangefinder sensors. I imagine I can define a sensor as a body in an xml schema, specifying which types of bodies it can detect, and during a simulation get an array that contains distances to bodies within the range of the sensor. Is this possible in mujoco 3?

**Comment by yuvaltassa** [comment]
[Documentation](https://mujoco.readthedocs.io/en/latest/XMLreference.html#sensor-rangefinder), [example](https://github.com/google-deepmind/dm_control/blob/main/dm_control/suite/quadruped.xml#L306).
