### ISSUE TITLE
Force direction detected by sensor

### ISSUE THREAD

**Issue by zichunxx** [google-deepmind/mujoco#1441]
Hi! 

I've been confused about the force direction detected by the force sensor for a while and made a [MWE.zip](https://github.com/google-deepmind/mujoco/files/14392222/MWE.zip) to illustrated my confusion with the [impedance controller](https://github.com/kevinzakka/mjctrl) made by @kevinzakka.

First of all, I found that creating a dummy body is a great way to gather force information from [here](https://github.com/google-deepmind/mujoco/issues/399#issue-1317892443).

Second, as illustrated in the [document](https://mujoco.readthedocs.io/en/stable/XMLreference.html#sensor-force), the detected force is expressed in the site frame and points from the child body to the parent body.

For the above MWE, I create a dummy body containing a sensor site on the tip of the peg and simulate a process of moving vertically downward toward the ground and hitting the ground. **Running the python script in the MWE can reproduce the process directly without any tuning.**

<img src="https://github.com/google-deepmind/mujoco/assets/72594017/c33622f6-bb0f-4448-ba59-b2e99569c8c4" width=50% height=50%>

Here is the force information in the z-direction:
<img src="https://github.com/google-deepmind/mujoco/assets/72594017/1352c8b2-354b-4fd4-af36-a3f397f32985" width=60% height=60%>

For my example, I think the force is negative because the z-axis of the sensor site frame points downward, and the force points from the dummy body to the box_eef body, which is upward. You can also find body labels in the above figure.

1) But why the detected force is positive? 

2) I also found the dummy body should be in the right position but the position of the sensor site does not matter, why?

I have found some related issues but they didn't solve my confusion. Here is the list:

* https://github.com/google-deepmind/mujoco/issues/1249
* https://github.com/google-deepmind/mujoco/issues/399
* https://github.com/google-deepmind/mujoco/issues/997

Thanks in advance for your precious time in checking the MWE. Any comment would be appreciated.

**Comment by kevinzakka** [comment]
Hi @zichunxx, I'm looking into this and will get back to you soon.
