### ISSUE TITLE
Robot going through objects in environment

### ISSUE THREAD

**Issue by santoz007** [google-deepmind/mujoco#1443]
Hi,

I am trying to simulate hybrid force/position control of a manipulator using mujoco py. In between the simulation, the manipulator penetrates through a fixed object in the environment instead of moving over it i.e. no penetration must take place. This is causing my simulation to stop entirely.   

![Issue](https://github.com/google-deepmind/mujoco/assets/45757248/cd4d97b8-3385-4186-a0ee-f039546f6678)

My model file is defined as follows:

![Model](https://github.com/google-deepmind/mujoco/assets/45757248/45423f27-be01-4dce-90de-c92cc33ffc3e)

Any help is highly appreciated.

**Comment by kevinzakka** [comment]
Few recommendations here:

* Increase the thickness of your table.
* Replace the collision geom of the last link of your robot with a primitive like a cylinder or a sphere.
* Reduce your simulation timestep.

**Comment by r-aristov** [comment]
> Few recommendations here:
> 
> * Increase the thickness of your table.
> * Replace the collision geom of the last link of your robot with a primitive like a cylinder or a sphere.
> * Reduce your simulation timestep.

Have similar issue with mujoco-mjx here: [Collisions not working properly in mujoco-mjx with Humanoid model](https://github.com/google-deepmind/mujoco/issues/1468)

Unfortunately none of the suggested things worked.

**Comment by btaba** [comment]
Hi @r-aristov , the issue referenced for Humanoid was closed, Can you please provide a complete example that we can reproduce? I don't really understand what the expected behavior is vs. the behavior you're seeing, do you have a video?

**Comment by r-aristov** [comment]
@btaba Hello!
The issue was resolved, thanks!
It turned out that I missed **conaffinity** parameter and by default collisions were turned on only for feet of Humanoid.
