### ISSUE TITLE
sdf.plugin bolt diameter size calculation

### ISSUE THREAD

**Issue by marcos724** [google-deepmind/mujoco#1459]
Hi,

I'm a student and I'm trying to use MuJoCo for assembly `nut-bolt` with a ur5 manipulator.

I'm looking for some help with the  correct calculation of diameter size of the bolt and the nut, 

how to calculate the `outside diameter` and `inside diameter` of the `bolt`?, 
I would have a `outside diameter=20mm,` but after many attempts, i dont get the correct diameter. instead i get a size `more than 20mm` of diameter. It also happens with the `nut`.  

i wonder if there is a formula  i ignore that helps to calculate  the `exact input diameter.`

regards

**Comment by quagla** [comment]
I would suggest to look at the code https://github.com/google-deepmind/mujoco/blob/main/plugin/sdf/nut.cc#L33 if you need and interactive visualization you can use https://www.shadertoy.com/view/XtffzX which is where I took the initial SDF from.
