### ISSUE TITLE
What is the unit of actuator_force?

### ISSUE THREAD

**Issue by SJH-JunhoSong** [google-deepmind/mujoco#1475]
Hi,

I'm a student and I'm trying to use MuJoCo for control of 7-DOF manipulator .

I'm looking for some help with actuator units.

In simulation, I adapted Joint space PD control (ref: joint position). To achieve it, I set PD gain, but it was far different from actual gain value. (e.g. PD gains in MuJoCo- Kp: 1500, Kd: 60 / Actual PD gain for real plant - Kp: 0.01, Kd: 0.001)

Here is the screenshot of value of mjData, ctrl_input (=mjtNum* ctrl) & actuator_force (=mjtNum* actuator_force) 
ctrllimit: -500~500

![image](https://github.com/google-deepmind/mujoco/assets/149144352/0868be07-0515-413c-919e-82c774b19e6c)

I think I am facing a scaling or unit problem, how can I solve this issue?

Thank you for your help.

**Comment by yuvaltassa** [comment]
Actuator force is always in the natural units of the target (torque units for hinges, force units for sliders).

Assuming your model is MKS, this means Nm and N, respectively.

You should probably read this too https://mujoco.readthedocs.io/en/latest/overview.html#units-are-unspecified
