### ISSUE TITLE
[Off topic question] Origins of the gymnasium/humanoid robot model.

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [google-deepmind/mujoco#1481]
Hi,

I'm a maintainer of [Gymnasium](https://gymnasium.farama.org/) & the project manager of [Gymnasium-Robotics](https://robotics.farama.org/), and I'm trying to use `MuJoCo` for "impoving the documentation of the humanoid model"'.

In gymnasium/mujoco we have the [humanoid](https://gymnasium.farama.org/main/environments/mujoco/humanoid/) environment which consists of a humanoid robot whose goal is to locomote towards the  +x direction as fast as possible.

The robot model used in the gymnasium is different from the model found in the [original paper](https://ieeexplore.ieee.org/document/6386025) though it is based on it.

From what I could tell it mainly differs by missing the toes and halving a couple of tendons connecting the hips to the knees.

Note: I assume this is the [original model](https://github.com/google-deepmind/mujoco/blob/9ac048e262e664b5951678ae5c098d9175862218/model/humanoid/humanoid.xml#L16).

Do you happen to have any insight (or a best guesses) on why the gymnasium's humanoid robot model Is different from the original robot model?

Thanks!
@yuvaltassa @erez-tom

**Comment by yuvaltassa** [comment]
> Note: I assume this is the [original model](https://github.com/google-deepmind/mujoco/blob/9ac048e262e664b5951678ae5c098d9175862218/model/humanoid/humanoid.xml#L16).

Well, our model has changed over time. Perhaps look at the history of this file to see how it has changed (e.g. the tendons are a fairly recent addition).

Why did they remove the feet? No idea, ask them :stuck_out_tongue_closed_eyes:
