### ISSUE TITLE
XML Error: unknown plugin 'mujoco.elasticity.cable'.

### ISSUE THREAD

**Issue by Wangzihao12ous** [google-deepmind/mujoco#1488]
I used follow code to load a model:
#include "mujoco.h"
#include "stdio.h"
#include <GLFW/glfw3.h>
#include <mjplugin.h>
#include <mjvisualize.h>
#include <mjxmacro.h>
#include <mjvisualize.h>
#include <mjmodel.h>
#include <mjui.h>
#include "iostream"
char error[1000];
mjModel* m;
mjData* d;
mjvCamera cam;     // abstract camera
mjvOption opt;     // visualization options    
mjvScene scn;      // abstract scene           
mjrContext con;    // custom GPU context        
GLFWwindow *window;

int main(void)
{
   char error[1000] = "Could not load binary model";
   // load model from file and check for errors
   m = mj_loadXML("../xml/cable.xml", NULL, error, 1000);
   if( !m )
   {
      printf("%s\n", error);
      return 1;
   }
   std::cout<<mj_versionString();
   // make data corresponding to model
   d = mj_makeData(m);

   // run simulation for 10 seconds
   while( d->time<10 )
   {
      mj_step(m, d);
   }

   // free model and data
   mj_deleteData(d);
   mj_deleteModel(m);

   return 0;
}

But erro is XML Error: unknown plugin 'mujoco.elasticity.cable'.
However if I use simluate in the bin folder,it is work,like follow:

(base) wzh@wzhhh:~/mujoko/mujoco-3.1.1/bin$ ./simulate ../../mjcdemo/xml/trynew.xml
MuJoCo version 3.1.1
Plugins registered by library 'libactuator.so':
    mujoco.pid
Plugins registered by library 'libsensor.so':
    mujoco.sensor.touch_grid
Plugins registered by library 'libsdf.so':
    mujoco.sdf.bolt
    mujoco.sdf.bowl
    mujoco.sdf.gear
    mujoco.sdf.nut
    mujoco.sdf.torus
    mujoco.sdf.sdflib
Plugins registered by library 'libelasticity.so':
    mujoco.elasticity.cable
    mujoco.elasticity.membrane
    mujoco.elasticity.shell
    mujoco.elasticity.solid

**Comment by Balint-H** [comment]
You have to load a plugin before it can be recognized by the xml loader. Simulate does this as well. See [docs](https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mj-loadpluginlibrary), and how its used in [Simulate](https://github.com/google-deepmind/mujoco/blob/a49f3f63fcd7b932e92c671d98a4e8ac15b86a21/simulate/main.cc#L191).

**Comment by traversaro** [comment]
For a bit more of context on why plugins are not loaded by default in C++, differently from Python: https://github.com/google-deepmind/mujoco/issues/554 .

**Comment by Balint-H** [comment]
To give the user control over what plugins are loaded (e.g. you can make your own custom plugins and load those as well). However to do that you need reference to where the plugins are, and that kind of assumption should not be baked into the engine (but fine for an app like yours or Simulate).

**Comment by Wangzihao12ous** [comment]
> You have to load a plugin before it can be recognized by the xml loader. Simulate does this as well. See [docs](https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mj-loadpluginlibrary), and how its used in [Simulate](https://github.com/google-deepmind/mujoco/blob/a49f3f63fcd7b932e92c671d98a4e8ac15b86a21/simulate/main.cc#L191).

Thank you very much! It works!

**Comment by Wangzihao12ous** [comment]
> For a bit more of context on why plugins are not loaded by default in C++, differently from Python: #554 .

Thank you very much!
