### ISSUE TITLE
Contact problem of STL mesh generated by python.

### ISSUE THREAD

**Issue by JameScottX** [google-deepmind/mujoco#1494]
Hi,

I'm a student and I'm trying to use MuJoCo though learning-based methods to control various robots.
I'm looking for some help about contact probelm when I was trying import a stl mesh as a radonmized terrain. The reason why I am doing this is that MJX is not supported with a height field, for now, I attempted to generate a randomized terrain with some python code. While the import process seems not expected.

Below are some screenshots illustrating my question in detail. Some objects can not fall into the pit or valley.
![994b2548b6646e27b7eca754512d81d](https://github.com/google-deepmind/mujoco/assets/33600719/1615e1ef-8b3b-40d9-a4f7-69b47b5d251d)

Based on what I knew, I checked the wireframe at first, but I did not find something bothered me, just like this:
![8f15989d979c0f91efc4cbe00335c7e](https://github.com/google-deepmind/mujoco/assets/33600719/19450b5d-3dd2-479f-8adb-153ad6159cc1)

Also, I put the terrain mesh into the Meshlab to examine, but it looked fine to me. Here it is.
![a2a67b713a3116d86300c6761df09c0](https://github.com/google-deepmind/mujoco/assets/33600719/f7a52e5e-ea60-408d-87c8-6ae0553f844e)

I would very much appreciate it if someone could give me a hand with this issue.

**Comment by yuvaltassa** [comment]
You need to decompose your mesh into convex parts or compose it from primitives. This terrain looks like it could easily be composed from boxes. Search previous issues, many people have asked this before.
