### ISSUE TITLE
Collision Detection Issue in Pusher-v4 Environment with Mujoco > 2.3.7

### ISSUE THREAD

**Issue by HernandezEduin** [google-deepmind/mujoco#1495]
**Issues with Collisions**
I've been exploring reinforcement learning for a project and decided to utilize the Pusher-v4 environment available through Mujoco and Gymnasium. My approach was informed by examples from CleanRL, aiming to gain a deeper understanding of the coding practices within this domain. However, I encountered a notable issue: the robot, which is expected to learn to push an object towards a goal, instead passes through the object without any collision.

Upon consultation with the community and specific members (@Kallinteris-Andreas), we've pinpointed that this issue arises exclusively with Mujoco versions post 2.3.7. For reference and further investigation, I've detailed this observation at the following [Gymnasium GitHub issue](https://github.com/Farama-Foundation/Gymnasium/issues/950).

I'm looking forward to any insights or solutions to address this collision detection problem.

**Reproducibility**
You can test this behaviour with the following code I modified from clearnrl and trained model:
[cleanrl.zip](https://github.com/google-deepmind/mujoco/files/14555864/cleanrl.zip)

**Mujoco Ver. 2.3.7**

https://github.com/google-deepmind/mujoco/assets/86664284/41bbcac9-08ca-4aab-b28e-5ce66281ec6e

**Mujoco Ver. 3.0.0**

https://github.com/google-deepmind/mujoco/assets/86664284/aa1d5eda-f11c-4180-8144-6e48f907dfe5

**Context**
  - OS: Windows 10  
  - Python: 3.8.18
  - Issues in: MuJoCo version 3.0.0 and up
  - Bindings: 
     - `pytorch`
     - `mujoco == 2.3.7 or 3.0.0`, 
     - `gymnasium == 0.29.1`,
     - `gymnasium[mujoco]`,

**Comment by Kallinteris-Andreas** [comment]
For additional context here is the model: https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/envs/mujoco/assets/pusher.xml
