### ISSUE TITLE
Derivative of joint torque with respect to position

### ISSUE THREAD

**Issue by mavex857** [google-deepmind/mujoco#1506]
Hi,

I'm a student and write my thesis about variable stiffness control and would like to compute the rotational joint stiffness.
In the literature that can be defined as the derivative of joint torque with respect to joint angle. 
Is it possible to derive these two things from mujoco? Derivative of angle would be ```derivative of qpos = qvel``` but I cannot find a way to obtain the derivative of the torque. 
To compute the torque on the joint in the first place I use ```tq = data.qfrc_smooth + data.qfrc_constraint```.
Right now I just save the value of this from the previous timestep, take the difference with current timestep and divide by ```model.opt.timestep```. However I am pretty sure that that's not giving correct values. Or does it?

Thanks for pointing me to the right direction.

**Comment by yuvaltassa** [comment]
If the force is $f$, the angle is $q$, and the setpoint is $q_0$, simple stiffness $k$ means $f(q) = k * (q - q0)$ and implies that $k = \frac{\partial f}{\partial q}$. 

In MuJoCo these are given by `mjData.actuator_force`, `mjData.qpos`, `mjModel.qpos_spring` and `mjModel.jnt_stiffness`.
