### ISSUE TITLE
How to calculate the xpos from the pos

### ISSUE THREAD

**Issue by coder-rakeshpaul** [google-deepmind/mujoco#1507]
Hi,

I am a student and trying to figure out how to calculate the xpos given the pos. From this [stackoverflow post
](https://stackoverflow.com/questions/73296464/mujoco-what-is-the-difference-between-pos-qpos-and-xpos). I infer that the the xpos is the position in the global frame and the pos is the position wrt to the parent.

I am using the xml as the [humanoid_cmu ](https://github.com/google-deepmind/dm_control/blob/main/dm_control/suite/humanoid_CMU.xml)from dm_control. 

I calculate the xpos as 

`xpos =  pos_body + pos_parentBody + pos_parentBody_parent +....`

which doesn't give correct values

this is a snippet of the xml
![image](https://github.com/google-deepmind/mujoco/assets/114281050/9b01bfb9-acef-4d57-adc6-b90012c20a8b)

just looking at this we can say that the xpos calculated by my method on 

`lfemur would be = pos[world] + pos[root] + pos[lhipjoint] + pos[lfemur] = [0.102, -0.092,  1.05]`

`but the xpos which I get from mujoco with data.body(3).xpos is [0.102 -0.05   0.908]`

What is the cause of this? I think that the relation of between pos and xpos might have been misunderstood by me so want to clarify how this actually works.

Thank you.

**Comment by quagla** [comment]
Hi, it's a full frame transformation not just a sum of positions, i.e. there is also a rotation between frames. Have a look at

https://github.com/google-deepmind/mujoco/blob/main/src/engine/engine_support.c#L1812

Hope it helps :)
