### ISSUE TITLE
Sensors in MuJoCo XLA?

### ISSUE THREAD

**Issue by eleninisioti** [google-deepmind/mujoco#1513]
I see in the documentation of MuJoCO XLA (https://mujoco.readthedocs.io/en/stable/mjx.html) that sensors are under development, any chance this feature has been added? If so, are there any examples?

**Comment by breakds** [comment]
At this moment, I just implement them with jax functions following the logic implemented in c++: https://github.com/google-deepmind/mujoco/blob/main/src/engine/engine_sensor.c#L525

**Comment by yuvaltassa** [comment]
Does anyone want to send us a PR implementing this in the MJX codebase? That would be welcome.

**Comment by breakds** [comment]
> Does anyone want to send us a PR implementing this in the MJX codebase? That would be welcome.

Never contributed to MuJoCo before, but I would like to give it a try if no one is currently working on it.

**Comment by kevinzakka** [comment]
Sensors will be part of the next MJX release.
