### ISSUE TITLE
Tracking camera giving error

### ISSUE THREAD

**Issue by karthyyy** [google-deepmind/mujoco#1528]
Hi,

  I am trying to render a model using MuJoCo python binding, viewing from a custom camera setup. I have gone through the colab tutorial where a tracking camera is implemented using a free camera with camera properties varying with each simulation setup. I tried the same for my setup but it renders like the stationary object appears to move towards the moving object with which the camera is defined.

   My simplified setup has a box moving towards a stationary sphere at a prescribed velocity. Sphere is not placed at the center of viewport.

   I need to generate camera view from the top of box and behind it (so that box is also seen in the camera output). As box moves, the camera should also move but its pointing direction should not change. I believe this is done with "tracking" mode of the camera. Please correct if wrong. So I have coded as follows.

```
<mujoco>
.......................
  <worldbody>
   
 
    # Cube    
    <body name="cube" pos="0 -10 0" >     
      <joint type="free"/>
       .......................
      <camera name="track_cam" pos="-5 -5 5" euler ="0 0 0" mode="track"/>       
    </body>
   
    # Sphere
    <body name="sphere" pos="10 10 0" >   
    .......................     
    </body>
   
    </worldbody>   

</mujoco>
```
 
 
The python code snippet is as follows
 
```
# Initialization
.......................
camera_id = mj.mj_name2id(model, mj.mjtObj.mjOBJ_CAMERA, 'track_cam')
tracking_camera = mj.MjvCamera()
tracking_camera.type = mj.mjtCamera.mjCAMERA_TRACKING
tracking_camera.trackbodyid = 1
.......................
 
# Loop Execution
.......................
mj.mjr_setBuffer(mj.mjtFramebuffer.mjFB_WINDOW, context) 
mj.mjv_updateScene(model, data, opt, None, "tracking_camera", mj.mjtCatBit.mjCAT_ALL.value, scene) 
.......................
 
```
The code is throwing errors as follows
 
**_mj.mjv_updateScene(model, data, opt, None, "tracking_camera", mj.mjtCatBit.mjCAT_ALL.value, scene) 
TypeError: mjv_updateScene(): incompatible function arguments. The following argument types are supported:
1. (m: mujoco._structs.MjModel, d: mujoco._structs.MjData, opt: mujoco._structs.MjvOption, pert: Optional[mujoco._structs.MjvPerturb], cam: mujoco._structs.MjvCamera, catmask: int, scn: mujoco._structs.MjvScene) -> None

Invoked with: <mujoco._structs.MjModel object at 0x0000023492B63B30>, <mujoco._structs.MjData object at 0x000002349EFD0BB0>, <MjvOption
.......................

>, None, 'tracking_camera', 7, <mujoco._structs.MjvScene object at 0x000002349F0C3330>_**

Thanks n Regards,
Karthik

**Comment by yuvaltassa** [comment]
I think the error is pretty clear? `mjv_updateScene` wants an `mjvCamera` but you are giving it a string.
