### ISSUE TITLE
Penetration occurs in mujoco simulation

### ISSUE THREAD

**Issue by Nikanbaturu** [google-deepmind/mujoco#1544]
Hi,

I'm a student and I'm trying to use MuJoCo for  peg-in-hole task
When I started simulating, I found that the block would get stuck in the board, and it seemed to be constantly shaking.
The following are the XML files for my block and peg-board

  <summary>minimal XML</summary>

```XML
block XML
<mujocoinclude model="block">
        <body name="peg_block_link" pos="0 -0.3 -0.27" euler="1.5707963 1.5707963 0">
            <joint name="block_joint" type="free" damping="0.0001"></joint>>
            <geom type="mesh" contype="0" conaffinity="0" group="1" mass="0.001" friction="10" rgba="0.078431 0.494117 0.984313 1" mesh="peg_block" />
            <geom type="mesh" rgba="0.078431 0.494117 0.984313 1" mesh="peg_block" />
        </body>>
</mujocoinclude>
--------------------------------
peg-board XML
<mujoco model="peg_board">
        <body name="board_link" pos="0 -0.3 -0.295">
            <geom type="box" size="0.08 0.05 0.005" mass="1000" material="board_mat" />
        </body>>
</mujoco>
```

</details>

Here is a  video, illustrating my question:

https://github.com/google-deepmind/mujoco/assets/69098659/0aa6936e-3da4-4113-a397-a3e8a535ffbe

**Comment by yuvaltassa** [comment]
https://mujoco.readthedocs.io/en/latest/XMLreference.html#option-flag-multiccd
