### ISSUE TITLE
Forward and Inverse dynamics in Mujoco

### ISSUE THREAD

**Issue by FrancescoTrotti** [google-deepmind/mujoco#1547]
Hi,

I'm a Ph.D. candidate and I'm trying to use Mujoco for a project. I am trying to compute the direct and inverse dynamics of 'Halfcheetah-v4' but I am noticing discrepancies between the results of the two functions.
In particular, I initially tried using the function mj_forward(MjModel, MjData) to compute a state (MjData.qpos, MjData.qvel, MjData.qacc) from fixed torques (MjData.ctrl vector of 6x1 values). Subsequently, I re-initialized the system by setting the qpos, qvel, and qacc previously found with mj_forward by hand. However, I cannot return to the starting torques using the function mj_inverse(MjModel, MjData). I have tried reading the variable MjData.qfrc_inverse, but it returns a size vector (9 x 1), which is therefore incompatible in both size and values from the original torques. Then, I also checked the variables MjData.actuator_force and MjData.qfrc_actuator, but I got a vector of (6 x 1) zeros in both cases. How can I solve my problem?

I attach below the code used to compute the inverse from set values of (MjData.qpos, MjData.qvel, MjData.qacc).

```python
    exclude_pos = False
    env = gymn.make('HalfCheetah-v4', reset_noise_scale=0, exclude_current_positions_from_observation=exclude_pos)

    m = mujoco.MjModel.from_xml_path("half_cheetah.xml")
    d = mujoco.MjData(m)
    d.qpos = [0.00186257, -0.00180925, -0.00316014,  0.0070008,   0.01352665,  0.0046701, 0.01961726, -0.00347373, -0.00093322]
    d.qvel = [ 0.18625746, -0.18092484, -0.31601395,  0.7000798,   1.35266484,  0.46700995, 1.96172633, -0.34737323, -0.09332228]
    d.qacc = [ 20.95819344, -20.0586757,  -36.21781914,  73.76085513, 166.22178942, 53.79152057, 228.71097766, -55.9578873,  -13.1199122 ]

    print("Initial pos: ", d.qpos)
    print("Initial vel: ", d.qvel)
    print("Initial qacc: ", d.qacc)
    print("Initial frc for forward: ", d.ctrl)
    print("Initial frc for inverse: ", d.qfrc_inverse)
    print("Initial actuator force tau: ", d.actuator_force)
    print("Initial actuator force: ", d.qfrc_actuator)
    print("--------\n")


    mujoco.mj_inverse(m, d)
   
    print("pos after mj_inverse: ", d.qpos)
    print("vel after mj_inverse: ", d.qvel)
    print("qacc after mj_inverse: ", d.qacc)
    print("frc inverse after mj_inverse (d.qfrc_inverse): ", d.qfrc_inverse)
    print("actuator force tau: ",  d.actuator_force)
    print("actuator force: ", d.qfrc_actuator)
    print("expected output: ", [0.33747295, 0.3996362, 0.18299277, 0.5981481, 0.15231994, 0.07616442])
    print("--------\n")

    # expected output computed with mj_forward
    # d.ctrl = [0.33747295, 0.3996362, 0.18299277, 0.5981481, 0.15231994, 0.07616442]
```

Thanks for your help

**Comment by yuvaltassa** [comment]
The inverse dynamics only takes you back to the forces, it cannot—even in principle—take you back to `ctrl`. Imagine a cheetah flying in the air, defying gravity, this is a legitimate kinematic trajectory, but implies forces on unactuated dofs, right?

If your trajectory happens to be physically consistent with the controls, you want to effectively invert `mj_fwdActuation`. For torque-control actuators this mean pre multiplying by the moment matrix pseudo-inverse. If $f$ is `qfrc_actuator`/`qfrc_inverse`, $u$ is `ctrl` and $M$ is the transpose of `actuator_moment` then
$$f = Mu \quad \rightarrow \quad u = M^\dagger f$$
