### ISSUE TITLE
cannot import customized obj mesh mujoco.viewer due to "inconsistent orientation"

### ISSUE THREAD

**Issue by zcczhang** [google-deepmind/mujoco#1551]
Hi,

I'm trying to use MuJoCo for research, and I want to import mesh files into MuJoCo. However, when I simply use interactive mujoco viewer and drag the XML file into the viewer (with an obj mesh that can be visualized correctly by open3d or trimesh), the error pops up:
```
"Error: faces of mesh ‘xxx' have inconsistent arientatian. Please check the faces containing the vertices X and Y.
Object name = xxx. id = x, line = y"
```

<details>
  <summary>minimal XML</summary>

```XML
<mujoco model="scene">
<default>
<default class="visual">
<geom group="2" type="mesh" contype="0" conaffinity="0"/>
</default>
<default class="collision">
<geom group="3" type="mesh"/>
</default>
</default>
<asset>
<mesh file="scene.obj"/>
</asset>
<worldbody>
<body name="scene">
<geom mesh="scene" class="visual"/>
<geom mesh="scene" class="collision"/>
</body>
</worldbody>
</mujoco>
```

</details>

![image](https://github.com/google-deepmind/mujoco/assets/52727818/ae0e442a-5685-4302-afc2-8e4c15802439)

**Comment by Balint-H** [comment]
Hello, this sounds like an issue with the asset. For physics its important which part of a mesh is supposed to be inside of an object vs outside,  while graphics software can render the inconsistency.  I recommend editing your mesh outside mujoco and retrying.

(e.g. in blender: https://blender.stackexchange.com/questions/12165/how-to-make-all-faces-flip-to-the-right-consistent-direction)
