### ISSUE TITLE
Related to logging of model states in mujoco

### ISSUE THREAD

**Issue by yaswanth1701** [google-deepmind/mujoco#1552]
Hi,

I'm an undergraduate student and I'm currently planning to work on a project for benchmarking physics engines. 

I am interested to know if there is a feature available for logging the model states (eg: position, orientation, velocity, etc) for simulation duration in mujoco. if there is a functionality available, please let me know in which format the log files get stored. 
Thank you

**Comment by yuvaltassa** [comment]
https://mujoco.readthedocs.io/en/latest/computation/index.html#the-state
