### ISSUE TITLE
force sensor with connect

### ISSUE THREAD

**Issue by 2-woo-10** [google-deepmind/mujoco#1554]
**How to ask for help**

First, read our quick guide to
[asking good questions](https://github.com/google-deepmind/mujoco#asking-questions).
Below is a template for you to use:

I'm a student and I'm trying to use MuJoCo for estimation about contact force.
I'm looking for some help.

I'm using a force sensor to measure the force by declaring a gem at the end of the franka panda gripper.
A total of 4 geoms are made on one side of the gripper to measure the force, and after checking the values, a vibrating shape appears, can you explain this?
<details>
<mujoco model="panda">
  <compiler angle="radian" meshdir="assets" autolimits="true"/>
  <option integrator="implicit" timestep="0.001"/>
  <option gravity="0 0 -9.81"/>
  <option>
  <flag multiccd="enable"/>
  </option>
  <default>
    <default class="panda">
      <material specular="0.5" shininess="0.25"/>
      <joint frictionloss="2" damping="1" axis="0 0 1" range="-2.7437 2.7437"/>

      
      <default class="finger">
        <joint axis="0 1 0" type="slide" range="0 0.04"/>
      </default>

      <default class="visual">
        <geom type="mesh" contype="0" conaffinity="0" group="2"/>
      </default>
      <default class="collision">
        <geom type="mesh" group="3"/>
        <default class="fingertip_pad_collision_1">
          <geom type="box" size="0.0085 0.004 0.0085" pos="0 0.0055 0.0445"/>
        </default>
        <default class="fingertip_pad_collision_2">
          <geom type="box" size="0.003 0.002 0.003" pos="0.0055 0.002 0.05"/>
        </default>
        <default class="fingertip_pad_collision_3">
          <geom type="box" size="0.003 0.002 0.003" pos="-0.0055 0.002 0.05"/>
        </default>
        <default class="fingertip_pad_collision_4">
          <geom type="box" size="0.003 0.002 0.0035" pos="0.0055 0.002 0.0395"/>
        </default>
        <default class="fingertip_pad_collision_5">
          <geom type="box" size="0.003 0.002 0.0035" pos="-0.0055 0.002 0.0395"/>
        </default>
      </default>
    </default>
  </default>

  <asset>
    <texture name="grid" builtin="checker" height="500" rgb1=".1 .2 .3" rgb2=".2 .3 .4" type="2d" width="500"/>
    <material name="grid" texture="grid" texrepeat="1 1" texuniform="true" reflectance=".2"/>

    <material class="panda" name="white" rgba="1 1 1 1"/>
    <material class="panda" name="off_white" rgba="0.901961 0.921569 0.929412 1"/>
    <material class="panda" name="black" rgba="0.25 0.25 0.25 1"/>
    <material class="panda" name="green" rgba="0 1 0 1"/>
    <material class="panda" name="light_blue" rgba="0.039216 0.541176 0.780392 1"/>

    
    <mesh name="link0_c" file="link0.stl"/>
    <mesh name="link1_c" file="link1.stl"/>
    <mesh name="link2_c" file="link2.stl"/>
    <mesh name="link3_c" file="link3.stl"/>
    <mesh name="link4_c" file="link4.stl"/>
    <mesh name="link5_c0" file="link5_collision_0.obj"/>
    <mesh name="link5_c1" file="link5_collision_1.obj"/>
    <mesh name="link5_c2" file="link5_collision_2.obj"/>
    <mesh name="link6_c" file="link6.stl"/>
    <mesh name="link7_c" file="link7.stl"/>
    <mesh name="hand_c" file="hand.stl"/>

    
    <mesh file="hand_0.obj"/>
    <mesh file="hand_1.obj"/>
    <mesh file="hand_2.obj"/>
    <mesh file="hand_3.obj"/>
    <mesh file="hand_4.obj"/>
    <mesh file="finger_0.obj"/>
    <mesh file="finger_1.obj"/>
  </asset>

  <worldbody>
  
    <light directional="true" diffuse=".4 .4 .4" specular="0.1 0.1 0.1" pos="0 0 5.0" dir="0 0 -1" castshadow="false"/>
    <light directional="true" diffuse=".6 .6 .6" specular="0.2 0.2 0.2" pos="0 0 4" dir="0 0 -1" castshadow="false"/>

    <geom name="ground" type="plane" size="0 0 1" pos="0 0 0" quat="1 0 0 0" material="grid" condim="6"/>

    <light name="top" pos="0 0 2" mode="trackcom"/>

    
    <body name="hand" pos="0 0 0.107" quat="0. 0.3826834 0 -0">
      <inertial mass="0.73" pos="-0.01 0 0.03" diaginertia="0.001 0.0025 0.0017"/>
      <geom mesh="hand_0" material="off_white" class="visual"/>
      <geom mesh="hand_1" material="black" class="visual"/>
      <geom mesh="hand_2" material="black" class="visual"/>
      <geom mesh="hand_3" material="white" class="visual"/>
      <geom mesh="hand_4" material="off_white" class="visual"/>
      <geom mesh="hand_c" class="collision"/>

      <joint name="joint1" type="slide" pos="0 0 0" axis="0 0 1" range="-2.7437 2.7437" damping="100"/>

      <body name="left_finger" pos="0 0 0.0584">
        <inertial mass="0.015" pos="0 0 0" diaginertia="2.375e-6 2.375e-6 7.5e-7"/>
        <joint name="finger_joint1" class="finger"/>
        <geom mesh="finger_0" material="off_white" class="visual"/>
        <geom mesh="finger_1" material="black" class="visual"/>
        <geom mesh="finger_0" class="collision"/>
        <geom class="fingertip_pad_collision_1"/>
        <geom class="fingertip_pad_collision_2"/>
        <geom class="fingertip_pad_collision_3"/>
        <geom class="fingertip_pad_collision_4"/>
        <geom class="fingertip_pad_collision_5"/>

        <body name="left_dummy_body_1" pos="-0.005 -0.001 0.05">
          <geom name="left_dummy_geom_1" type="box" rgba="1 0 0 1" size="0.001 0.001 0.001" mass="0.0001"/>
          <site name="left_dummy_site_1" type="box" rgba="1 0 0 1" size="0.001 0.001 0.001" />
        </body>

        <body name="left_dummy_body_2" pos="0.005 -0.001 0.05">
          <geom name="left_dummy_geom_2" type="box" rgba="1 0 0 1" size="0.001 0.001 0.001" mass="0.0001"/>
          <site name="left_dummy_site_2" type="box" rgba="1 0 0 1" size="0.001 0.001 0.001" />
        </body>

        <body name="left_dummy_body_3" pos="0.005 -0.001 0.04">
          <geom name="left_dummy_geom_3" type="box" rgba="1 0 0 1" size="0.001 0.001 0.001" mass="0.0001"/>
          <site name="left_dummy_site_3" type="box" rgba="1 0 0 1" size="0.001 0.001 0.001" />
        </body>

        <body name="left_dummy_body_4" pos="-0.005 -0.001 0.04">
          <geom name="left_dummy_geom_4" type="box" rgba="1 0 0 1" size="0.001 0.001 0.001" mass="0.0001"/>
          <site name="left_dummy_site_4" type="box" rgba="1 0 0 1" size="0.001 0.001 0.001" />
        </body>
      </body> 

      <body name="right_finger" pos="0 0 0.0584" quat="0 0 0 1">
        <inertial mass="0.015" pos="0 0 0" diaginertia="2.375e-6 2.375e-6 7.5e-7"/>
        <joint name="finger_joint2" class="finger"/>
        <geom mesh="finger_0" material="off_white" class="visual"/>
        <geom mesh="finger_1" material="black" class="visual"/>
        <geom mesh="finger_0" class="collision"/>
        <geom class="fingertip_pad_collision_1"/>
        <geom class="fingertip_pad_collision_2"/>
        <geom class="fingertip_pad_collision_3"/>
        <geom class="fingertip_pad_collision_4"/>
        <geom class="fingertip_pad_collision_5"/>

        <body name="right_dummy_body_1" pos="-0.005 -0.001 0.05">
          <geom name="right_dummy_geom_1" type="box" rgba="1 0 0 1" size="0.001 0.001 0.001" mass="0.0001"/>
          <site name="right_dummy_site_1" type="box" rgba="1 0 0 1" size="0.001 0.001 0.001" />
        </body>

        <body name="right_dummy_body_2" pos="0.005 -0.001 0.05">
          <geom name="right_dummy_geom_2" type="box" rgba="1 0 0 1" size="0.001 0.001 0.001" mass="0.0001"/>
          <site name="right_dummy_site_2" type="box" rgba="1 0 0 1" size="0.001 0.001 0.001" />
        </body>

        <body name="right_dummy_body_3" pos="0.005 -0.001 0.04">
          <geom name="right_dummy_geom_3" type="box" rgba="1 0 0 1" size="0.001 0.001 0.001" mass="0.0001"/>
          <site name="right_dummy_site_3" type="box" rgba="1 0 0 1" size="0.001 0.001 0.001" />
        </body>

        <body name="right_dummy_body_4" pos="-0.005 -0.001 0.04">
          <geom name="right_dummy_geom_4" type="box" rgba="1 0 0 1" size="0.001 0.001 0.001" mass="0.0001"/>
          <site name="right_dummy_site_4" type="box" rgba="1 0 0 1" size="0.001 0.001 0.001" />
        </body>
      </body>
    </body>

    
      
      
    

    <body name="object" pos="-0.05 0 0" euler="0 1.57 0">
      <joint type="free" />
      
      <geom name="object" type="box" mass="0.5" size="0.01 .01 .08" rgba="1 0 0 1"/>
    </body>
  </worldbody>
  <tendon>
    <fixed name="split">
      <joint joint="finger_joint1" coef="0.5"/>
      <joint joint="finger_joint2" coef="0.5"/>
    </fixed>
  </tendon>

  <equality>
    <joint joint1="finger_joint1" joint2="finger_joint2" solimp="0.95 0.99 0.001" solref="0.005 1"/>
  </equality>

  <actuator>
    <motor ctrllimited="true" ctrlrange="-12.0 12.0" joint="joint1" name="actuator1"/>
     
    <motor ctrllimited="true" tendon="split" forcerange="-20 20" ctrlrange="-20 20" name="actuator8"/>
  </actuator>

  

  <sensor>
    <force name="left_dummy_site_1" site="left_dummy_site_1"/>
    <force name="left_dummy_site_2" site="left_dummy_site_2"/>
    <force name="left_dummy_site_3" site="left_dummy_site_3"/>
    <force name="left_dummy_site_4" site="left_dummy_site_4"/>

    <force name="right_dummy_site_1" site="right_dummy_site_1"/>    

    <force name="right_dummy_site_2" site="right_dummy_site_2"/>
    <force name="right_dummy_site_3" site="right_dummy_site_3"/>
    <force name="right_dummy_site_4" site="right_dummy_site_4"/>
    
    

  </sensor>

</mujoco>

</details>

Here is a screenshot / video, illustrating my question:
![image](https://github.com/google-deepmind/mujoco/assets/109202740/f0aa14c2-d2b3-4e79-a8eb-d6a0c97d7ed6)
[Screencast from 2024년 03월 27일 22시 33분 31초.webm](https://github.com/google-deepmind/mujoco/assets/109202740/441d7bad-1141-408b-926e-6e505a33c8fe)
09202740/6cd0a2a3-eb1d-4e4e-88fc-00c6cc35d6d6)

**Comment by yuvaltassa** [comment]
This is common and not unphysical. Force-vibration due to fast stick-slip is something that happens.

Try reducing the timestep and see what effect that has.

**Comment by 2-woo-10** [comment]
This is the result of setting the current timestep to 0.05.
[Screencast from 2024년 03월 27일 23시 18분 06초.webm](https://github.com/google-deepmind/mujoco/assets/109202740/aeae2a9d-6d00-4a7d-ab04-bb11cfe984a8)

**Comment by 2-woo-10** [comment]
@yuvaltassa

This is the result of setting the current timestep to 0.05.
[Screencast from 2024년 03월 27일 23시 18분 06초.webm](https://github.com/google-deepmind/mujoco/assets/109202740/aeae2a9d-6d00-4a7d-ab04-bb11cfe984a8)

**Comment by yuvaltassa** [comment]
50ms is huge! Try 1ms
