### ISSUE TITLE
Custom object integration using obj2mjcf and controlling their physical properties

### ISSUE THREAD

**Issue by anupampatil44** [google-deepmind/mujoco#1557]
Hi,

I am trying to integrate a custom object that I modeled in Blender and used [obj2mjcf](https://github.com/kevinzakka/obj2mjcf) to get the corresponding XML file into an  [existing environment XML](https://github.com/MarkFzp/act-plus-plus/blob/main/assets/bimanual_viperx_transfer_cube.xml). 

The modification of the original code file is as follows:
```
<mujoco>
    <include file="scene.xml"/>
    <include file="vx300s_dependencies.xml"/>
	
	<asset>
            <!-- loaded all the requisite assets, add this to vx300s_dependencies.xml under assets -->
            <mesh file="custom_object.obj"/>
       </asset>
	<default>
      <default class="wall">
            <geom type="plane" size=".5 .5 .05"/>
      </default>
      <default class="visual">
          <geom group="2" type="mesh" contype="0" conaffinity="0"/>
      </default>
      <default class="collision">
          <geom group="3" type="mesh"/>
      </default>
  </default>

    <worldbody>
		
        <include file="vx300s_left.xml" />
        <include file="vx300s_right.xml" />
		
        <body name="custom_object" pos="0 .5 0.1">
           <geom solimp="2 1 0.01" solref="0.01 1" friction="1 0.005 0.0001" pos="0 0 0" size="0.0002" mesh="custom_object" class="visual"/>
           <geom solimp="2 1 0.01" solref="0.01 1" friction="1 0.005 0.0001" pos="0 0 0" size="0.0002" mesh="custom_object" class="collision"/>
    	</body>
</worldbody>
```
[Link to the custom_object.obj file](https://drive.google.com/file/d/1MY2d1OuVbBVT-I4ZxZwruMJ8JOAGFs1D/view?usp=sharing)
We are able to get the objects in the environment by including them into the xml as shown above, however we are getting errors in adding essential physics attributes such as the position, size of object, mass, inertia etc. which are necessary for the objects to behave realistically within the MuJoCo environment.

![Screenshot from 2024-03-13 13-23-49](https://github.com/google-deepmind/mujoco/assets/61505546/a5e9aec2-501a-4867-8805-31d823079ac9)
The tiny spec at the top of right of the image is my object, which remains fixed there. I need to get it to the appropriate position near the grippers, as well as have physical properties for appropriate simulation.

What is the best way to go about with this?

Thanks and Regards

**Comment by yuvaltassa** [comment]
This is a very basic question. Try going over the tutorial.
