### ISSUE TITLE
Finding predecessor states

### ISSUE THREAD

**Issue by richardrl** [google-deepmind/mujoco#1558]
From the current state, is it possible to compute the predecessor state given some action?

**Comment by Balint-H** [comment]
What is your use case?

You might be able to get something close on a small timescale to that by reversing forces. However, picture the case of an object falling down and settling on the ground under zero control. Having this functionality would imply being able to suddenly predict that the object will penetrate the ground, then launch up.

**Comment by yuvaltassa** [comment]
If you set timestep to a negative value you can reverse the physics 🙂
