### ISSUE TITLE
[C#] What is a good method to use void * in C# (the simulate's UI framework (ref Unity's MjBindings)

### ISSUE THREAD

**Issue by kshfire** [google-deepmind/mujoco#1580]
Hi,

I'm trying to utilize the Mujoco in C# application.
Fortunately, there are already some codes **(Unity plugin)**.

I want to reimplement the simulate's functions and UI by C#, however, I have trouble in some void pointers in the UI-related functions and data.
For example,

[StructLayout(LayoutKind.Sequential)]
public unsafe struct mjuiState_ {
...
...

public void* userdata;

...
}

[StructLayout(LayoutKind.Sequential)]
public unsafe struct mjUI_ {
...
public void* userdata;
...
}

[StructLayout(LayoutKind.Sequential)]
public unsafe struct mjuiDef_ {
...
public void* pdata;
...
}

====================      simulate      ===================================

void Simulate::RenderLoop() {
...
  // set GUI adapter callbacks
  this->uistate.userdata = this;
  this->platform_ui->SetEventCallback(UiEvent);
  this->platform_ui->SetLayoutCallback(UiLayout);

  // populate uis with standard sections
  **this->ui0.userdata = this;
  this->ui1.userdata = this;**
...
}

Problem example1 :  In C#, I couldn't find a method casting a class instance to a void pointer. Is there an any good method ?

void MakeJointSection(mj::Simulate* sim, int oldstate) {
...
      // set data and name
      if (!sim->is_passive_) {
        defSlider[0].pdata = &sim->d_->qpos[sim->m_->jnt_qposadr[i]];
      } else {
        **defSlider[0].pdata = &sim->qpos_[sim->jnt_qposadr_[i]];**
      }
...
}

Problem example2 :  Instead of std::vector\<mjtNum\> type, I used the List\<mjtNum\> type for qpos_.  In C#, casting List<mjtNum> to void pointer is failed.  Is there an any good method ?

Especially, reproducing the UI0 and UI1 parts in C# are really difficult to me.  I think the void pointer is a main problem in C# and I don't want to recreate that part.
I'd really appreciate it if someone could tell me any good methods or ideas.

**Comment by Balint-H** [comment]
Hello,
In this case you don't need to use a void pointer. As far as I understand, you want slider functionality that sets Qpos, do I understand correctly, or am I missing anything else? To do this you could set the qpos in the MjScene's Data field.

If you don't want to set the qpos on every frame you can disable the MjScene after it finishes initializing (so it doesn't step the simulation on every FixedUpdate). In that case you can modify Data as you wish, perform mj_step1 or other API calls to properly update the kinematics, then call the Synchronisation methods of the MjScene manually. Then you'd only need to do this when the slider value changes.

Let me know if you have questions about doing any of these steps, or if you have further questions.
