### ISSUE TITLE
Issues with Camera Settings and Rendering in Mujoco

### ISSUE THREAD

**Issue by kankannali** [google-deepmind/mujoco#1608]
Hello Mujoco Support Team,

I am experiencing issues with configuring the camera settings in the Mujoco simulation environment that affect the rendered output. Specifically, I am trying to render images with a resolution of 1280x720 pixels. However, the actual rendered images only occupy a small portion at the bottom-left corner of the output, with the rest of the image being filled with black padding. Despite various adjustments to the camera's fovy and focalpixel parameters, the proportion of the actual image to the black padding in the rendered output remains unchanged. This indicates that the changes to the camera settings do not affect the rendered image as expected, pointing to a possible issue in how these settings are being applied or interpreted by the rendering engine.

**Issue Description:**
_XML Camera Configuration_: I have defined the camera in my XML file. Despite various adjustments to these parameters, the size and position of the actual rendered section of the image remain unchanged, with a significant portion of the output still appearing as black padding.Here is the camera definition from my XML file:
``<camera name="rgbd_camera" pos="0 0 0" euler="90 -90 0"/>
``
``<camera name="rgbd_camera" pos="0 0 0" euler="90 -90 0" fovy="82" resolution="1280 720"/>
``
``<camera name="rgbd_camera" pos="0 0 0" euler="90 -90 0" resolution="1280 720" focalpixel="736 736"  sensorsize="0.036 0.024"/>
``

_Visualization Code_: I am using the following Python code to render images:
`def get_rgbd_data(self):`
`    camera_name = 'rgbd_camera'`
`    camera_id = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_CAMERA, camera_name)`
`    self.cam.type = mujoco.mjtCamera.mjCAMERA_FIXED`
`    self.cam.fixedcamid = camera_id`
`    viewport = mujoco.MjrRect(0, 0, 1280, 720)`
`    mujoco.mjv_updateScene(self.model, self.data, mujoco.MjvOption(), None, self.cam, mujoco.mjtCatBit.mjCAT_ALL, self.scene)`
`    mujoco.mjr_render(viewport, self.scene, self.context)`
`    rgb_data = np.zeros((viewport.height, viewport.width, 3), dtype=np.uint8)`
`    depth_data = np.zeros((viewport.height, viewport.width), dtype=np.float32)`
`    mujoco.mjr_readPixels(rgb_data, depth_data, viewport, self.context)`
`    rgb_image = cv2.flip(rgb_data, 0)`
`    rgb_image = cv2.cvtColor(rgb_image, cv2.COLOR_RGB2BGR)`
`    depth_image = (depth_data - depth_data.min()) / (depth_data.max() - depth_data.min()) * 255`
`    depth_image = cv2.flip(depth_image.astype(np.uint8), 0) `
`    depth_data = cv2.flip(depth_data, 0)`
`    self.save_rgbd_data(rgb_image, depth_image, self.step_count)`
`    return rgb_image, depth_data`
`def save_rgbd_data(self, rgb_image, depth_image, step_count, save_path='original_result/'):`
`    rgb_filename = f"rgb_{step_count}.png"`
`    cv2.imwrite(f"{save_path}{rgb_filename}_mask.png", rgb_image)`
`    depth_filename = f"depth_{step_count}.png"`
`    depth_image_visual = cv2.normalize(depth_image, None, 0, 255, cv2.NORM_MINMAX)`
`    depth_image_visual = depth_image_visual.astype('uint8')`
`    cv2.imwrite(f"{save_path}{depth_filename}_mask.png", depth_image_visual)`
Problematic Output: Regardless of the parameter adjustments in the XML configuration, the output images consistently show a small, correctly rendered section at the bottom-left corner with the remaining area filled with black. 
![rgb_0 png_mask](https://github.com/google-deepmind/mujoco/assets/60174245/1ec1c257-50f1-4c12-bb8f-e969964a6491)

Expected Behavior:
I anticipate that adjustments to the camera's fovy and focalpixel settings would significantly alter the field of view and effectively utilize the entire 1280x720 resolution set in the viewport, eliminating the black padding observed in the current output.

_Besides:_ In reviewing how Mujoco outputs depth information, I have noticed that previously, Mujoco would normalize the depth data (the depth_data in my code) to a range of [0, 1]. Does this normalization behavior still exist in the current version of Mujoco? Understanding this will help me better interpret and utilize the depth data obtained from the simulation.

I would greatly appreciate any guidance on what might be causing this issue and how to correct it. Your insights or recommendations would be highly valuable.

Thank you for your time and assistance!

**Comment by yuvaltassa** [comment]
As [documented](https://mujoco.readthedocs.io/en/latest/XMLreference.html#body-camera-resolution), resolution needs to be specified when you set up the context. I recommend reading the code of [renderer](https://github.com/google-deepmind/mujoco/blob/main/python/mujoco/renderer.py) module, which will also show you how to convert openGL's (not MuJoCo's) normalized depth in to units of length. I believe that wakling through our [tutorial](https://github.com/google-deepmind/mujoco?tab=readme-ov-file#getting-started) will answer many of your questions.
