### ISSUE TITLE
Using mujoco(bin\compile.exe) to generate MJCF format XML files

### ISSUE THREAD

**Issue by xsc9202** [google-deepmind/mujoco#1610]
Hi,

I'm a  engineer and I'm trying to use MuJoCo(bin\bin\compile.exe) for the MJCF XML files. but encountered some problems:
we used Mujoco (mujoco-3.1.3-windows-x86_64\bin\compile.exe) to generate MJCF format XML files will result in losing the content of the first body.
I'm looking for some help:
1.Is it because we did not use the software correctly?
2.Or this is the mujoco software bug?
Thks!
![缺失body](https://github.com/google-deepmind/mujoco/assets/167731348/2db933d9-bb69-424e-a244-ee5037daf61b)

**Comment by yuvaltassa** [comment]
Are you converting from URDF?

**Comment by xsc9202** [comment]
Hi
Yes , we used the URDF .


Best Regards!

发件人: Yuval Tassa ***@***.***>
发送时间: 2024年4月22日 21:39
收件人: google-deepmind/mujoco ***@***.***>
抄送: 肖世池(Xiaoshichi) ***@***.***>; Author ***@***.***>
主题: Re: [google-deepmind/mujoco] Using mujoco(bin\compile.exe) to generate MJCF format XML files (Issue #1610)


外部邮件/External Mail


Are you converting from URDF?

―

**Comment by xsc9202** [comment]
Hi
we used the URDF and the STL files as following:
