### ISSUE TITLE
Pass a C++ mjData to python with pybind11, MuJoCo as a C++ and python library

### ISSUE THREAD

**Issue by pkrack** [google-deepmind/mujoco#1612]
Hi,

I am a student trying to use MuJoCo for collision detection and trajectory planning for a real robot, and for reinforcement learning experiments on the same simulated robot.

I need the flexibility to implement performance critical code in C/C++ (e.g. IK & trajectory planning), while being able to easily experiment with python (e.g. for reinforcement learning). 

I compile both the C dynamic library and the bindings with scikit-build-core and link my own code against the same dynamic library than the MuJoCo python bindings.
I write python bindings for my code using pybind11 as well.

I would like to interact with the simulation from python and C++. In this context, I am trying to return, from C++ to python, a pointer to a `mjData` struct.
Directly returning a reference to the shared pointer does not work.
```C++
py::class_<SimState>(pymodule, "SimState")
.def_readonly("collision", &SimState::collision)
...
.def_readonly("physics_state", &SimState::mjdata); // <- What should I return here?
```
Python complains that it does not know about the `mjData_`

I have tried including [`structs.h`](https://github.com/deepmind/mujoco/blob/bbbf30ee47688bb03cefc7c3d6475b8283c0712f/python/mujoco/structs.h) returning a `MjDataWrapper`, but I get an unknown symbol error, even after adding `PYBIND11_EXPORT` to the wrapper, the base wrapper class and the raw `mjData` object.

In [this](https://github.com/google-deepmind/mujoco/issues/983) issue, @saran-t seems to suggest that the `MjDataWrapper` is not necessary and I should simply return opaque pointers, which I tried with `PYBIND11_MAKE_OPAQUE`, but python still complains about an unknown type `mjData_` 

I am now out of ideas and grateful for any help.

**Comment by saran-t** [comment]
The easiest thing in your case is to instantiate the MjData object in Python and grab the underlying pointer as a void*, pass it as a long int to pybind11 and cast it back to mjData* in C++. That way you never need to deal with MuJoCo types across the Python/C++ boundary.

Alternatively, if you are interested in doing some fairly advanced pybind11 work, you can help us figure out how to register custom casters so that pybind11 understands that mjData should be casted via MjDataWrapper.

**Comment by peterdavidfagan** [comment]
@pkrack did you successfully link the python binding `MjWrapper` classes to your pybind library. It seems like yes based on:

> I compile both the C dynamic library and the bindings with scikit-build-core and link my own code against the same dynamic library than the MuJoCo python bindings.

Would it be possible to share this code if you have it. My strategy was to return the MjModelWrapper from my binding method for getting a readonly property similar to the following method:

```
mujoco::python::_impl::MjModelWrapper FrankaMJROS::get_model()
{
  return *mujoco::python::_impl::MjModelWrapper::FromRawPointer(this->m);
}
```

I think this should work right?

**Comment by peterdavidfagan** [comment]
> The easiest thing in your case is to instantiate the MjData object in Python and grab the underlying pointer as a void*, pass it as a long int to pybind11 and cast it back to mjData* in C++. That way you never need to deal with MuJoCo types across the Python/C++ boundary.

This might actually make more sense in my use case, going to try it out.
