### ISSUE TITLE
MJX model: Some fields are JAX Arrays, some are numpy arrays?

### ISSUE THREAD

**Issue by ju-kreber** [google-deepmind/mujoco#1615]
The documentation (https://mujoco.readthedocs.io/en/stable/mjx.html) states:

> 1. Fields in mjx.Model and mjx.Data are JAX arrays copied onto device, instead of numpy arrays.

However when I run the following code sample

```python
import mujoco
from mujoco import mjx

XML = "<mujoco />"

model = mujoco.MjModel.from_xml_string(XML)
mjx_model = mjx.device_put(model)

print(type(mjx_model.jnt_range), type(mjx_model.jnt_limited))
```

This prints `<class 'jaxlib.xla_extension.ArrayImpl'> <class 'numpy.ndarray'>`.

I am confused. Shoudn't all fields of mjx.Model be JAX arrays?

EDIT: `Python  3.10.14`,  `mujoco.__version__ == '3.1.3'`

**Comment by btaba** [comment]
Hi @ju-kreber , fields that are compiled and static, such as `jnt_limited`, remain numpy arrays, and importantly do not get traced. We'll update the docs accordingly; this is working as intended.

**Comment by ju-kreber** [comment]
Thanks for the clarification! It would be great to mention this in the documentation.
Also, I didn't yet understand what "static" means in this context (isn't the whole model usually static?), so explaining this could also improve users' understanding of MJX. :)

**Comment by btaba** [comment]
@ju-kreber let us know if the updated docs clarify some of the questions https://github.com/google-deepmind/mujoco/commit/b56d7d6e308d128c687e2108f28ad42c4b32b668

**Comment by erikfrey** [comment]
(which you can find now in the ["latest" version of our documentation](https://mujoco.readthedocs.io/en/latest/mjx.html#structs).)

**Comment by ju-kreber** [comment]
Yes, the updated docs explain it very well in my opinion.
Thanks for integrating this so quickly!
