### ISSUE TITLE
Out of memory while using MJX to load Google Barkour VB quadruped

### ISSUE THREAD

**Issue by JunhongXu** [google-deepmind/mujoco#1619]
Hi,

I'm a researcher and I'm trying to use MuJoCo for my research project.

I am looking for help with an out-of-memory issue while using MJX. The model I am loading is the [google_parkour_vb quadruped](https://github.com/google-deepmind/mujoco_menagerie/blob/main/google_barkour_vb/barkour_vb.xml). 

I am using a Nvidia 4090, which has 24 GB of memory, to simulate 20 robots at the same time. I know that JAX pre-allocates a large part of the GPU memory. Is this out-of-memory issue related to JAX pre-allocation?

Here is the code snippet that leads to out of memory error:
```python
import mujoco as mj 
import jax 
from mujoco import mjx
import numpy as np

mj_model = mj.MjModel.from_xml_path(PATH_TO_BARKOUR_VB)
mj_data = mj.MjData(mj_model)
# To make the mjx work, we need to set the frictionloss to zero.
mj_model.dof_frictionloss = np.zeros(len(mj_model.dof_frictionloss))

mjx_model = mjx.put_model(mj_model)
mjx_data = mjx.put_data(mj_model, mj_data)


jit_step = jax.jit(mjx.step)

rng = jax.random.PRNGKey(0)
rng = jax.random.split(rng, 20)
batch = jax.vmap(lambda rng: mjx_data.replace(qpos=jax.random.uniform(rng, (19,))))(rng)

jit_step = jax.jit(jax.vmap(mjx.step, in_axes=(None, 0)))
for i in range(100):
	batch = jit_step(mjx_model, batch)
```

Thanks for your help!

**Comment by JeyRunner** [comment]
Did you try running it with `XLA_PYTHON_CLIENT_MEM_FRACTION=0.5` (or some smaller fraction of preallocated memory)?
The default is 75%, which is 18GB in your case.
See https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html

**Comment by JunhongXu** [comment]
Hi @JeyRunner,

Thanks for your suggestion! But the solution is actually using the `mjx` model from `mujoco_menagerie/google_barkour_vb/scene_mjx.xml`. 

I am wondering what are the differences between the `mjx` and non-mjx version of the robot models and how to create an mjx robot model from the normal one?

**Comment by btaba** [comment]
Hi @JunhongXu , the differences are outlined here https://github.com/google-deepmind/mujoco_menagerie/tree/main/google_barkour_vb#mjx

A similar process should be done for other models. See also:

https://github.com/google-deepmind/mujoco_menagerie/tree/main/anybotics_anymal_c#mjx

**Comment by yuvaltassa** [comment]
See also

https://mujoco.readthedocs.io/en/latest/mjx.html#feature-parity
