### ISSUE TITLE
a question about abnormal and large fluctuations in contact force between ball and the jump

### ISSUE THREAD

**Issue by sanbens1234** [google-deepmind/mujoco#1620]
Hi,

I'm a student,  tenghui wang. I'm trying to use MuJoCo for simulating a ball rolling on the slope and jumps.

I'm looking for some help with abnormal and large fluctuations in contact force between ball and the jump, see in fig. 2.

I have 2 questions. The first question is that at the junction of the geom “slope” and geom "jumps", the contact force is about 2000N(i.e. at the begining of the x-axis in fig.2), which is abnormally large. The secon question is that during the process of rolling on the jumps, the contact force varies largey( about ±200N, the gravity of ball about 670N). The second question might be caused by the discrete points of the hfiled, but i don't know how to improve it.
Here is a model which explains my question:

<details>
  <summary>minimal XML</summary>

```XML
<mujoco model="go1 scene">
  <include file="generated_hfield.xml"/>

  <worldbody>
    <body name="sph_body" pos="30 0 12">
      <freejoint/> 
        <geom name="sph" type="sphere" size="0.2"/>
        <inertial mass="67" pos="0 0 0" diaginertia="0.1 0.1 0.1"/>
    </body>
    <geom name="jumps" type="hfield" hfield="example" pos="0 0 0" euler="0 0 -1.570796327" />
    <geom name="slope" size="400 20 0.00001" pos="25.60064256 0 9.822735615" euler="0 -0.19198621772 0" type="plane" contype="1" conaffinity="1"/>
    </worldbody>
</mujoco>

```
</details>
since the file "generated_hfield.xml" is too long, i zip it as follows,

[generated_hfield.zip](https://github.com/google-deepmind/mujoco/files/15112075/generated_hfield.zip) 

fig.1 the scene of the simulation
![截图 2024-04-25 22-28-01](https://github.com/google-deepmind/mujoco/assets/41227599/71357ebb-8506-42ab-a666-6641328fbe64)

fig.2 the contact force Fz between geom"jumps" and geom "sph"
<img width="893" alt="image" src="https://github.com/google-deepmind/mujoco/assets/41227599/75c85b22-5934-4370-aa37-642b8addec68">

**Comment by yuvaltassa** [comment]
Not clear why you think they are "abnormally large". There is a corner at the beginning of your your slope geom, the ball hits the corner and you get a large force. In any case, looking at contact force magnitude in this situation is useless. This is a timestep-dependent quantity. You should be looking at the integral of the the impulse (force*dt). The actual size of the force is not something that can be judged to be small or large without knowing the time during which it was applied.
