### ISSUE TITLE
Outdated link in generated code comments points to archived 'greg' repository

### ISSUE THREAD

**Issue by 7etsuo** [google-deepmind/mujoco#1622]
https://github.com/google-deepmind/mujoco/blob/d6553ed192eec115a488bcb60581f14b77bc8a2c/src/render/glad/glad.c#L1444

**Expected Result:**
The link in the comment should lead to a valid file or should be updated/removed if it's no longer relevant.

**Actual Result:**
The link directs to an archived repository with the specified path missing.

**Suggested Fix:**
The comment should be removed to avoid confusion.

**Comment by yuvaltassa** [comment]
FYI This code is autogenerated by glad.
