### ISSUE TITLE
geom/site position change problem after model compilation 

### ISSUE THREAD

**Issue by lshdlut** [google-deepmind/mujoco#1628]
Hi, I'm a researcher and I'm using MuJoCo for inverse kinematics tasks.

### **The problem**
After model compilation (from xml file), I have modified the position of some elements with the following code:
```
m.geom_pos[ m.geom('test_geom').id, 1 ] = 0.5
m.site_pos[ m.geom('test_site').id, 2 ] = 0.5
mujoco.mj_fwdPosition( m, d )
viewer.sync()
```

I found that:
- Sites with a default position of '0 0 0' in the XML file do not move
- Sites with at least 1 non-zero value in their default position in the XML file move as expected
- Geoms performed more complicated behavior and I was not able to figure it out.
- It seems that geom behavior changes depending on its type, position, and the attributes of other elements within the same body (?)

### **The question**
Is it a bug or a feature?

### **Detailed description**

- I wanted to visualize the target position/orientation (more like a point cloud in my case)
-  I have already tried with mujoco.mjv_addGeoms(). It worked well but sometimes is not staightforward when you want to modify the pos in the world frame.
-  I have also tried mocap bodies. However, they significantly affect the kinematic tree, especially since I need to add up to hundreds of them.
- I then tried adding geom/site directly to the worldbody and modifying the pos in the world frame.

**Comment by yuvaltassa** [comment]
This is a feature. Some objects have a property called sameframe e.g. site_sameframe, determined at compile time, which means that at runtime the full frame transform can be skipped and merely copied from the parent. This can speed up kinematics a lot. You can set it to 0 if you're changing positions/orientations post-compile.

Bodies have an even stronger property called body_simple, which implies a diagonal inertia matrix. I'm not sure if changing that post-compile is safe. I can check if you like. If you have simple bodies and you're moving around mass-conferring geoms, the physics will likely be wrong.
