### ISSUE TITLE
Understanding different times associated with simulation?

### ISSUE THREAD

**Issue by kurtenkera** [google-deepmind/mujoco#1634]
Hi, I've been following the examples in [tutorial.ipynb](https://colab.research.google.com/github/google-deepmind/mujoco/blob/main/python/tutorial.ipynb#scrollTo=3jHYTV-bwfrS), and I've noticed that there are various different, but important notions of time in a given simulation. 

I'm most familiar with the mathematical timestep, dt, that is used to integrate Newton's laws of motions (a smaller timestep typically means a more accurate simulation). But then there is also 'clock time' (i.e., how long it takes for the computer to run the simulation). And rendering time... And simulation time.

Can anyone explain these subtle nuances in a concise clear way? I've looked at countless articles online, but the distinctions are not clear to me? I need to know as I'm struggling to understand how the example on `Contacts` in [tutorial.ipynb](https://colab.research.google.com/github/google-deepmind/mujoco/blob/main/python/tutorial.ipynb#scrollTo=3jHYTV-bwfrS) presents a simulation that is "1/4x real time"? (This is the relevant code below):

```
# simulate and render
for i in range(n_frames):
  while data.time < i/120.0: #1/4x real time
    mujoco.mj_step(model, data)
  renderer.update_scene(data, "track", options)
  frame = renderer.render()
  frames.append(frame)
```

**Comment by yuvaltassa** [comment]
Regarding the specific question, video is played back at 30hz by default by the mediapy utility used in the tutorial. By rendering frames every 1/120 of a second, playback will be at 1/4x real time.

Any other specific questions?
