### ISSUE TITLE
Slip simulation 

### ISSUE THREAD

**Issue by 2-woo-10** [google-deepmind/mujoco#1643]
"Hello,

I'm currently using the Mujoco simulator to create a dataset by attaching a sensor to the end of a gripper. I'm trying to simulate a scenario where the gripper grasps an object and moves it, applying an external force to make the object slide. However, even after grasping, the object slips regardless of the grasping force applied by the gripper. I would appreciate any advice on how to address this issue.

Thank you."

**Comment by yuvaltassa** [comment]
https://mujoco.readthedocs.io/en/latest/modeling.html#preventing-slip
