### ISSUE TITLE
Understanding the relationship between body frame and inertial properties.

### ISSUE THREAD

**Issue by r0adrunner** [google-deepmind/mujoco#1652]
I am new to mujoco.
I do not understand the concept of a inertial frame.
If i change the inertial properties via <body/inertial/fullinertia> there is a new frame created when I switch on the 'inertia' button on the 'model elements' tab of the simulator when the frame rendering option is set to 'body', that 'aligns' in some way to the inertial matrix entered.
What is it there for? Does it change anything about the original body frame?

**Comment by yuvaltassa** [comment]
Quoting from the [documentation](https://mujoco.readthedocs.io/en/latest/overview.html#body):

"Each body has two coordinate frames: the frame used to define it as well as to position other elements relative to it, and an inertial frame centered at the body’s center of mass and aligned with its principal axes of inertia. The body inertia matrix is therefore diagonal in this frame."
