### ISSUE TITLE
anisotropic bending stiffness for cable

### ISSUE THREAD

**Issue by sanbens1234** [google-deepmind/mujoco#1653]
Hi,

I'm a student and I'm trying to use MuJoCo for simulating anisotropic bending stiffness for cable .

I learned the demo of elastic cable,as shown below. My question is that if it's possible to set anisotropic bending stiffness, i.e E_by!=E_bz, see fig.1 . In particular, I want to set E_by=∞, so that the cable can only bend around z-axis.

Here is a model which explains my question:

<details>
  <summary>minimal XML</summary>

```XML
<mujoco model="Cable">
  <include file="scene.xml"/>

  <extension>
    <plugin plugin="mujoco.elasticity.cable"/>
  </extension>

  <statistic center="0 0 .3" extent="1"/>
  <visual>
    <global elevation="-30"/>
  </visual>

  <compiler autolimits="true"/>

  <size memory="2M"/>

  <worldbody>
    <composite type="cable" curve="s" count="41 1 1" size="1" offset="-.3 0 .6" initial="none">
      <plugin plugin="mujoco.elasticity.cable">
        <!--Units are in Pa (SI)-->
        <config key="twist" value="1e7"/>
        <config key="bend" value="4e6"/>
        <config key="vmax" value="0.05"/>
      </plugin>
      <joint kind="main" damping=".015"/>
      <geom type="capsule" size=".005" rgba=".8 .2 .1 1" condim="1"/>
    </composite>
    <body name="slider" pos=".7 0 .6">
      <joint type="slide" axis="1 0 0" damping=".1"/>
      <geom size=".01"/>
    </body>
  </worldbody>
  <equality>
    <connect name="right_boundary" body1="B_last" body2="slider" anchor=".025 0 0"/>
  </equality>
  <contact>
    <exclude body1="B_last" body2="slider"/>
  </contact>
  <actuator>
    <motor site="S_last" gear="0 0 0 1 0 0" ctrlrange="-.03 .03"/>
  </actuator>
</mujoco>
```

</details>

figure 1
![Photo_0513_1a](https://github.com/google-deepmind/mujoco/assets/41227599/b36705e7-48f4-4280-b4ae-14d50c5b9e2d)

**Comment by quagla** [comment]
We do not support anisotropic stiffnesses although it's super easy to do it if you can compile from source. The only thing you need would be to hard code it here https://github.com/google-deepmind/mujoco/blob/main/plugin/elasticity/cable.cc#L198

Feel free to open a new issue if that doesn't work!
