### ISSUE TITLE
mujoco display irregularity

### ISSUE THREAD

**Issue by ylang-ylang** [google-deepmind/mujoco#1656]
Hi,

I'm a student and I'm trying to use MuJoCo for RL training

I'm looking for some help with display issue

I tried mujoco 200, 237, 315, None of them work properly on my laptop :(
All of them are only showing a little bit of the image in the top left corner as shown below
It seems to be just a display issue, I can even manipulate the options in this small area

And I use a computer with an amd cpu with core graphics and a nvidia graphics card, I don't know if that helps.
I'm hoping to find a way to get it to work on my computer, thank you very much for your reply!

![屏幕截图 2024-05-13 185413](https://github.com/google-deepmind/mujoco/assets/90782530/0faade37-a5bf-4f3b-b14f-1e0c45a09472)

**Comment by ylang-ylang** [comment]
Never mind.I updated my core graphics card driver and everything seems to be working fine! :)
![image](https://github.com/google-deepmind/mujoco/assets/90782530/d82e33e9-6ca2-4b7a-b40f-530e79f487e1)
For those of you who also using amd cpu with Radeon 680M core graphics, updating to 31.0.24031.5001 will solve your problem!

**Comment by ylang-ylang** [comment]
After I restarted the laptop, the strange thing happened again
![image](https://github.com/google-deepmind/mujoco/assets/90782530/6d9cae0a-81c0-419a-b15d-10043ba006f1)
I really don't have a clue.

**Comment by RagibRownak** [comment]
Same issue there also. Did anyone found any solutions for this issue?

**Comment by yuvaltassa** [comment]
Hmm there used to be an open issue about problems related to AMD GPUs but I can't seem to find it...

@saran-t can you find it?

**Comment by RagibRownak** [comment]
is there any way to solve this gui interface issue with AMD GPUs? Any advice or hack or solve is appreciated.

**Comment by wjxway** [comment]
https://github.com/google-deepmind/mujoco/issues/639

**Comment by kevinzakka** [comment]
Let's keep track of AMD related issues in #639.
