### ISSUE TITLE
how to get flexible body position and velocity

### ISSUE THREAD

**Issue by Pablo-M-V-99** [google-deepmind/mujoco#1674]
Hi,
I'm a student and I'm trying to use MuJoCo for simulating a moving flag.
Here is the model I'm using for the flag:

		<body name="pin" pos="0 0 1.5">
	  		<flexcomp name="flag" type="grid" count="9 19 1" spacing="0.05 0.05 0.05" mass="10" radius="0.001">
		    	<edge equality="true" damping="0.001"/>
				<plugin plugin="mujoco.elasticity.shell">
				  	<config key="thickness" value="1e-2"/>
				 						
				  	<config key="poisson" value="0"/>
				  	<config key="young" value="3e6"/>
		    	        </plugin>
		  	</flexcomp>
		</body>

At the moment two hems of the flag are locked in place, while the other two are connected to a mocap body that I use to simulate a desired movement for the flag. For the movement I wrote a 5th degree polynomial trajectory, which, in theory, guarantees the movement ends with zero speed and zero acceleration. 
However, I would like to implement a test on the velocity of all the elements that make up the flag to be sure the flag is completely still before starting a new movement. 
Something like:

for all the elements that make up the flag
    if element_speed > threshold_speed  
        wait until element_speed <= threshold_speed

I have started using Mujoco only recently, so I don't know how I can access this information. Can you help me?

**Comment by quagla** [comment]
Hi @Pablo-M-V-99 

These are the array you would like to look at https://github.com/google-deepmind/mujoco/blob/main/include/mujoco/mjmodel.h#L840

For an usage example, please have a look at e.g. https://github.com/google-deepmind/mujoco/blob/7ca8a629a2f1be89d7c27c36fd5720532cad2471/src/engine/engine_setconst.c#L216 

Let me know if it doesn't help!
