### ISSUE TITLE
D4RL mujoco datasets compatibility between versions

### ISSUE THREAD

**Issue by atagle123** [google-deepmind/mujoco#1700]
Hi,

I'm a student and I'm trying to use MuJoCo to build some RL models and test them in the D4RL benchmark.

I'm looking for some help with the versions of the respective D4RL environments.
My question is as follows: mujoco-py is now deprecated, so I want to use the new MuJoCo library. However, the D4RL datasets are made with the v2 environments that use mujoco-py. I would like to know if it’s possible to train an offline model-based RL algorithm with the v2 datasets (e.g., HalfCheetah v2) and later test it online with the v3-v4 environments. In other words, are the dynamics and rewards across the versions of the environments still the same?

Thanks in advance.

**Comment by yuvaltassa** [comment]
https://mujoco.readthedocs.io/en/latest/computation/index.html#reproducibility
