### ISSUE TITLE
Disabling contact rendering for Touch Sensor Grid plugin

### ISSUE THREAD

**Issue by eneserciyes** [google-deepmind/mujoco#1705]
Hi,

I'm using the [touch sensor grid plugin](https://github.com/google-deepmind/mujoco/blob/main/plugin/sensor/README.md#touch-grid) for tactile simulation.

This plugin renders the force on touch points like this:

![Screenshot from 2024-05-30 20-32-40](https://github.com/google-deepmind/mujoco/assets/20225199/b49df604-e279-43ef-8cda-ef74c8c26854)

Is there a way I can disable this rendering?

**Comment by yuvaltassa** [comment]
Currently there is no way to disable it, but there probably should be...

However, I'd rather not add yet another vis flag just for plugins. In the meantime, assuming you are [building from source](https://mujoco.readthedocs.io/en/latest/programming/index.html#building-from-source), just add above [this line](https://github.com/google-deepmind/mujoco/blob/f616975e28d6bcae3c5364da5c3ea7ae4f80809c/plugin/sensor/touch_grid.cc#L381) something like
```C
if (opt.flags[mjVIS_FLAGOFYOURCHOICE]) return;
```
