### ISSUE TITLE
Human musculoskeletal motion simulation using mujoco

### ISSUE THREAD

**Issue by 2802029572** [google-deepmind/mujoco#1707]
Hi,

I'm a student and I'm trying to Human musculoskeletal motion simulation using mujoco

I'm looking for some help with I want to input the joint angle values at each moment into my mujoco human musculoskeletal model, but I found that my human body does not move according to my angle values, how should I modify the code and xml file.

Here is a model which explains my question:

<details>

<actuator>

    <general name="pelvis_tilt" joint="pelvis_tilt" class="motor"></general>
    <general name="pelvis_list" joint="pelvis_list" class="motor"></general>
    <general name="pelvis_rotation" joint="pelvis_rotation" class="motor"></general>
    <general name="pelvis_tx" joint="pelvis_tx" class="motor"></general>
    <general name="pelvis_ty" joint="pelvis_ty" class="motor"></general>
    <general name="pelvis_tz" joint="pelvis_tz" class="motor"></general>
    <general name="hip_flexion_r" joint="hip_flexion_r" class="motor"></general>
    <general name="hip_adduction_r" joint="hip_adduction_r" class="motor"></general>
    <general name="hip_rotation_r" joint="hip_rotation_r" class="motor"></general>
    <general name="knee_angle_r" joint="knee_angle_r" class="motor"></general>
    <general name="ankle_angle_r" joint="ankle_angle_r" class="motor"></general>
    <general name="subtalar_angle_r" joint="subtalar_angle_r" class="motor"></general>
    <general name="mtp_angle_r" joint="mtp_angle_r" class="motor"></general>
    <general name="hip_flexion_l" joint="hip_flexion_l" class="motor"></general>
    <general name="hip_adduction_l" joint="hip_adduction_l" class="motor"></general>
    <general name="hip_rotation_l" joint="hip_rotation_l" class="motor"></general>
    <general name="knee_angle_l" joint="knee_angle_l" class="motor"></general>
    <general name="ankle_angle_l" joint="ankle_angle_l" class="motor"></general>
    <general name="subtalar_angle_l" joint="subtalar_angle_l" class="motor"></general>
    <general name="mtp_angle_l" joint="mtp_angle_l" class="motor"></general>
    <general name="L5_S1_Flex_Ext" joint="lumbar_extension" class="motor"></general>
    <general name="L5_S1_Lat_Bending" joint="lumbar_bending" class="motor"></general>
    <general name="L5_S1_axial_rotation" joint="lumbar_rotation" class="motor"></general>
    <general name="arm_flex_r" joint="arm_flex_r" class="motor"></general>
    <general name="arm_add_r" joint="arm_add_r" class="motor"></general>
    <general name="arm_rot_r" joint="arm_rot_r" class="motor"></general>
    <general name="elbow_flex_r" joint="elbow_flex_r" class="motor"></general>
    <general name="pro_sup_r" joint="pro_sup_r" class="motor"></general>
    <general name="wrist_flex_r" joint="wrist_flex_r" class="motor"></general>
    <general name="wrist_dev_r" joint="wrist_dev_r" class="motor"></general>
    <general name="arm_flex_l" joint="arm_flex_l" class="motor"></general>
    <general name="arm_add_l" joint="arm_add_l" class="motor"></general>
    <general name="arm_rot_l" joint="arm_rot_l" class="motor"></general>
    <general name="elbow_flex_l" joint="elbow_flex_l" class="motor"></general>
    <general name="pro_sup_l" joint="pro_sup_l" class="motor"></general>
    <general name="wrist_flex_l" joint="wrist_flex_r" class="motor"></general>
    <general name="wrist_dev_l" joint="wrist_dev_l" class="motor"></general>

  </actuator>
</details>

Here are my joint numbers
![f17c7ec9cd08599b102ab34b92bef2f](https://github.com/google-deepmind/mujoco/assets/148313519/b59fef34-2422-4b91-823a-cf2b6b615796)

**Comment by yuvaltassa** [comment]
Your question does not contain enough information in order to help you.

Perhaps this will help
https://mujoco.readthedocs.io/en/latest/computation/index.html#consistency-in-mjdata
