### ISSUE TITLE
unity  'mujoco.elasticity.cable' error

### ISSUE THREAD

**Issue by mg638** [google-deepmind/mujoco#1709]
hello. I'm trying to test Mujoco in Unity, but when loading the model, the error is displayed and I can't use it.

IOException: Error loading the model: XML Error: unknown plugin 'mujoco.elasticity.cable'

I am using version 3.1.3. Does Unity not support elasticity yet?

**Comment by Balint-H** [comment]
Hello! Yes, at the moment elasticity plugin support is not added to the official branch yet, although preliminary tests were already done to confirm it is possible to add. I intended to revisit the topic at the start of July.

If it is a critical feature for you, and you don't mind tweaking the source code of the Unity plugin, I can help you get started before then though.

**Comment by mg638** [comment]
If it's available, what should I do? It's okay to modify the plug-in.

**Comment by mg638** [comment]
@Balint-H 

hello. The elasticity plugin error was previously resolved. However, when I play, the following error message appears. How do I resolve this?

IOException: Error loading the model: XML Error: Schema violation: unrecognized attribute: 'sensornoise'

Element 'flag', line 1

**Comment by Balint-H** [comment]
Hello, this was an issue for a while for version 3.1.4 and 3.1.5 of the Unity plugin, but is fixed for 3.1.6. Could you please test with that? Thanks!

**Comment by kevinzakka** [comment]
Going to close the issue assuming that upgrading fixes the problem. If that is not the case, please re-open the issue.
