### ISSUE TITLE
Saving the xml with updates after mj_step

### ISSUE THREAD

**Issue by budzianowski** [google-deepmind/mujoco#1719]
**Is your feature request related to a problem? Please describe.**
Hey, I'm running the following code:

> import mujoco
> path = "model.xml"
> mj_model = mujoco.MjModel.from_xml_path(path)
> mj_model.opt.solver = mujoco.mjtSolver.mjSOL_CG
> mj_model.opt.iterations = 6
> data = mujoco.MjData(mj_model)
> data.qpos = new_qpos  # some new position
> mujoco.mj_step(mj_model, data)
> mujoco.mj_saveLastXML("new_model.xml", mj_model)

**Describe the solution you'd like**
I would like to save the new xml with updated body positions (and geoms) after the mj_step.

**Describe alternatives you've considered**
I'm not sure if there is anything smarter right now than to log all the bodies and geoms pos and quat and save it to the xml file?

**Comment by yuvaltassa** [comment]
That's what keyframes are for, but we should really expose an API function to do what simulate does [here](https://github.com/google-deepmind/mujoco/blob/7a06bcfdaf109ef09a77f80a9ebacad11662bd1f/simulate/simulate.cc#L1982)...

To be clear this will not change the base configuration, but it will save the state to the model and then after `mk_saveXML` it will appear in the XML and you'll be able to reload it.
