### ISSUE TITLE
[MJX] Difference between training model in MJX and Evaluating in Mujoco with Height Map Activated

### ISSUE THREAD

**Issue by AlexS28** [google-deepmind/mujoco#1730]
Hi,

I wanted to ask if there was any analysis (or attempt) made to evaluate the model trained in MJX (specifically with the height map) and evaluate this trained model in Mujoco (with the height map applied in Mujoco as well)? I am mostly asking because I was successfully able to train our Biped robot on the height map in MJX, but this policy did not work in the regular Mujoco. However, a flat terrain in regular Mujoco did work. So I just want to double check if this is an error on my end, or if the height map in MJX vs Mujoco have some difference? Maybe on way to check if someone already has done is to see if the barkour example in MJX trained on the height map works in regular Mujoco with the height map.

Thanks,
Sincerely,
Alex

**Comment by btaba** [comment]
Hi @AlexS28 , I have not tried this personally. The contacts between heightmaps in MJX vs MuJoCo are not equivalent. In MJX we use the separating axis test with one-shot contact manifolds (4 points), and cull these to a max of 4 points. In MuJoCo, we use MPR and can use up to 50 contact points FWIU. In the MJX [tutorial](https://colab.research.google.com/github/google-deepmind/mujoco/blob/main/mjx/tutorial.ipynb), we do show transfer for the humanoid between MJX and MuJoCo, but the collision detection in that case is equivalent (capsules, planes, spheres). Hope that helps

**Comment by AlexS28** [comment]
I see, thanks for the answer, I guess in that case it make sense why the behavior could be different between the two then.

**Comment by i1Cps** [comment]
Good Afternoon, I understand the explanation as to why this happens but what is the proper way to solve this issue? The issue being, MuJoCo and MJX generate heightmap contacts differently, therefore when calling `mjx_data = mjx.put_data(m, d)`, where m contains heightmap contacts, 

the following error is thrown:

```ValueError: d.ncon too high, d.ncon = 18, model = 16```

This is thrown from the following contact block 
```
  <contact>
    <pair geom1="floor" geom2="humanoid_left_foot" condim="3"/>
    <pair geom1="floor" geom2="humanoid_right_foot" condim="3"/>

    <pair geom1="floor" geom2="humanoid_left_shin" condim="3"/>
    <pair geom1="floor" geom2="humanoid_right_shin" condim="3"/>
  </contact>
```

What I have tried:

` <size nconmax="16"/>` (The old solution, which I believe is deprecated)
```
  <custom>
    <numeric data="4" name="max_contact_points"/>
    <numeric data="4" name="max_geom_pairs"/>
  </custom>
```
