### ISSUE TITLE
Mujoco Viewer Setup as in 2.1.0

### ISSUE THREAD

**Issue by girishsmurthyIntel** [google-deepmind/mujoco#1731]
Dear Team,
         We are working on migration from mujoco2.1 to mujoco3.1. I have referred the https://mujoco.readthedocs.io/en/latest/python.html#migration-from-mujoco-py. 

I am unable to understand the set up of the mujoco viewer. I need to get the window which has no GUI tabs for the simulation set up, but just the simulation window with statistics (fps, steptime etc). Can you kindly help me in this regard?

**Comment by yuvaltassa** [comment]
See last bullet in [this section](https://mujoco.readthedocs.io/en/latest/python.html#passive-viewer)

**Comment by girishsmurthyIntel** [comment]
Thank you.
