### ISSUE TITLE
Getting/Setting the state of the simulation

### ISSUE THREAD

**Issue by girishsmurthyIntel** [google-deepmind/mujoco#1735]
Dear Team,

       To replace the get_state & set_state APIs in mujoco 2,  mujoco 3.0 would use the mj_getState or the mj_setState APIs. 
I need help to understand what the third argument of  mj_getState or the mj_setState APIs i.e, **"mjtNum* state"** refers to? Also what should I initialize this argument at the beginning, while running a getState? Any references will be helpful.

Rgds,
Girish

**Comment by yuvaltassa** [comment]
I seem to remember you use Python? 

Anyway, please read the documentation [here](https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mj-statesize) and the test code [here](https://github.com/google-deepmind/mujoco/blob/28e5ba2d293c151d6fe8482ec870ce14513ed260/python/mujoco/bindings_test.py#L712) and or [here](https://github.com/google-deepmind/mujoco/blob/28e5ba2d293c151d6fe8482ec870ce14513ed260/test/engine/engine_support_test.cc#L480).
