### ISSUE TITLE
Equivalent of the get_site_xvelp() in Mujoco 3.1

### ISSUE THREAD

**Issue by girishsmurthyIntel** [google-deepmind/mujoco#1737]
Dear Team,

        Earlier in Mujoco2.x there was an usage of self.conveyor.sim.data.get_site_xvelp(f"object{object_id}") * self._dt to determine the positional velocity. Can you please help me on how to migrate this in 3.1?

**Comment by yuvaltassa** [comment]
https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mj-objectvelocity
