### ISSUE TITLE
Query on viewer/render/read_pixels API migration to Mujoco 3.x

### ISSUE THREAD

**Issue by girishsmurthyIntel** [google-deepmind/mujoco#1738]
Dear Team,

        I was unable to understand how to map mujoco2.x APIs **mujoco_py.MjViewerBasic**, corresponding **render and read_pixels** APIs in mujoco 3.0. Request your kind help on this.

**Comment by girishsmurthyIntel** [comment]
I used the API mujoco.viewer.launch_passive(self.conveyor.model, self.conveyor.data, show_left_ui= False, show_right_ui= False), but I get the error:
ERROR: mjv_makeSceneState: mjvSceneState buffer is not fully used

Press Enter to exit ..

Please advise.

**Comment by girishsmurthyIntel** [comment]
@yuvaltassa Can you kindly help here.

**Comment by yuvaltassa** [comment]
We cannot help you without a minimal reproducible example.

**Comment by girishsmurthyIntel** [comment]
Hi @yuvaltassa, Please find the model attached. The main xml file is warehouse_v2.xml
The segments of the code I have used are 
        self.model = mujoco.MjModel.from_xml_path(fullpath) # fullpath is the path for the file warehouse_v2.xml
        self.data = mujoco.MjData(self.model)
        mujoco.mj_forward(self.model, self.data)
        mujoco.viewer.launch_passive(self.model, self.data, show_left_ui= False, show_right_ui= False)
[assets.zip](https://github.com/user-attachments/files/15890240/assets.zip)

**Comment by girishsmurthyIntel** [comment]
Dear @yuvaltassa, Can you kindly check this xml file and help us know of this error.

**Comment by girishsmurthyIntel** [comment]
Hi @yuvaltassa , I figured out that if I remove the <size njmax="10000" nconmax="10000"></size> from the xml file, the error doesn't occur. Kindly provide your insights.

**Comment by yuvaltassa** [comment]
I don't know what it means to "remove the from". No insights from me.

**Comment by girishsmurthyIntel** [comment]
I am so sorry, the comment isn't rightly uploaded.
I figured out that if I remove the line below in the warehouse_v2.xml file, the error doesn't occur. kindly provide your insights
**<size njmax="10000" nconmax="10000"></size>**

**Comment by yuvaltassa** [comment]
We have documentation, please read it. Specifically take note of the word **legacy**


https://mujoco.readthedocs.io/en/latest/modeling.html#csize

https://mujoco.readthedocs.io/en/latest/XMLreference.html#size-memory

**Comment by sIHURs** [comment]
> Hi @yuvaltassa , I am so sorry, the comment isn't rightly uploaded. I figured out that if I remove the line below in the warehouse_v2.xml file, the error doesn't occur. kindly provide your insights **njmax="10000" nconmax="10000"**

Hi, I would like to ask if a cause has been found for this issue, I have the same problem. My XML file runs fine in the simulator, but I encounter this error when using the Python API: ERROR: mjv_makeSceneState: mjvSceneState buffer is not fully used.
