### ISSUE TITLE
How to Fix Position and Orientation Error

### ISSUE THREAD

**Issue by binbinbai** [google-deepmind/mujoco#1755]
Hello,

I am using MuJoCo 210 to control a robotic hand by setting the target position as the control signal. However, I have noticed a consistent position and orientation error between the commanded and the actual positions.

Would it be better to upgrade to a newer version of MuJoCo or adjust the motor gains to reduce this error?

Thank you for your assistance!

**Comment by yuvaltassa** [comment]
I'm assuming you're using position actuators. There will always be an error, position actuators are springs and the control signal sets the setpoint of the spring. When the target is achieved the force is 0 by definition, so you'll never get 0 error. Increasing the gains will reduce the error but never take it to 0.

That said, upgrading to the latest version is probably a good idea regardless.

**Comment by binbinbai** [comment]
Thank you so much! @yuvaltassa
