### ISSUE TITLE
Editing size of geom from Python code

### ISSUE THREAD

**Issue by Servo97** [google-deepmind/mujoco#1756]
Hi,

I'm a grad student and I'm trying to use MuJoCo for simulating a mesh of an object. 

I'm looking for some help with editing the size of the mesh in python code for curriculum learning. Basically my curriculum changes the size of the object based on difficulty, and I want to scale the size of the object dynamically instead of restarting the entire simulation with changed values in the xml file of the scene. 

Here is a model which explains my question:

I'm trying to change the geom size using this code. The commented code is an alternative way I tried. 
This is the xml file (the franka_emika_panda is from the Mujoco Menagerie repo):

```
<mujoco model="peg_insertion">
	<include file="franka_emika_panda/scene.xml" />
	<asset>
		<mesh name="peg_diamond" file="meshes/diamond.obj" />
		<mesh name="hole_diamond" file="meshes/diamond_mold.obj" />
	</asset>
	<worldbody>
		<body name="peg" pos="0.5 0.3 0.02" euler="1.57079 0 0">
			<geom name="peg_diamond" pos="0 0 0" type="mesh" mesh="peg_diamond" />
			<joint name="peg_joint" type="free" />
		</body>
		<body name="hole" pos="0.5 0 0.025" euler="1.57079 0 0">
			<geom name="hole_diamond" pos="0 0 0" type="mesh" mesh="hole_diamond" />
		</body>
	</worldbody>
</mujoco>
```

```
        for i in range(1000):
            if i%100 == 0:
                # self.model.geom('peg_diamond').size = 1.1*self.model.geom('peg_diamond').size
                geom_id = self.model.geom("peg_diamond").id
                self.model.geom_size[geom_id] = 1.2*self.model.geom_size[geom_id]
                print(self.model.geom('peg_diamond').size)

                self.model.geom('peg_diamond').rgba[:3] = np.random.rand(3)
                mujoco.mj_forward(self.model, self.data)
            mujoco.mj_step(self.model, self.data)
```

Here is a screenshot / video, showing that the color changes as expected, but the size remains constant:
https://drive.google.com/file/d/12WDQdHTpZBMXLt170fX1kFMBj4LtTIqQ/view?usp=sharing

Can someone please help me figure out how do I go about it? 

Thanks!

**Comment by yuvaltassa** [comment]
You can't do that, you need to recompile. There are a bunch of compiled quantities (bounding volumes etc.) that rely on this being fixed at run-time.
