### ISSUE TITLE
Unexpected Behavior for Deformable Objects

### ISSUE THREAD

**Issue by hea467** [google-deepmind/mujoco#1773]
Hi,

I'm a student and I'm trying to use MuJoCo for simulating origami / deformable robotic structures.

I'm looking for some help with understanding with the particular behavior of a deformable object. I've attached the code and a video below. I am expecting the vertices v2 and v5 to drop down like it does in the video due to their mass, and v0, v1 are fixed like it does in the video. However, I'm expecting v3 and v4 to move stick to v0 and v1 and stay put. However, right now it seems like it is passing through the object itself and slowly damping the movement. Is this expected behavior or did I make a mistake?  

Here is a model which explains my question:

<details>
 

```XML
<mujoco model="valley_fold">
	<extension>
		<plugin plugin="mujoco.elasticity.solid" />
	</extension>
	<include file="scene.xml" />
	<worldbody>
		<body name="v0" pos="0 0 1.005">
			<inertial pos="0 0 0" mass="1" diaginertia="1.66667e-05 1.66667e-05 1.66667e-05" />
		</body>
		<body name="v1" pos="2 0 1.005">
			<inertial pos="0 0 0" mass="1" diaginertia="1.66667e-05 1.66667e-05 1.66667e-05" />
		</body>
		<body name="v2" pos="2 1 1.005">
			<inertial pos="0 0 0" mass="1" diaginertia="1.66667e-05 1.66667e-05 1.66667e-05" />
			<joint name="v2_j2" pos="0 0 0" axis="0 1 0" type="slide" />
			<joint name="v2_j3" pos="0 0 0" axis="0 0 1" type="slide" />
		</body>
		<body name="v3" pos="2 2 1.005">
			<inertial pos="0 0 0" mass="1" diaginertia="1.66667e-05 1.66667e-05 1.66667e-05" />
			<joint name="v3_j2" pos="0 0 0" axis="0 1 0" type="slide" />
		</body>
		<body name="v4" pos="0 2 1.005">
			<inertial pos="0 0 0" mass="1" diaginertia="1.66667e-05 1.66667e-05 1.66667e-05" />
			<joint name="v4_j2" pos="0 0 0" axis="0 1 0" type="slide" />
		</body>
		<body name="v5" pos="0 1 1.005">
			<inertial pos="0 0 0" mass="1" diaginertia="1.66667e-05 1.66667e-05 1.66667e-05" />
			<joint name="v5_j2" pos="0 0 0" axis="0 1 0" type="slide" />
			<joint name="v5_j3" pos="0 0 0" axis="0 0 1" type="slide" />
		</body>
	</worldbody>
	<deformable>
		<flex name="body1" dim="2" body="v0 v1 v2 v5" vertex="0 0 0 0 0 0 0 0 0 0 0 0"
			element="0 1 2 2 3 0" rgba="0 0 1 0.9" />
		<flex name="body2" dim="2" body="v2 v3 v4 v5" vertex="0 0 0 0 0 0 0 0 0 0 0 0"
			element="0 1 2 2 3 0" rgba="0 0 1 0.9" />
	</deformable>
	<equality>
		<flex flex="body1" />
		<flex flex="body2" />
	</equality>
</mujoco>
```

</details>

Here is a screenshot / video, illustrating my question:

https://github.com/google-deepmind/mujoco/assets/79684082/3daf6f44-024f-4acc-a232-b9e639c937d0

[https://drive.google.com/file/d/1xrn9LetCplEDPA_rsP5MQIi7cV3_gtY_/view?usp=sharing](url)

**Comment by quagla** [comment]
Try https://mujoco.readthedocs.io/en/latest/XMLreference.html#flex-contact-selfcollide
