### ISSUE TITLE
Spin and Magnus force

### ISSUE THREAD

**Issue by KieDani** [google-deepmind/mujoco#1780]
Hi,

I'm a researcher and I'm trying to use MuJoCo for the physics simulation of a sport's ball (e.g. in soccer or basketball).

I want to take into account that the Magnus force is acting on a spinning ball and I would like to know how to incorporate this effect in the MuJoCo simulation.
At the moment I do a simple simulation defined by this XML file:
```XML
<mujoco>
      <worldbody>
        <!-- Define the ball -->
        <body pos="5.425 0 1" name="ball">
            <joint type="free" name="ball_joint"/>
            <geom type="sphere" name="ball_geom" size="0.11" mass="0.43" pos="0 0 0" />
        </body>
        <!-- Define the field  -->
        <geom type="plane" name="field" size="200 200 0.1" pos="0 0 0" solref="-1000 0"/>
      </worldbody>
      <!-- Enable gravity for the simulation -->
      <option gravity="0 0 -9.81" integrator="RK4" timestep="0.002" density="1.2" viscosity="0.00002" />
    </mujoco>
```
By setting the density and viscosity I hoped to incorporate the Magnus effect into the simulation. However, according to the [docs](https://mujoco.readthedocs.io/en/latest/computation/fluid.html), it seems like density and viscosity only affect the drag (btw: this way it is also not possible to set some constants for different surfaces, since some surfaces cause a larger force) and no Magnus effect is introduced. Is this correct?
So do I instead have to use _fluidshape=ellipsoid_ in order to describe a spinning ball correctly?

**Comment by yuvaltassa** [comment]
| So do I instead have to use fluidshape=ellipsoid in order to describe a spinning ball correctly?

Yes
