### ISSUE TITLE
How to create a abitrary object without penetration for in-hand manipulation task

### ISSUE THREAD

**Issue by QiyangYan** [google-deepmind/mujoco#1791]
Hi,

I'm a student and I'm trying to use MuJoCo for a research project.

I'm looking for some help with creating arbitrary objects for in-hand manipulation tasks.

Currently, the object will be penetrated by the finger and resulting in the oscillation of the finger joint.

<body name="octagon">
          <joint name="joint:object" type="free" damping="0.01"></joint>
          <geom mesh="octagon" rgba="1.5 1.5 1.5 1" class="collision" friction="1" mass="0.02" condim="4" contype="6" conaffinity="5"/>
 </body>
 
 When I use the regular geom type like box and cylinder to create the object, it doesn't show this problem. I'm wondering what's the proper way to create arbitrary objects

**Comment by Balint-H** [comment]
Collisions with meshes are in general less stable than with collision primitives. You can adjust the [solver parameters](https://mujoco.readthedocs.io/en/latest/modeling.html#csolver) of the mesh geom, particularly the `solref` parameters time constant can be decreased for less compliant contacts. You can also enable the MultiCCD flag for more stable contact behaviour with meshes at additional computational costs.
