### ISSUE TITLE
Where does the `center` of `geom_aabb` point at?

### ISSUE THREAD

**Issue by barikata1984** [google-deepmind/mujoco#1792]
Hi, everyone,

I am trying to retrieve the axis-aligned bounding box (aabb) of an assembly. I modelled stacked blocked as 
```xml
<body name="object">
    <geom name="top" type="box" density="500" size=".16 .32 .32" pos=".0 .0 .32"/>
    <geom name="bottom" type="box" density="2000" size=".16 .32 .32" pos=".0 .0 -.32"/>
</body>

```
and shown in the attached picture (Do not care about the placement. The bottom half was placed underground intentionally):
<img width="320" alt="Screenshot from 2024-07-07 17-10-32" src="https://github.com/google-deepmind/mujoco/assets/7353608/0bde798c-c034-4ab5-b56d-c80434c86927">
And then, I checked the value of `geom_aabb` which returns `(center, size)`. What I expected was 
```
m.geom_aabb=array([[0.  , 0.  , 0.32  , 0.16, 0.32, 0.32],
                   [0.  , 0.  , -0.32  , 0.16, 0.32, 0.32]])
```
because the center of the upper half is above the ground, and the center of the bottom half is beneath the cubicleground. But the result I got was:
```
m.geom_aabb=array([[0.  , 0.  , 0.  , 0.16, 0.32, 0.32],
                   [0.  , 0.  , 0.  , 0.16, 0.32, 0.32]])
```
So, both `center`s look specifying the same location. Now, I am confused about where the `center` is for each `geom`. Does anybody tell me where it is?

Plus, assuming that the origin of the coordinate system describing `center` is the same to the position of each geom relative to the body, I coded a procedure like
```python
for pos, aabb in zip(m.geom_pos, m.geom_aabb):
    print(f"{np.split(aabb, 3)=}")
    local_center, xyz_scale = np.split(aabb, 2)
    for i in (-1, 1):
        for j in (-1, 1):
            for k in (-1, 1):
                point = xyz_scale * np.array([i, j, k]) + pos + local_center

                if max_point is None or np.all(max_point <= point):
                    max_point = point

                if min_point is None or np.all(point <= min_point):
                    min_point = point

if max_point is None or min_point is None:
    raise TypeError("'max_point' or 'min_point' is None.")

aabb_scale = np.abs(max_point - min_point).max() / 2  # cube, not cuboid

print(f"{aabb_scale=}")
```
It works nicely for the stacked blocks above but is there a better way to achieve it?

Thanks in advance

**Comment by quagla** [comment]
Hi, geom_aabb is in the geom frame. So the center is at data->geom_xpos in Cartesian coordinates. Hope that helps.
