### ISSUE TITLE
Mujoco MJX Rangefinder Sensor support

### ISSUE THREAD

**Issue by DarioRepoRuler** [google-deepmind/mujoco#1821]
Hi,

I'm a student working with MuJoCo MJX. I know that MJX doesn't support sensors yet, but I saw on the [MuJoCo](https://mujoco.readthedocs.io/en/stable/mjx.html) website that many sensors (except user and plugin) are being developed.

I've added rangefinder sensors to my ".xml" file and would like to know when this feature will be available. Is there any way to access sensor data now?
![Screenshot from 2024-07-17 16-30-03](https://github.com/user-attachments/assets/dc7f6f80-08bc-43ae-8dd1-70752e0833dc)

Thank you!

**Comment by erikfrey** [comment]
Hello - MJX rangefinder was implemented in 51733c2a8ac081ed7c44d8e96bb0f8d6d30059f0 and will be part of the next release.
