### ISSUE TITLE
`mjs_firstElement` has a segmentation fault if the spec does not have the element

### ISSUE THREAD

**Issue by JewelryForge** [google-deepmind/mujoco#1824]
Hi,
  I think the proper behavior of `mjs_firstElement` when the spec does not have the element is to return a `nullptr`. Now `mjs_firstElement` (exactly `mjCModel::NextObject`) assumes that the element vectors (e.g. `actuators_`) are not empty and directly accesses the first item.
https://github.com/google-deepmind/mujoco/blob/dd9dd295badd9d09184d9c3c0e7d9641c85dec6a/src/user/user_model.cc#L716
  I think it's better that the function first checks that the vector is not empty and returns a `nullptr` if it's empty.
  The following code can reproduce this issue:
```c++
  auto *spec = mj_makeSpec();
  mjs_firstElement(spec, mjtObj::mjOBJ_HFIELD);
```
  Thank you for your help!

**Comment by JewelryForge** [comment]
The same problem also exists in `mjs_firstChild` (i.e. `mjCBody::NextChild`)
In addition, it seems that there are no tests about `mjs_firstElement` currently.

**Comment by yuvaltassa** [comment]
Thanks for reporting this!

Please help us find additional issues :slightly_smiling_face:
