### ISSUE TITLE
MjSpec requires length 3 floats for size assignment regardless of geom type

### ISSUE THREAD

**Issue by kevinzakka** [google-deepmind/mujoco#1826]
As the title suggests:

```python
import mujoco

spec = mujoco.MjSpec()
geom = spec.worldbody.add_geom()
geom.type = mujoco.mjtGeom.mjGEOM_SPHERE
geom.size = (.01,)
```

results in the following error message:
```bash
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (arg0: mujoco._specs.MjsGeom, arg1: numpy.ndarray[numpy.float64[3, 1]]) -> None

Invoked with: <mujoco._specs.MjsGeom object at 0x7d575c1df3f0>, (0.01,)
```

even though the number of required parameters should be 1 in this case.

This however works:

```python
import mujoco

spec = mujoco.MjSpec()
geom = spec.worldbody.add_geom()
geom.type = mujoco.mjtGeom.mjGEOM_SPHERE
geom.size[0] = .01
```

I think it would be nice to support direct assignment.

**Comment by yuvaltassa** [comment]
Making the way one attribute works (size) depend on the value of another attribute (type) would be a serious headache. I don't think it'd be worth the effort for such a small convenience. And like you say, you can always set the size[0] post-hoc.
