### ISSUE TITLE
Regarding the version issue of MuJoCo？

### ISSUE THREAD

**Issue by cuiliyuan121** [google-deepmind/mujoco#1829]
When I try to use MuJoCo versions less than 3.0, I always encounter the error: "Error: faces of mesh 'xxx' have inconsistent orientation. Please check the faces containing the vertices X and Y. Object name = xxx. id = x, line = y". I tried upgrading the version as suggested by [#1551](https://github.com/google-deepmind/mujoco/issues/1551) but then encountered: "'MjModel' object has no attribute 'bvh_geomid'". According to [#3](https://github.com/elicassion/sugarl/issues/3) explanation, versions below 3.0 should suffice. How can I resolve this?

**Comment by Cryon233** [comment]
II have also encountered this problem, may I ask what is the reason and how it was finally solved?
