### ISSUE TITLE
Performance differs with added disabled actuators/groups 

### ISSUE THREAD

**Issue by eufrizz** [google-deepmind/mujoco#1838]
Hi, I've just started testing using actuatorgroupdisable to allow my model to switch between position and intvelocity control. However, I've noticed that it changes the performance of the model.

1. With just one group of actuators, the model behaves as expected and gets to the setpoint nicely.

2. If I add a second group of actuators to the XML (e.g. velocity control), and then deactivate them, I now find that the model overshoots the setpoint a bit before settling. I would expect performance to be the same, as the only enabled actuators are exactly the same as in the first example, same gain parameters etc. I do NOT have both groups of actuators enabled at the same time, and I disable them under the Physics panel as well as under the Group Activation panel (Group Activation panel makes no difference).

3. Interestingly, this behaviour goes away when I decrease the timestep from 0.002 to 0.001 - the model performs like the first example again.

I don't fully understand it but seems like the extra unused actuators are perhaps slowing down/changing the simulation calculations in some way. Is this expected behaviour?

I can provide a minimal example if you'd like.

**Comment by yuvaltassa** [comment]
Yes please, a minimal example would be much appreciated.

**Comment by eufrizz** [comment]
I've just been comparing by loading the models directly into the GUI and playing with the controls. Here are a couple of videos so you can see the (subtle) overshoot when it changes position. Model files attached below.

One actuator group (baseline):
![one_actuator_group](https://github.com/user-attachments/assets/b5cb550a-46f9-4f31-b1e7-a5c745d5c89e)

Two actuator groups:
![two_actuator_groups](https://github.com/user-attachments/assets/2011e3c1-1137-4d8d-b6ab-a4a3aa728d7b)

[mujoco_actuator_test.zip](https://github.com/user-attachments/files/16355243/mujoco_actuator_test.zip)

**Comment by yuvaltassa** [comment]
This is a bug! 

Thanks, will fix shortly.
