### ISSUE TITLE
Depth rendering incorrect values

### ISSUE THREAD

**Issue by giorgionicola** [google-deepmind/mujoco#1871]
Hi,
I am trying to simulate a depth camera and I am using the renderer. However the values of the depth are clearly wrong.
Here is the minimal XML and minimal code.

<details>
  <summary>minimal XML</summary>

```XML
<mujoco>
	<option gravity="0 0 -9.81"/>
	<visual>
  		<global offheight="512"/>
	</visual>

	<worldbody>
		<body name="end_effector" mocap="true" pos="0 0 0">
			<body name="camera" pos="0 0 0.5" euler="0 0 0">
				<camera name="azure_kinect" mode="fixed" pos="0 0 0" fovy="120" euler="0 0 0"/>
			</body>
		</body>
	         <body name="plate" pos="0 0 -0.01">
		        <geom type="box" size="0.5 0.5 0.01"/>
	         </body>

	</worldbody>
```
</details>
<details>
<summary>minimal Code</summary>

```Python


import mujoco
import mujoco.viewer
import matplotlib.pyplot as plt
import numpy as np

model = mujoco.MjModel.from_xml_path('tmp_tessuto.xml')
data = mujoco.MjData(model)
viewer = mujoco.viewer.launch_passive(model, data)
while True:
    mujoco.mj_step(model, data)
    viewer.sync()

    with mujoco.Renderer(model, 512, 512) as renderer:
        mujoco.mj_step(model, data)

        renderer.enable_depth_rendering()

        renderer.update_scene(data, camera='azure_kinect')
        depth_frame = renderer.render()
        depth_frame[depth_frame > 1] = np.nan

        renderer.disable_depth_rendering()

    _, ax = plt.subplots(ncols=2)
    ax[0].imshow(depth_frame)
    ax[1].plot(depth_frame[:, 256])
    plt.show()
```
</details>

here is the simulated scene
![mujoco_viewer depth](https://github.com/user-attachments/assets/cde6d1fa-2a29-4ad6-acad-19aeb5026035)

The output depth is the left image and the right image is a plot a the depth value of the middle section.
![wrong depth](https://github.com/user-attachments/assets/a1768d4e-edb3-4d7d-b290-b496ae9604c6)

The depth value is constant at 0.5, which is equal to the shortest distance between the object and the camera.
The depth value should change across the object given the size of it

**Comment by yuvaltassa** [comment]
This looks right. What makes you say this is "clearly wrong"?

You might be misunderstanding what "depth" means, in this context. It does not mean "distance from the camera position". It means "distance from the camera **image plane**" or, equivalently, "dot product with the negative Z axis of the camera frame".

**Comment by giorgionicola** [comment]
You are right, depth in the robotics context is assumed as the camera->point distance rather than camera plane-> point.

For those who are interested here is the minimal code to convert  it into depth image with camera -> point distance using the intrinsic parameters of the camera

```Python
depth_plane = renderer.render()
i_indices, j_indices = np.meshgrid(np.arange(resolution[0]), np.arange(resolution[1]), indexing='ij')

x_camera = (i_indices - cx) * depth_plane / fx
y_camera = (j_indices - cy) * depth_plane / fy
depth = np.sqrt(z ** 2 + x_camera ** 2 + y_camera ** 2)
```
