### ISSUE TITLE
[Python MuJoCo 3.2] Load Failed when load 100 or more materials in xml

### ISSUE THREAD

**Issue by forworksmk** [google-deepmind/mujoco#1877]
Using MuJoCo version 3.1.6 in python, When I load my XML file, no error occurs.

However, after updating MuJoCo to version 3.2 and loading the same XML file, I encounter the following error:

`FatalError: Maximum number of materials is 100`

What can I do to avoid this error or maybe solve this error?

**Comment by yuvaltassa** [comment]
What is the XML file (and why do you have so many materials)?

**Comment by forworksmk** [comment]
Hello,

I have built a simulation environment for indoor spaces using an XML file, and it worked well with MuJoCo version 3.1.6. However, upon upgrading to version 3.2, I encountered an issue where the simulator indicates that the maximum number of materials has been exceeded.

In my environment, there are approximately 200 materials. My question is: Is there a way to exceed the max number of materials limit in MuJoCo 3.2, or are there any recommended approaches to handle this limitation?

Thank you for your assistance.

**Comment by nimrod-gileadi** [comment]
We'll increase the limit back to 1000 in the upcoming 3.2.1.

**Comment by nimrod-gileadi** [comment]
Unfortunately the commit just missed the cut for 3.2.1 and will be pushed in 3.2.2.

**Comment by nimrod-gileadi** [comment]
3.2.2 is now released and the issue should be fixed.
