### ISSUE TITLE
 get external force of object collision in mujoco

### ISSUE THREAD

**Issue by gaoning0109** [google-deepmind/mujoco#1892]
I want to get the total external force of object collision in mujoco
Here is  a function I wrote to get the resultant external force.

void print_body_external_forces(mjModel* model, mjData* data) {
    int nbody = model->nbody; 

    for (int i =1; i < nbody; i++) {
        // Get the external force for the current body
        const mjtNum* external_force = data->cfrc_ext + 6 * i;
        std::cout << "Body " << i << " external force (Fx, Fy, Fz): ("
            << external_force[0] << ", "
            << external_force[1] << ", "
            << external_force[2] << ") N"
            << std::endl;
        std::cout << "Body " << i << " external torque (Mx, My, Mz): ("
            << external_force[3] << ", "
            << external_force[4] << ", "
            << external_force[5] << ") N"
            << std::endl;
    }
}

This code doesn't seem right
![image](https://github.com/user-attachments/assets/0b5ef680-817f-4736-aab6-5115ea27df4a)

**Comment by yuvaltassa** [comment]
As documented [here](https://mujoco.readthedocs.io/en/latest/APIreference/APItypes.html#mjdata) rotations are before translations for this array.

```c
  // computed by mj_sensorAcc/mj_rnePostConstraint if needed; rotation:translation format
  mjtNum* cacc;              // com-based acceleration                           (nbody x 6)
  mjtNum* cfrc_int;          // com-based interaction force with parent          (nbody x 6)
  mjtNum* cfrc_ext;          // com-based external force on body                 (nbody x 6)
```
