### ISSUE TITLE
[MJX] How to keep action values ​​consistent in single episode?

### ISSUE THREAD

**Issue by ChanMook** [google-deepmind/mujoco#1916]
Hi,
I'm working on MuJoCo MJX.

I set the action value of MJX as the parameters to make torque. The action value(control parameter) changes at every step, causing problems in control.
I want to find optimal fixed action on single episode. how can i do?

**Comment by Balint-H** [comment]
My suspicion is that this could be fixed if you set the action_repeat field in your training to be equal to your episode length. Then the agent will make a single action at the start of the episode.

**Comment by Balint-H** [comment]
Alternatively, for fixed action policies you can consider non RL methods, like grid searching or Bayesian optimisation.
