### ISSUE TITLE
Initialization with the object already grasped

### ISSUE THREAD

**Issue by zichunxx** [google-deepmind/mujoco#1919]
Hi!  

I want to initialize a model with the object being grasped by the gripper so that the arm does not have to re-grasp each time when resetting the environment in reinforcement learning.

I have tried some methods that end up with the object falling off before it was grasped. Is it feasible to realize this? 

Thanks!

**Comment by Balint-H** [comment]
Have you tried to grasp the object, then saving `data->qpos`, then restore it as needed?
