### ISSUE TITLE
How do I input to joints? qpos is'nt working

### ISSUE THREAD

**Issue by maheshr24** [google-deepmind/mujoco#1920]
def ik_solver(model, data):
    target_position = np.array([0.4, 0.3, 0.4])  # Target position for end-effector
    position_Q = data.site_xpos[0]
    jacp = np.zeros((3, model.nv))

    # Calculating the Jacobian matrix
    mj.mj_jacSite(model, data, jacp, None, 0)  # 0 corresponds to the site ID for end-effector
    J = jacp[:3, :7]  # Select only the first 3 rows and the first 7 columns

    # Computing inverse Jacobian
    Jinv = np.linalg.pinv(J)  # Use pseudo-inverse for better numerical stability
    x = np.array([position_Q[0], position_Q[1], position_Q[2]])
    dx = target_position - x  # Calculate the error in position

    dq = Jinv @ dx  # Calculate the change in joint angles

    # Update joint angles
    data.qpos[:7] += dq[:7]  # Update only the first 7 joints

    # Forward dynamics
    mj.mj_forward(model, data)

Here when my input is with qpos the model does'nt respond I think the input should be with ctrl's. How do I convert the qpos to ctrl for input

**Comment by kevinzakka** [comment]
Two comments:

1. You need to integrate the solution `dq` for a small time step and then set the resulting joint position in qpos.
2. Your code is not simulating any of the actuators, just teleporting the joints to whatever dq is. You should set `data.ctrl` as you alluded to and call `mj_step` instead.

See [mjctrl](https://github.com/kevinzakka/mjctrl/blob/main/diffik.py) for an example of how to do this.
