### ISSUE TITLE
Simulate Tactile Sensor Arrays with Touch Grid Plugin

### ISSUE THREAD

**Issue by Director-of-G** [google-deepmind/mujoco#1922]
Hi,

I'm simulating tactile sensor arrays (e.g., uSkin) using the `touch_grid` plugin, attached to each knuckle of the Shadow Hand. However, due to the collision detection between rigid bodies not producing multiple contact points, often only one `touch_grid` sensor outputs a non-zero value (e.g., the small white block between the thumb tip and a red object).

![image](https://github.com/user-attachments/assets/1eaa2a29-97b4-4a39-8aea-de35a8dadd31)

This is unexpected since real tactile sensor arrays typically show non-zero readings across multiple taxels.

One potential solution might be decomposing the object into sub-meshes, similar to how the `touch_grid` demo seems to work.

![image](https://github.com/user-attachments/assets/938501f9-4757-42c0-9ad1-4813369fe562)

I am not sure if it will work, any suggestions?

**Comment by LeiHanyue** [comment]
How did you deal with that problem later?

**Comment by dt1729** [comment]
Having same observation when I'm trying to work with these sensors on a bot, did you ever find a different sensor or is this the limitation of GJK/MPR? Did you move to Issac Sim or MJWarp to get around this issue? Flex contacts with Touch sensors were able to solve this but super slow on my Ryzen 7 CPU only, not sure how to proceed here honestly.  @yuvaltassa some comments are appreciated here.
