### ISSUE TITLE
geom_quat stops working after version 3.2.2

### ISSUE THREAD

**Issue by omarrayyann** [google-deepmind/mujoco#2071]
### Intro

I am an undergrad at NYU Abu Dhabi, and I'm using MuJoCo for some projects.

### My setup

Version: 3.2.2 vs 3.2.3
OS: Error occurs on both Mac and Ubuntu (at least)

### What's happening? What did you expect?

geom_quat (and I believe other _quats) do not work after updating from 3.2.2 to 3.2.3. I added a simple example to reproduce error. Try running it in both mujoco versions.

### Minimal model for reproduction

Try running the following main.py and scene.xml using both MuJoCo versions (3.2.2 and 3.2.3)

Main.py

```
import mujoco
import mujoco.viewer
import numpy as np

model = mujoco.MjModel.from_xml_path('scene.xml')
data = mujoco.MjData(model)
site_id =  mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_SITE, "target")

with mujoco.viewer.launch_passive(model,data,show_left_ui=False,show_right_ui=False) as viewer:
        while viewer.is_running():
            
            model.site_quat[site_id] = np.random.rand(4)

            mujoco.mj_step(model, data)
            viewer.sync()         
```

scene.xml

```
<?xml version="1.0" ?>
<mujoco model="iiwa14_scene">
  

    <statistic center="0.2 0 0.2" extent="1.0"/>

    <visual>
        <headlight diffuse="0.3 0.3 0.3" ambient="0.2 0.2 0.2" specular="0 0 0"/>
        <rgba haze="0.15 0.25 0.35 1"/>
        <global azimuth="-120" elevation="-20"  offwidth="1280" offheight="720"/>
        <quality shadowsize="0"/>
    </visual>

    <asset>
        <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="512" height="3072"/>
        <texture type="2d" name="groundplane" builtin="checker" mark="edge" rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3"
          markrgb="0.8 0.8 0.8" width="300" height="300"/>
        <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5" reflectance="0.2"/>

            <texture type="2d" name="floor_texture" builtin="checker" mark="edge" rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3"
          markrgb="0.8 0.8 0.8" width="300" height="300"/>

        <material name="floor_material" texture="floor_texture" texuniform="true" texrepeat="5 5" reflectance="0.2"/>

    </asset>

    <worldbody>


        <light pos="0 0 4.5" dir="0 0 -1" directional="true"/>
         <light pos="0 4.5 0.6" dir="0 -1 0" directional="true"/>
        <light pos="0 -4.5 0.6" dir="0 1 0" directional="true"/>

            <site name="target" type="box" pos="0.3 0.01 0.05" size="0.05" rgba="1 0 0 1" />


            <geom name="floor" size="1 1 0.05" type="plane" material="floor_material"/>

  
    </worldbody>
</mujoco>
```

**Comment by yuvaltassa** [comment]
This WIA. After the introduction of [mjtSameFrame](https://mujoco.readthedocs.io/en/latest/APIreference/APItypes.html#mjtsameframe) (item 10 in the 3.2.3 changelog), if the quat is (1, 0, 0, 0) at compile time then mj_kinematics will avoid computing the rotation. This is a valuable optimization.

Your options are:
1. Set `mjModel.xxx_sameframe[i]` to 0, and then your code will work.
2. (recommended) Stop modifying the `mjModel` and use procedural modification and recompilation using [`mjSpec`](https://mujoco.readthedocs.io/en/latest/programming/modeledit.html). This is the recommended long term solution. There is now no good reason to modify `mjModels`.
