### ISSUE TITLE
zero drag problem

### ISSUE THREAD

**Issue by kassasin** [google-deepmind/mujoco#2082]
I have a question. When I do a zero-force drag problem on a robotic arm, after compensating for gravity, although there is a slight error, the robotic arm can still be stationary due to the influence of static friction. How should I achieve this in mujoco? Because as far as I know there is no Coulomb friction in mujoco.

**Comment by kassasin** [comment]
frictionloss seems can't achieve this goal

**Comment by quagla** [comment]
https://mujoco.readthedocs.io/en/latest/XMLreference.html#option-noslip-iterations

**Comment by kassasin** [comment]
Thanks very much, it works. But is also leads to small motion,can i  eliminate it completely?

**Comment by quagla** [comment]
The best solution I can offer is playing with the parameters and see if you can improve the behavior. I'm not sure if you can really remove the motion completely since everything in MuJoCo has some small compliance by design.

**Comment by kassasin** [comment]
Thank you very much .
