### ISSUE TITLE
mujoco is unable to show models that have undergone approximately convex decomposition

### ISSUE THREAD

**Issue by walt666** [google-deepmind/mujoco#2086]
### Intro

Hi!

I am a graduate student , I use MuJoCo for my research on Robotic arm.

### My setup

mujoco-3.2.0 

### What's happening? What did you expect?

I'd like to simulate pouring objects into a bowl，same as #357.
So I used CoACD for approximately convex decomposition. After turning,  I import the obj format model into mujoco. The model is not fully displayed.How can I do this? Thanks!

### Steps for reproduction

![bowstl](https://github.com/user-attachments/assets/75a82710-29f8-475b-8b21-71a361e3f49f)
![bowobj](https://github.com/user-attachments/assets/82ac66e6-01b1-43f0-9d68-3b0794bc88a6)
![bowmujoco](https://github.com/user-attachments/assets/0cccb4a5-d027-4fca-b8d6-0873e7c20e7b)

### Minimal model for reproduction

If you encountered the issue in a complex model, please simplify it as much as possible (while still reproducing the issue).

<details>
<summary>minimal XML</summary>

```XML

<mujoco>
  <worldbody>
    <light pos="0 0 1"/>
    <geom type="sphere" size="1" rgba="1 0 0 1"/>
  </worldbody>
</mujoco>

```
</details>

### Code required for reproduction

```xml
<mujoco>
  <include file="scene1.xml"/>

  <worldbody>  
    <light diffuse=".5 .5 .5" pos="0 0 3" dir="0 0 -1"/>

    <body name="camB" pos="0 0 30" euler="0 0 90 ">
      <geom name="b" type="mesh" mesh="b" ></geom>
    </body>
    
  </worldbody>

  <asset>
    <mesh name="b" file="xmodel/bow.obj" scale="1 1 1"></mesh>  
  </asset>
  
</mujoco>
```

### Confirmations

- [X] I searched the [latest documentation](https://mujoco.readthedocs.io/en/latest/overview.html) thoroughly before posting.
- [X] I searched previous [Issues](https://github.com/google-deepmind/mujoco/issues) and [Discussions](https://github.com/google-deepmind/mujoco/discussions), I am certain this has not been raised before.

**Comment by quagla** [comment]
Does your obj contains multiple meshes? If so you need to use https://github.com/kevinzakka/obj2mjcf

**Comment by walt666** [comment]
> Does your obj contain multiple meshes? If so you need to use https://github.com/kevinzakka/obj2mjcf
Did I choose the right command？But nothing happened.
![mjcf](https://github.com/user-attachments/assets/99a96281-ccee-4705-af2f-e7819cf414ea)

**Comment by walt666** [comment]
I got this one. But loading failed again.
![mjcfbow](https://github.com/user-attachments/assets/7d5eb043-632e-496c-900f-ad959747f4a1)
![mujocobow2](https://github.com/user-attachments/assets/d9c01a69-2015-47c6-971b-6b68d3106433)

**Comment by quagla** [comment]
> > Does your obj contain multiple meshes? If so you need to use https://github.com/kevinzakka/obj2mjcf
> > Did I choose the right command？But nothing happened.
> > ![mjcf](https://private-user-images.githubusercontent.com/54744417/370357959-99a96281-ccee-4705-af2f-e7819cf414ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxOTcyODUsIm5iZiI6MTcyNzE5Njk4NSwicGF0aCI6Ii81NDc0NDQxNy8zNzAzNTc5NTktOTlhOTYyODEtY2NlZS00NzA1LWFmMmYtZTc4MTljZjQxNGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDE2NTYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMjA0YjY0OGExMmQ4OTk1N2MyZjgzYWNmMWQ0ZmY1NTJkMmYxMjhiNjQ4ZjkxYTI2MDI4NTdjZDg4OGY3ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._ZJhj_8kOCQc9YJ-1K20TPiZ9uRG6lC4wgTlY7WVNss)
> > @quagla

I can't tell from this if your OBJ has sub-meshes, which are not supported in MuJoCo. But you can split the file with obj2mjcf.

**Comment by walt666** [comment]
> > > Does your obj contain multiple meshes? If so you need to use https://github.com/kevinzakka/obj2mjcf
> > > Did I choose the right command？But nothing happened.
> > > ![mjcf](https://private-user-images.githubusercontent.com/54744417/370357959-99a96281-ccee-4705-af2f-e7819cf414ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxOTcyODUsIm5iZiI6MTcyNzE5Njk4NSwicGF0aCI6Ii81NDc0NDQxNy8zNzAzNTc5NTktOTlhOTYyODEtY2NlZS00NzA1LWFmMmYtZTc4MTljZjQxNGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDE2NTYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMjA0YjY0OGExMmQ4OTk1N2MyZjgzYWNmMWQ0ZmY1NTJkMmYxMjhiNjQ4ZjkxYTI2MDI4NTdjZDg4OGY3ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._ZJhj_8kOCQc9YJ-1K20TPiZ9uRG6lC4wgTlY7WVNss)
> > > @quagla
> 
> I can't tell from this if your OBJ has sub-meshes, which are not supported in MuJoCo. But you can split the file with obj2mjcf.

Thank you! I get it. Things work out perfectly！
