### ISSUE TITLE
Was the mujoco.org/forum completely deleted?

### ISSUE THREAD

**Issue by takeru1205** [google-deepmind/mujoco#21]
Hi there,
Very thankful for the announcements.

I'd like to ask about MuJoCo modeling in [mujoco forum](http://www.mujoco.org/forum/index.php).
But I got 404 response.

The forum is completely deleted?
Will the forum reopen? Or will be opened a page like a forum?

**Comment by saran-t** [comment]
MuJoCo's old forums will be available for read-only access on [Roboti LLC's website](https://roboti.us) shortly.

For new discussions, please use [our GitHub Discussions page](https://github.com/deepmind/mujoco/discussions).
