### ISSUE TITLE
pipeline_step is very slow for humanoid robot

### ISSUE THREAD

**Issue by gautica** [google-deepmind/mujoco#2104]
### The feature, motivation and pitch

Hi!

I am a researcher in legged robot locomotion. I am very interested in applying RL methods with MJX, but I tried the Unitree H1 robot and found that it takes for a single environment about 3-5 milliseconds to run one step **pipeline_step** function and 0.5 seconds for 500 environments, which is much slower than the reported performance in the documentation. In my H1 model, the contact is simplified to be only at the feet. So my question is, is it normal that it is so slow?

**Comment by yuvaltassa** [comment]
1. This is not a feature request. Please post in "asking for help".
2. This is not reproducible, there is no way to help you.
