### ISSUE TITLE
Unsable Simulation for Deformable object 

### ISSUE THREAD

**Issue by yzwfromk** [google-deepmind/mujoco#2109]
### Intro

Hi!

I am a graduate student at Georgia Tech, I use MuJoCo for my research on Bipedal locomotion on challenging terrain.

### My setup

Ubuntu 20.04.6 LTS, 64 bit
Mujoco Python 3.2.0

### What's happening? What did you expect?

I'm simulating deformable object using `<flexcomp>`. However, the simulation sometimes crashes and runs fine, depending on the size of the `count`, `spacing`, and `mass`, and other parameters such as `young`.

For the given model that I attached here, it works fine. However, if I change `young` to 5e4, or `mass` to 10, or `count` to `40 40 5`, or `spacing` to `.1 .1 .01`, the simulation doesn't work.

### Steps for reproduction

Loading the model below in the simulator will let you know if it runs or not

### Minimal model for reproduction

```
<mujoco model='error'>
  <compiler angle='degree' eulerseq='xyz'/>
  <option iterations='50' solver='Newton' timestep='0.001' gravity='0 0 -9.806'/>

  <extension>
    <plugin plugin="mujoco.elasticity.solid"/>
  </extension>

  <default>
    <default class='collision'>
    <geom conaffinity='1' condim='3' contype='1'/>
    </default>
    <equality solimp='0.9 0.95 0.001 0.1 2' solref='0.001 1.1' />
    <geom conaffinity='0' condim='1' contype='0' solref='0.005 1' />
    <joint solreflimit='0.001 1' />
  </default>


  <worldbody>

    <geom name='ground' type='plane' size='0 0 1' conaffinity="127" condim="3" friction="0.7 0.01 0.005" pos='0 0 0' priority='100'/>
    <light diffuse="1 1 1" pos="0 0 3" dir="0 0 -1"/>

    <flexcomp type="grid" count="20 20 5" spacing=".1 .1 .1" pos="0 0 0.31"
                radius=".0" rgba="0 .7 .7 1" name="softbody" dim="3" mass="20">
        <contact condim="3" solref="0.01 1" solimp=".95 .99 .0001" selfcollide="none"/>
        <edge damping="1"/> 
        <plugin plugin="mujoco.elasticity.solid">
            <config key="poisson" value="0.2"/>
            <config key="young" value="5e3"/>
        </plugin>
    </flexcomp>

  </worldbody>

</mujoco>
```

### Code required for reproduction

`python3 -m mujoco.viewer`

### Confirmations

- [X] I searched the [latest documentation](https://mujoco.readthedocs.io/en/latest/overview.html) thoroughly before posting.
- [X] I searched previous [Issues](https://github.com/google-deepmind/mujoco/issues) and [Discussions](https://github.com/google-deepmind/mujoco/discussions), I am certain this has not been raised before.

**Comment by quagla** [comment]
Hi, yes this is normal. You either have to reduce the time step or switch to constraints with `equality="true"` instead of using the true elasticity model (so deleting the plugin).
