### ISSUE TITLE
`spec.copy_back(model)` errors

### ISSUE THREAD

**Issue by kevin-thankyou-lin** [google-deepmind/mujoco#2142]
### Intro

Hi!

I'm a PhD student at UT Austin, I use MuJoCo for [robosuite](https://robosuite.ai/) which my lab maintains.

### My setup

```
mujoco=='3.2.3'
Python 3.9.0 
Ubuntu 20.04
```

### What's happening? What did you expect?

I'm trying to to save the most 'recent' version of an `MjModel` (as `mj_saveLastXML`, which is exposed in python, might be overridden during runtime) as an xml by copying things into an `MjSpec` via `spec.copy_back(model)`. However, it seems like the python bindings of this method aren't correctly exposed. 

Use case / reproduction script:

```python
import mujoco
import pathlib


def save_modified_model_to_xml(model: mujoco.MjModel, original_xml_path: str, output_xml_path: str) -> None:
    # Load from string.
    spec = mujoco.MjSpec()
    spec.from_file(original_xml_path)
    spec.compile()

    # Copy the modified model back into the spec
    spec.copy_back(model)

    # Save the modified model to a new XML file
    xml = spec.to_xml()
    pathlib.Path(output_xml_path).write_text(xml)
    
# Define paths
original_xml_path = 'sample_model.xml'
output_xml_path = 'modified_model.xml'

# Ensure paths exist
pathlib.Path(original_xml_path).write_text("""
<mujoco model="simple_model">
    <worldbody>
        <body name="box" pos="0 0 0.5">
            <joint name="hinge" type="hinge" axis="0 1 0" />
            <geom type="box" size="0.1 0.1 0.1" />
        </body>
    </worldbody>
</mujoco>
""")

# Load model
model = mujoco.MjModel.from_xml_path(original_xml_path)

# Modify model (e.g., move the box higher)
model.body_pos[1] = [0.0, 0.0, 1.0]  # Move the box up

# Save the modified model
save_modified_model_to_xml(model, original_xml_path, output_xml_path)
```

Gives error:

```
    spec.copy_back(model)
TypeError: copy_back(): incompatible function arguments. The following argument types are supported:
    1. (self: mujoco._specs.MjSpec, arg0: mjModel_) -> None

Invoked with: <mujoco._specs.MjSpec object at 0x7f880a766c70>, <mujoco._structs.MjModel object at 0x7f8833d9a4b0>
```

### Steps for reproduction

See the above script.

### Confirmations

- [X] I searched the [latest documentation](https://mujoco.readthedocs.io/en/latest/overview.html) thoroughly before posting.
- [X] I searched previous [Issues](https://github.com/google-deepmind/mujoco/issues) and [Discussions](https://github.com/google-deepmind/mujoco/discussions), I am certain this has not been raised before.

**Comment by quagla** [comment]
We made an API change. Please replace 

```
    spec = mujoco.MjSpec()
    spec.from_file(original_xml_path)
```
with 

```
    spec = mujoco.MjSpec.from_file(original_xml_path)
```

and let me know if the error persists. In your code, `spec` is empty.

**Comment by yuvaltassa** [comment]
Also, are you sure you want copy_back?

This functionality is basically legacy, from when modifying mjModel was recommended and you wanted those modification to appear in the XML. However now that you have `mjSpec` there is basically no reason to ever use copy_back.

If you're sure you need it, please explain why.

**Comment by kevin-thankyou-lin** [comment]
Hi @quagla, thanks for your reply. 

I think I originally tried directly using `spec = mujoco.MjSpec.from_file(original_xml_path)`, but I get the following error:

```
spec = mujoco.MjSpec.from_file(original_xml_path)
TypeError: from_file(): incompatible function arguments. The following argument types are supported:
    1. (self: mujoco._specs.MjSpec, filename: str, assets: Optional[dict] = None) -> None

Invoked with: 'sample_model.xml'
```

I tried using an absolute file path, but get the same `TypeError` and also double checked that I'm using `mujoco==3.2.3`. Also, I'm actually getting a correct looking xml when I print the spec:

```python
def save_modified_model_to_xml(model: mujoco.MjModel, original_xml_path: str, output_xml_path: str) -> None:
    # Load from string.
    spec = mujoco.MjSpec()
    spec.from_file(original_xml_path)
    spec.compile()
    xml = spec.to_xml()
    print(xml)
```

**Comment by kevin-thankyou-lin** [comment]
Hi @yuvaltassa, thanks for checking. I see that directly modify the `mjModel` is no longer recommended, so we should update robosuite to use the new spec based model creation workflow in later releases.

That said, I'm wondering if there's still a way to obtain the 'most recent' xml from the current `mjModel`, with fexisting exposed functions? Concretely, I'm wondering if there's some variant of `mujoco.mj_saveXML(filename.encode(), self._model)` that is available? (for reference `mujoco.mj_saveXML` doesn't exist)

```bash
>>> import mujoco
>>> mujoco.mj_saveXML
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mujoco' has no attribute 'mj_saveXML'
```

Currently, we have this `get_xml()` method that uses `mujoco.mj_saveLastXML`. However, it's causing some issues when we try to load other `mjModel`'s after creating a first `mjModel`:

```python    
def get_xml(self):
        with TemporaryDirectory() as td:
            filename = os.path.join(td, "model.xml")
            ret = mujoco.mj_saveLastXML(filename.encode(), self._model)
            return open(filename).read()
```

**Comment by yuvaltassa** [comment]
Try with 3.2.4?

mj_saveXML should work fine.

Sorry for the faff, these are slight birthing pains, but we think we're basically done with the major bugs now. We're working on thorough documentation now and a colab tutorial that should make this quite easy to use. Keep your eye on commits and the "Latest" version of the docs in the coming fortnight.

**Comment by kevin-thankyou-lin** [comment]
No worries! Sounds great - looking forward to the updates.

The functions don't seem to exist on 3.2.4 either (only `mj_saveLastXML` seems to exist):

```
>>> mujoco.__version__
'3.2.4'
>>> mujoco.mj_saveLastXML
<built-in method mj_saveLastXML of PyCapsule object at 0x7f8618b8edb0>
>>> mujoco.mj_saveXMLString
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mujoco' has no attribute 'mj_saveXMLString'
```

Also, I think `mj_saveXML` itself mightn't work for getting the changes inside the `mjModel` (I might be wrong), since the [docstring](https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mj-savexml) suggests I need a `spec` object?

`int mj_saveXML(const mjSpec* s, const char* filename, char* error, int error_sz);`

**Comment by yuvaltassa** [comment]
Sorry make I wasn't clear. In the new workflow you **never** make changes to the `mjModel`. You change the `mjSpec` and compile again to get new model. mj_saveXML is available, but exposed as a method of the pybind MjSpec object. Like I said we need to document, but you can go ahead and browse specs.cc until we do.

**Comment by kevin-thankyou-lin** [comment]
Ah you were clear - sounds great, I'll make a note to update robosuite to use the new `mjSpec/mjModel` workflow in a later robosuite release. Thanks for your help!
