### ISSUE TITLE
NotImplementedError: Elliptic cone force is not implemented yet.

### ISSUE THREAD

**Issue by kinalmehta** [google-deepmind/mujoco#2153]
### Intro

Hi!

I am trying to use MuJoCo-MJX with CMUHumanoid from [dm-control](https://github.com/google-deepmind/dm_control/tree/main/dm_control/locomotion). However I'm getting the following error.

```sh
NotImplementedError: Elliptic cone force is not implemented yet.
```

However in the documentation of version 3.2.0 it is mentioned that 
`Added support for [elliptic friction cones](https://mujoco.readthedocs.io/en/stable/XMLreference.html#option-cone).`

### Mujoco versions
- mujoco                       3.2.3
- mujoco-mjx                   3.2.3

### Python and OS version
- python 3.11.8
- ubuntu 22.04

### Minimal model for reproduction
minimal XML link: https://github.com/google-deepmind/dm_control/blob/main/dm_control/suite/humanoid_CMU.xml

### Code required for reproduction

```python
import mujoco
from mujoco import mjx

mj_model = mujoco.MjModel.from_xml_path(xml_path)
mj_data = mujoco.MjData(mj_model)
print(mj_data.qpos, type(mj_data.qpos))

mjx_model = mjx.put_model(mj_model) # error here
mjx_data = mjx.put_data(mj_model, mj_data)

print(mjx_data.qpos, type(mjx_data.qpos), mjx_data.qpos.devices())

mjx_data = mjx.forward(mjx_model, mjx_data)

```

### Confirmations

- [X] I searched the [latest documentation](https://mujoco.readthedocs.io/en/latest/overview.html) thoroughly before posting.
- [x] I searched previous [Issues](https://github.com/google-deepmind/mujoco/issues) and [Discussions](https://github.com/google-deepmind/mujoco/discussions), I am certain this has not been raised before.

**Comment by uvikas** [comment]
Hi @kinalmehta, I am getting the same error for a different XML model. Were you able to resolve this?

**Comment by kinalmehta** [comment]
I switched to using `pyramidal` cone till this is fixed
```xml
<option cone="pyramidal"/>
```
