### ISSUE TITLE
Model attach and MjSpec leads to broken xml

### ISSUE THREAD

**Issue by jjyyxx** [google-deepmind/mujoco#2162]
### Intro

I am a graduate student at HKU, I use MuJoCo for my research on robotic manipulation. This issue is a follow-up of comment https://github.com/google-deepmind/mujoco/issues/2150#issuecomment-2426708998

### My setup

MuJoCo 3.2.4

### What's happening? What did you expect?

1. the output xml contains two levels of nameless <default>, leading to error when loaded back;
2. the output xml is full of asset path inconsistencies (this may be harder to deal with)
    - `meshdir` would be overwritten, breaking either parent or child
    - If the child model is in another directory, its asset paths are just copied in, leading to failed asset lookup.
3. MjSpec load error if the child model contains `<custom>` tags.

### Steps for reproduction

Run snippet below

### Minimal model for reproduction

parent.xml
```xml
<mujoco>
    <compiler meshdir="a" />
    <asset>
        <!-- <mesh name="a" file="a.obj" /> -->
        <model name="child" file="child/child.xml" />
    </asset>
    <worldbody>
        <attach model="child" body="child" />
    </worldbody>
</mujoco>
```
child/child.xml
```xml
<mujoco>
    <compiler meshdir="b" />
    <asset>
        <!-- <mesh name="b" file="b.obj" /> -->
    </asset>
    <worldbody>
        <body name="child" />
    </worldbody>
</mujoco>
```

### Code required for reproduction

```python
import mujoco
spec = mujoco.MjSpec.from_file('parent.xml')
spec.compile()
xml = spec.to_xml()
print(xml)
mujoco.MjModel.from_xml_string(xml)
```

### Confirmations

- [X] I searched the [latest documentation](https://mujoco.readthedocs.io/en/latest/overview.html) thoroughly before posting.
- [X] I searched previous [Issues](https://github.com/google-deepmind/mujoco/issues) and [Discussions](https://github.com/google-deepmind/mujoco/discussions), I am certain this has not been raised before.

**Comment by quagla** [comment]
1. Should be solved by using a prefix, could you please confirm? It's likely that we will require a `prefix` for attach in the future.

**Comment by quagla** [comment]
I can't reproduce 3, could you please send a minimal example?

**Comment by quagla** [comment]
> Besides,
> 
> > This is known and part of conflicting compiler options in general. We are working to keep track of attached options.
> 
> I found that, currently, in order for an attached model (with assets) to work with MjSpec, the parent and child XML must be in the same level of directory. Otherwise, path inconsistency either prevents `MjSpec.compile` before `to_xml`, or produces a model with wrong relative path. I understand that completely resolving this issue may require some major changes, but this indeed complicates our model management (we would like to put thirdparty child models in a sub-directory, but currently could not.)

Yes, I know. I have a solution partially implemented but it's not ready to be submitted yet. Maybe in a week's time.

**Comment by quagla** [comment]
> @quagla Thanks for the quick fix! But,
> 
> > 1. Should be solved by using a prefix, could you please confirm? It's likely that we will require a prefix for attach in the future.
> 
> I could not confirm this workaround, because applying prefix when attaching a child model containing actuator with class leads to yet another segfault (in `mjXWriter::OneActuator`). 😂
> 
> a.xml
> 
> ```
> <mujoco>
>     <asset>
>         <model name="b" file="b.xml" />
>     </asset>
> 
>     <worldbody>
>         <attach model="b" body="b" prefix="b" />
>     </worldbody>
> </mujoco>
> ```
> 
> b.xml
> 
> ```
> <mujoco>
>   <default>
>     <default class="b"/>
>   </default>
> 
>   <worldbody>
>     <body name="b">
>       <geom type="box" size="0.1 0.1 0.1"/>
>       <joint name="b"/>
>     </body>
>   </worldbody>
> 
>   <actuator>
>     <position joint="b" class="b"/>
>   </actuator>
> </mujoco>
> ```

That's very useful, thanks!
