### ISSUE TITLE
Constraint Jacobian mis-allocation 

### ISSUE THREAD

**Issue by nisal-perera** [google-deepmind/mujoco#2189]
### Intro

Hi!

I am a PhD student using Mujoco to simulate a bipedal robot with closed chain mechanism.

### My setup

I am using Mujoco 3.2.4 on ubuntu 20.04 with C++.

### What's happening? What did you expect?

I made a mujoco model for my biped robot and created the closed-chain mechanism using equality` (<connect>)` constraint. I made sure to use the bare minimum number of equality constraints to defined my model. When i fix the robot w.r.t. the world (i.e. remove the `<free joint>`) i can simulate the robot with the linkages. However, when i add the `<free joint>` to make the robot a floating base, I get cannot simulate the model. I get the following error **"Error:engine error: mj_makeConstraint: constraint Jacobian mis-allocation:found nnzJ=642 but allocated 594"**.

I have attached a model that can be used to reproduce this error.

### Steps for reproduction

1. Load the model below to the mujoco environment. 

### Minimal model for reproduction

See the attached .xml model file
[closed_chain_bug_report.zip](https://github.com/user-attachments/files/17564568/closed_chain_bug_report.zip)

### Confirmations

- [X] I searched the [latest documentation](https://mujoco.readthedocs.io/en/latest/overview.html) thoroughly before posting.
- [X] I searched previous [Issues](https://github.com/google-deepmind/mujoco/issues) and [Discussions](https://github.com/google-deepmind/mujoco/discussions), I am certain this has not been raised before.

**Comment by yuvaltassa** [comment]
Thanks for the great bugt report.

I loaded the model at head and it's fine. I believe this was fixed by the same commit that fixed #2174.
Please [build from source](https://mujoco.readthedocs.io/en/latest/programming/index.html#building-from-source) to verify this on your full model, or wait for the next release.
