### ISSUE TITLE
The ’asset/model‘ tag may miss some types of actuators.

### ISSUE THREAD

**Issue by LinShuang22** [google-deepmind/mujoco#2233]
### Intro

Hi!

I am a PhD student working on robot cluster simulations using MuJoCo.

### My setup

MuJoCo：3.2.5
Python
Windows10

### What's happening? What did you expect?

I want to find a way to create a robot cluster in the XML model where all the individual robots are identical. I noticed that using `asset/model` can simplify the process and avoid repetitive creation.
My single robot includes various types of actuators, including those applied to joints and those applied to sites. When using `attach` in the final XML file, the actuators applied to sites are ignored, but the others are referenced correctly. And I can create an actuator in the scene.xml file.
In addition, I have some other questions.
*  How to create multiple copies with position offsets, similar to using `replicate/offset`.
*  I can first create a `body` and set its position, then reference attach in the child body of this body. However, there is a `freejoint` in my submodel, which causes a conflict.
* I tried using `replicate`, but it doesn't synchronize the creation of `actuator`.

Here is a screen-shot showing a green sphere:
* In single module, there are two actuators.
![图片](https://github.com/user-attachments/assets/1b91cd80-5509-4ee7-9c38-2879c2e0dbff)
* But, there is only one actuator in scene 

![图片](https://github.com/user-attachments/assets/22a18f99-ebeb-4eef-92af-8ef54a921348)

### Steps for reproduction

The `scene.xml` file is the final file, and `singlemodel.xml` is the submodel.

### Minimal model for reproduction

Here is my simplified example.

<details>
<summary>scene.xml</summary>

```XML

<mujoco model="scene">
    <asset>
        <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="512" height="3072"/>
        <texture type="2d" name="groundplane" builtin="checker" mark="edge" rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3"
                 markrgb="0.8 0.8 0.8" width="300" height="300"/>
        <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5" reflectance="0.2"/>
        <model name="testModel" file="singleModel.xml" />
    </asset>
    <worldbody>
        <light pos="0 0 1.5" dir="0 0 -1" directional="true"/>
        <geom name="floor" size="0 0 0.05" type="plane" material="groundplane"/>
        <attach model="testModel" body="singleModel" prefix="1-"/>
        
    </worldbody>
    <actuator>
<!--        <motor name="body_thrust" ctrlrange="0 1" gear="0 0 100 0 0 0" site="1-ball-center"/>-->
    </actuator>
</mujoco>
```
</details>

<details>
<summary>singleModel.xml</summary>

```XML

<mujoco model="singleModel">
    <worldbody>
        <body name="singleModel" pos="0 0 0.2">
            <joint name="modFree" type="free" pos="0 0 0"/>
            <geom name="ball" type="sphere" size="0.1" rgba="0.5 0 0 1"/>
            <site name="ball-center"/>
            <body name="limb1" pos="0 0 0">
                <joint name="limb1-hinge" type="hinge" pos="0 0 0" axis="0 0 1"/>
                <geom name="limb1-geom" type="cylinder" fromto="0 0 0 0.5 0 0" size="0.03" rgba="0.5 0.5 0 1"/>
            </body>
        </body>
    </worldbody>
    <actuator>
        <motor name="body_thrust" ctrlrange="0 1" gear="0 0 100 0 0 0" site="ball-center"/>
        <position name="hinge1" joint="limb1-hinge" kp="100" ctrlrange="0 1" forcerange="-100 100"/>
    </actuator>
</mujoco>
```
</details>

### Confirmations

- [X] I searched the [latest documentation](https://mujoco.readthedocs.io/en/latest/overview.html) thoroughly before posting.
- [x] I searched previous [Issues](https://github.com/google-deepmind/mujoco/issues) and [Discussions](https://github.com/google-deepmind/mujoco/discussions), I am certain this has not been raised before.

**Comment by quagla** [comment]
Thanks for the bug, it should work now.
