### ISSUE TITLE
`Error: Element 'compiler', line 0` when importing xml file

### ISSUE THREAD

**Issue by Fima2003** [google-deepmind/mujoco#2312]
### Intro

Hi!

I am a  undergrad student at Technion, I use MuJoCo for my modeling of a robotic arm that will perform specific tasks. For now, I need to model the ur5e arm on top of the box. I have the issue of importing ur5e.xml file into scene.xml. I want to place it on top of the box, so I use

```
<mujoco>
   //<`-- ...Some code -->
   <worldframe>
   //<`-- ...Some code -->
       <body pos="0.3 0 0.2">
         <include file="ur5e.xml" />
       </body>
   </worldframe>
</mujoco>
```
but it throws the following error: `XML error: Schema violation: unrecognized element. Element 'compiler', line 0`. And even if I comment out the compiler in ur5e.xml, it still gives the same error but with the next tag in the xml file...

What is this issue? and how can I go around it?

### My setup

Version 3.2.5, Python, ARM, MacOS. 

### What's happening? What did you expect?

I expect the ur5e robot to be on top of the box, but it throws an error instead. I am making a bug here, because this is google-deepmind model

### Steps for reproduction

1. Open the scene from this DeepMind folder https://github.com/google-deepmind/mujoco_menagerie/tree/main/universal_robots_ur5e
2. Change scene.xml the one in minimal model for reproduction
3. Should appear on top of the box, but instead throws an error

### Minimal model for reproduction

```XML
<mujoco model="ur5e scene">

  <statistic center="0.3 0 0.4" extent="0.8" />

  <visual>
    <headlight diffuse="0.6 0.6 0.6" ambient="0.1 0.1 0.1" specular="0 0 0" />
    <rgba haze="0.15 0.25 0.35 1" />
    <global azimuth="120" elevation="-20" />
  </visual>

  <asset>
    <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="512"
      height="3072" />
    <texture type="2d" name="groundplane" builtin="checker" mark="edge" rgb1="0.2 0.3 0.4"
      rgb2="0.1 0.2 0.3" markrgb="0.8 0.8 0.8" width="300" height="300" />
    <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5"
      reflectance="0.2" />
    <material name="wall" rgba="0.8 0.8 0.8 1" />
    <material name="box" rgba="0.6 0.4 0.2 1" />
  </asset>

  <worldbody>
    <!-- Ground plane -->
    <geom name="floor" size="0 0 0.05" type="plane" material="groundplane" />

    <!-- Base box -->
    <geom name="base_box" pos="0.3 0 0.1" size="0.2 0.2 0.1" type="box" material="box" />

    <!-- UR5e Robot placed on top of the box -->
    <body pos="0.3 0 0.2">
        <include file="ur5e.xml" />
    </body>

    <!-- Surrounding walls -->
    <geom name="wall1" pos="0.3 -0.3 0.5" size="0.2 0.01 0.5" type="box" material="wall" />
    <geom name="wall2" pos="0.3 0.3 0.5" size="0.2 0.01 0.5" type="box" material="wall" />
    <geom name="wall3" pos="0.1 0 0.5" size="0.01 0.2 0.5" type="box" material="wall" />
  </worldbody>
</mujoco>
```

### Code required for reproduction

no code needed

### Confirmations

- [X] I searched the [latest documentation](https://mujoco.readthedocs.io/en/latest/overview.html) thoroughly before posting.
- [X] I searched previous [Issues](https://github.com/google-deepmind/mujoco/issues) and [Discussions](https://github.com/google-deepmind/mujoco/discussions), I am certain this has not been raised before.

**Comment by yuvaltassa** [comment]
1. The error is obvious, you are including a model that has `<compiler/>` at the top, so you cannot include it there.
2. Why are you using include instead of [attach](https://mujoco.readthedocs.io/en/latest/XMLreference.html#body-attach)?
