### ISSUE TITLE
Inferring hinge axis from rotation matrix?

### ISSUE THREAD

**Issue by livinamuk** [google-deepmind/mujoco#235]
I apologise if this is simply a math problem but I've been stuck on this for some time and the consensus from all I've spoken to is that I must speak to somebody familiar with the library.

I'm trying to port my existing code base which uses PhysX over to MuJoCo, specifically the `PxD6Joint`, which as I understand must be emulated using three hinge joints. I have a rotation matrix which orientates the joint relative to a rigid body, which as I also understand must be decomposed into three unit vectors. 

Is this even possible from a rotation matrix? 

What is the approach here?

**Comment by livinamuk** [comment]
There is no way to specify limits for x, y, and z axes of the ball joint though right? 
That's a requirment here, I'm trying to port a ragdoll setup from PhysX to MuJoCo.

**Comment by yuvaltassa** [comment]
That is correct and indeed as I said above, the gimbal lock is only a problem with _unlimited hinges_. So you are doing the right thing.
