### ISSUE TITLE
Evaluate GJK vs MPR for collision detection

### ISSUE THREAD

**Issue by yuvaltassa** [google-deepmind/mujoco#3]
MuJoCo uses `libCCD` for collision detection, but currently only uses the [`MPR`](https://en.wikipedia.org/wiki/Minkowski_Portal_Refinement) algorithm, while `libCCD` also contains and implementation for [`GJK`](https://en.wikipedia.org/wiki/Gilbert%E2%80%93Johnson%E2%80%93Keerthi_distance_algorithm). It would be interesting to compare these two.

**Comment by kbayes** [comment]
MuJoCo now supports GJK directly through nativeccd.  We tried GJK from libccd in the past, but had poor results.
