### ISSUE TITLE
Unity not importing MuJoCo Scene properly 

### ISSUE THREAD

**Issue by ClaySant** [google-deepmind/mujoco#334]
I'm using MuJoCO 2.2.0, Unity 2022.2 and Ubunto 20.04.4 LT
And, when I try to import the humanoid model that comes with mujoco, the unity don't load the model really well. I create scene with a sphere in a tilted plane to test the mujoco physics, and everything run normal.
![Unity](https://user-images.githubusercontent.com/91495417/172953012-cdf585e4-1a58-49a4-8876-5f6ea45ab5f6.jpg)

**Comment by kevinzakka** [comment]
I believe this is no longer an issue.
