### ISSUE TITLE
Feature request - Proximity queries

### ISSUE THREAD

**Issue by eaa3** [google-deepmind/mujoco#51]
I was wondering if we currently have something akin to the distance and collision queries supported by Bullet [1] (e.g. getContactPoints, getClosestPoints). Is there any documentation on something equivalent to that in MuJoCo or could that be a potential feature to be implemented in the future? Many thanks for the presentation at CoRL!

[1] - https://docs.google.com/document/u/0/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/mobilebasic#h.hrpbzrwzgy1p

**Comment by yuvaltassa** [comment]
Hi, thanks for input! 

Regarding getContactPoints, simply iterate over the `data->contact` array to read out the contact points that have been found in the last call to the dynamics.

Regarding getClosestPoints, finding the distance and/or contact point between two arbitrary geoms -- independently of the dynamics -- there is currently no easy way to do this with the current API, but we can fairly easily add that. I've marked this as a feature request and will update here when we have something.

**Comment by MotorCityCobra** [comment]
> simply iterate over the `data->contact` array to read out the contact points

Hello. In what function or part of the cc file would you do this?  
I've tried to print out a lot of the data with `d->` or `m->` and I get `Segmentation fault (core dumped)`

**Comment by lzyang2000** [comment]
May I ask has there have been any updates on finding the distance between two arbitrary geoms? Thank you!

**Comment by yuvaltassa** [comment]
Thanks for the reminder!
