### ISSUE TITLE
Transform component in Unity modified in seeminlgy random way when using the MuJoCo plugin

### ISSUE THREAD

**Issue by pkrack** [google-deepmind/mujoco#521]
Hi,

I'm a student and I'm trying to use the MuJoCo Unity plugin for a robotics simulation.

I'm looking for some help with getting the plugin to work under Linux.

I installed everything according to the documentation and nothing in the process hinted at a potential mistake. It looks like a bug to me but to my surprise I haven't seen any bug report mentioning a similar problem. So I'll tag this as a question for now.

At initialization the transforms of the GameObjects with mjComponents are modified in all kind of crazy ways: X,Y,Z coordinates are reset to zero, swapped around between different gameObjects and rotated in a seemingly random fashion. 

The behavior is different based on the number of GameObjects in the scene and the presence of a MjBody as a parent (which is expected given e.g. [this conditional in MjGeom.cs](https://github.com/deepmind/mujoco/blob/16c11b9e8312a85a6f4c122a03bea25f864f771e/unity/Runtime/Components/Shapes/MjGeom.cs#L49).)

I guess the best way to explain what is happening is with a video. [Here](https://user-images.githubusercontent.com/20185598/194898212-f7f7e4db-bc0a-4a8f-81ea-706d554d01aa.webm) are all the cool features of my Unity/Mujoco simulation :)

The [generated XML file](https://github.com/deepmind/mujoco/files/9747094/test.md) (markdown extension so I can upload it here) works fine when using Mujoco directly with the simulate binary.

Any clue what is happening here? Let me know if there is anything I can do to narrow down the problem.

Best regards,
Pierre

Software:
- OS: Ubuntu 22.04 (Gnome 42.4, same behaviour with X and Wayland)
- Unity: 2021.3.11.f1
- Mujoco plugin: 2.2.2

Hardware: 
- CPU: Intel Core i5-1135g7
- GPU: Intel Iris Xe integrated graphics

**Comment by Balint-H** [comment]
Have you tried importing a scene with the importer (from the Assets menu)? How do they behave? 

Sometimes weird behaviour like this can be a result from a mismatch in the DLL and plugin version as well.

**Comment by Balint-H** [comment]
Have you tried importing a scene with the importer (from the Assets menu)? How do they behave? 

Sometimes weird behaviour like this can be a result from a mismatch in the DLL and plugin version as well.
