### ISSUE TITLE
HAPTIX Hand Model in Unity

### ISSUE THREAD

**Issue by mwinnick4** [google-deepmind/mujoco#522]
Hello. I have implemented the MuJoCo HAPTIX hand model's XML code into Unity and was trying to grasp and pick up objects (cubes, spheres, etc.) using the hand model itself. The computer I am running the program on is a low-performance computer. When I run the program, the framerate drops exponentially and the program does not run as expected (strange contact events with the cubes and sphere game objects passing through the hand model, etc.). I was wondering if anyone has faced something similar and if so, does anyone have suggestions to improve the quality of contact events? I do not believe that there is anything wrong with the code itself and do believe that the issue is a hardware issue, but I could be wrong. Let me know if anyone has also played around with the HAPTIX hand model in Unity and faced similar issues!

**Comment by Balint-H** [comment]
Hello, have you tried running other models with high number of contacts in Unity (for example, 22_humanoids, or humanoid 100)? How's the performance with them?
