### ISSUE TITLE
Cannot access all GPUs through EGL devices when using docker

### ISSUE THREAD

**Issue by Rocamonde** [google-deepmind/mujoco#572]
Hi,

I'm a researcher trying to use MuJoCo for RL reward specification from natural language feedback.

_Summary of issue_: all EGL devices available when running directly on server, but only one available when running within docker.

I am trying to select the GPU device id that should be used by mujoco for rendering, so I can parallelize the rendering of some environment.

The documentation does not explicitly discuss this, so by reading through the Python/C code, I found that setting the EGL flag allows me to select this backend, which then when setting the MUJOCO_EGL_DEVICE_ID will select the corresponding GPU device.

However, currently only 1 device is shown as available when running `all_devices = EGL.eglQueryDevicesEXT()` as per the function `create_initialized_egl_device_display` in `mujoco.egl.__init__.py`. When  I run `nvidia-smi` I can see a list of 8 distinct GPU cards installed. This is running within a docker container using `nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04`. 

Running
```python
import os; os.environ["MUJOCO_GL"] = "egl"; os.environ["MUJOCO_EGL_DEVICE_ID"] = "0"; import mujoco
```
works fine, but running
```python
import os; os.environ["MUJOCO_GL"] = "egl"; os.environ["MUJOCO_EGL_DEVICE_ID"] = "1"; import mujoco
```
raises
```
RuntimeError: The MUJOCO_EGL_DEVICE_ID environment variable must be an integer between 0 and 0 (inclusive), got 1.
```

When running outside of the container, I get all my devices:
```python
>>> from mujoco.egl import egl_ext as EGL
>>> len(EGL.eglQueryDevicesEXT())
9
```
(presumably the 8 GPUs plus one X server display?)

Any tips on how to enable the rest of GPU devices within Docker? And an explanation why I have 9 devices instead of 8 outside docker?

I am not an expert on C or linux so any help is appreciated.

**Comment by saran-t** [comment]
I'm a Docker expert, but a colleague pointed to https://github.com/NVIDIA/nvidia-docker/wiki/. It might be worth you reading through Nvidia's documentation on how to configure GPU access inside Docker.

**Comment by nimrod-gileadi** [comment]
Apologies if this is still an issue for you. Closing since there hasn't been any activity on this issue in a while.

**Comment by RealXuChe** [comment]
I encountered a similar issue. After investigating how to properly use Docker on a machine with NVIDIA GPUs, I’ve summarized the different problems I faced and my solutions here:

1. First, you should have the `nvidia-container-toolkit` installed on your host machine, and `nvidia-container-runtime` should be configured as Docker's backend runtime.
   You can check this by looking at the environment variables of the init process inside Docker: run `cat /proc/1/environ`. If the output contains something like `NVIDIA_DRIVER_CAPABILITIES=all NVARCH=x86_64 NVIDIA_REQUIRE_CUDA=cuda>=12.4 brand=tesla,driver>=470`, then this step has been successfully set up.

2. The `nvidia-container-toolkit` handles most of the tricky parts of passing the NVIDIA GPU into the container. However, by default, it doesn't enable graphical rendering functionality within the container. 
   If you encounter errors while trying to use GPU-accelerated rendering inside the container, you may need to create a new Docker container and pass the rendering capability into it when you do so. You can achieve this by passing the environment variable `-e NVIDIA_DRIVER_CAPABILITIES=all` when creating the container.

3. Using the environment variable above will add the driver libraries related to graphical rendering into the container. However, if the Docker image you are using doesn't include other components of the Linux graphics stack, you'll need to manually install them using a package manager. 
   For my Ubuntu image, I ended up needing to install the following three packages via apt-get: `libgl1`, `libx11-dev`, and `libglew-dev`. The missing graphics stack components in your image might differ from mine, so you should refer to the error messages you receive to install the necessary packages.

4. At this point, everything might already be working correctly. If it's not, and the error messages you see mention “MESA” or “nouveau,” it indicates that your graphics library is incorrectly calling the open-source graphics drivers. 
   Typically, your host machine will have proprietary graphics drivers installed, and the kernel module loaded will be the proprietary nvidia.ko. However, proprietary kernel drivers cannot work correctly with open-source user-space drivers, which leads to errors. 
   I found that the solution is to make your graphics libraries call the proprietary user-space graphics drivers. Specifically, the graphics library files on your system, such as libGLX or libEGL, are likely from the `libglvnd` project. These libraries don't contain actual graphical functionality but instead forward graphics API calls to the appropriate vendor libraries. `libglvnd` uses some json configuration files to determine which implementation to call. 
   In this case, the configuration file might not define the rule for dispatching to the NVIDIA proprietary implementation. If you're using EGL, you can check by running `ls /usr/share/glvnd/egl_vendor.d/`. For me, I could only see a `50_mesa.json file`. In this case, simply adding the following content to `/usr/share/glvnd/egl_vendor.d/10_nvidia.json` completely solved the problem for me:


```json
{
    "file_format_version" : "1.0.0",
    "ICD" : {
        "library_path" : "libEGL_nvidia.so.0"
    }
}
```

By applying all the steps above, I was able to use GPU rendering in Docker containers. I hope this helps you as well.

**Comment by yuyu5333** [comment]
> 我也遇到过类似的问题。在研究了如何在配备 NVIDIA GPU 的机器上正确使用 Docker 之后，我总结了遇到的不同问题以及解决方案：
> 
> 1. 首先，你应该`nvidia-container-toolkit`在主机上安装 ，`nvidia-container-runtime`并将其配置为 Docker 的后端运行时。
>    你可以通过查看 Docker: run 中 init 进程的环境变量来检查这一点`cat /proc/1/environ`。如果输出包含类似 的内容`NVIDIA_DRIVER_CAPABILITIES=all NVARCH=x86_64 NVIDIA_REQUIRE_CUDA=cuda>=12.4 brand=tesla,driver>=470`，则表示此步骤已成功设置。
> 2. 它`nvidia-container-toolkit`处理了将 NVIDIA GPU 传递到容器中的大部分棘手部分。但是，默认情况下，它不会在容器内启用图形渲染功能。
>    如果您在尝试在容器内使用 GPU 加速渲染时遇到错误，则可能需要创建一个新的 Docker 容器，并在执行此操作时将渲染功能传递给它。您可以通过在创建容器时传递环境变量来实现此目的`-e NVIDIA_DRIVER_CAPABILITIES=all`。
> 3. 使用上述环境变量会将与图形渲染相关的驱动程序库添加到容器中。但是，如果您使用的 Docker 镜像不包含 Linux 图形堆栈的其他组件，则需要使用包管理器手动安装它们。
>    对于我的 Ubuntu 镜像，我最终需要通过 apt-get 安装以下三个包：`libgl1`、`libx11-dev`和`libglew-dev`。您的镜像中缺少的图形堆栈组件可能与我的不同，因此您应该参考收到的错误消息来安装必要的包。
> 4. 此时，一切可能已经正常工作。如果不是，并且您看到的错误消息提到`MESA`或`nouveau`，则表示您的图形库错误地调用了开源图形驱动程序。
>    通常，您的主机将安装专有图形驱动程序，并且加载的内核模块将是专有的`nvidia.ko`。但是，专有内核驱动程序无法与开源用户空间驱动程序正常工作，从而导致错误。
>    我发现解决方案是让您的图形库调用专有用户空间图形驱动程序。具体来说，系统上的图形库文件（例如`libGLX`或`libEGL`）可能来自`libglvnd`项目。这些库不包含实际的图形功能，而是将图形 API 调用转发到适当的供应商库。`libglvnd`使用一些 json 配置文件来确定要调用哪个实现。
>    在这种情况下，配置文件可能没有定义分派到 NVIDIA 专有实现的规则。如果您使用的是 EGL，则可以通过运行进行检查`ls /usr/share/glvnd/egl_vendor.d/`。对我来说，我只能看到一个`50_mesa.json`文件。在这种情况下，只需添加以下内容即可`/usr/share/glvnd/egl_vendor.d/10_nvidia.json`完全解决问题：
> 
> {
>     "file_format_version" : "1.0.0",
>     "ICD" : {
>         "library_path" : "libEGL_nvidia.so.0"
>     }
> }
> 通过应用上述所有步骤，我能够在 Docker 容器中使用 GPU 渲染。希望这些步骤也能对你有所帮助。
> 
> **附言：**如果您对我提到的解决方案的参考感兴趣，或者上述步骤不能完全解决您的问题，您可能需要查看以下链接：
> 
> https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/index.html
> 
> https://wiki.archlinux.org/title/NVIDIA
> 
> https://wiki.archlinux.org/title/Nouveau
> 
> https://github.com/NVIDIA/libglvnd/
> 
> https://stackoverflow.com/questions/75515956/libegl-not-allowed-to-force-software-rendering-when-api-explicitly-selects-a-ha

Thank you very much. The problem has been successfully solved. Adding the file `/usr/share/glvnd/egl_vendor.d/10_nvidia.json` in Docker is a crucial step.

**Comment by Boltzmachine** [comment]
Same error. but did not use docker

**Comment by guaguastandup** [comment]
> Same error. but did not use docker同样的错误，但没有使用 docker

same problem, have you solved it?
