### ISSUE TITLE
Documentation images unreadable in dark mode

### ISSUE THREAD

**Issue by kgaranger** [google-deepmind/mujoco#587]
The new theme for the documentation looks great but the images with transparency are not readable in dark mode (screenshot below).

It may be preferable to include a white background behind these images or to use these images inverses for the dark mode theme.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/36901525/202347486-c363af44-3675-46a3-9041-7da783e0138a.png">

**Comment by kevinzakka** [comment]
Thanks for flagging this! Looks like there are some pictures that need a dark mode variant, most others seem okay?
