### ISSUE TITLE
Let d->userdata be a void pointer

### ISSUE THREAD

**Issue by joaopfg** [google-deepmind/mujoco#622]
Hi, I would like to make a request to let `d->userdata` a `void*`.  

`d->userdata` is currently of type `mjtNum*` . Correct if I'm wrong, but the main mechanism to communicate with control callbacks is to write/read to `d->userdata`. So, it puts restriction in the data I can pass to my control callbacks. 

In my simulation, I need to pass complex C structures to the control callbacks (which are received from an external server). I can of course try to encode my structures to allow them to be passed as `mjtNum*`. But I think it would facilitate a lot my life if `d->userdata` is a `void*`.

**Comment by yuvaltassa** [comment]
You can cast to a `void*` and back?

**Comment by saran-t** [comment]
@yuvaltassa that's undefined behaviour and should not really be suggested as a solution.

@joao the recommended path forward for nontrivial controllers is to utilise our new plugin API -- I'm about to push out a commit that extends plugins for control too. I'll be working on documentation for this API over the next couple of weeks, but in the meantime you can check out our bundled "elasticity" plugin code if you want to get started.

**Comment by joaopfg** [comment]
@saran-t @yuvaltassa Thanks for help. 

For now I got a workaround to do the conversion by playing with the C library function `memcpy`. Here is a small example doing something similar to what I did in my simulation:

```
#include "stdio.h"
#include "stdlib.h"
#include "string.h"

struct data_type{
	char const *name;
	int busy;
};

typedef struct data_type data_type;

struct buffer_type{
	double *buffer;
	size_t len;
};

typedef struct buffer_type buffer_type;

data_type convert_to_data_type(buffer_type const *buffer_container){
	data_type *data = malloc(sizeof(data_type));
    	memcpy(data, buffer_container->buffer, sizeof(data_type));
    	data_type data_type_copy = {data->name, data->busy};
    	free(data);
    	return data_type_copy;
}

buffer_type convert_to_buffer_type(data_type const *data){
	buffer_type buffer_container;
	buffer_container.buffer = (double *)malloc(sizeof(data_type));
	memcpy(buffer_container.buffer, data, sizeof(data_type));
	buffer_container.len = sizeof(data_type)/sizeof(double);
	return buffer_container;
}

int main(){
	data_type *data = malloc(sizeof(data_type));
	data->name = "test";
	data->busy = 1;		
	
	buffer_type buffer_container = convert_to_buffer_type(data);
	data_type data_copy = convert_to_data_type(&buffer_container);
	printf("Name: %s\n", data_copy.name);
	printf("Busy: %d\n", data_copy.busy);
	return 0;
}
```

What do you think ?

**Comment by erez-tom** [comment]
No, there's no built-in memory locking in MuJoCo's runtime.

**Comment by yuvaltassa** [comment]
No locking, but also no threading. Until your callback returns control to the caller, nothing else will touch mjData.

**Comment by joaopfg** [comment]
@yuvaltassa Thanks for info. Making a hook on the question, if I want to make some bodies move at the same time synchronized, is there some mechanism in MuJoCo ? If I understood, with the control callback mechanism I'm obliged to move the bodies sequentially, right ?

**Comment by yuvaltassa** [comment]
>  If I understood, with the control callback mechanism I'm obliged to move the bodies sequentially, right ?

The control callback `mjcb_control` can do whatever it wants, it has full access to mjData.
