### ISSUE TITLE
Defaults/Classes for Body elements

### ISSUE THREAD

**Issue by JeanElsner** [google-deepmind/mujoco#668]
Adding classes/defaults for body elements could make some MJCF models more compact. This could be used to set the `gravcomp` attribute for a kinematic chain for instance using the `childclass` attribute. Otherwise `gravcomp` has to be defined on every body of the chain.

**Comment by kevinzakka** [comment]
+1

**Comment by yuvaltassa** [comment]
Yes, both bodies and sensors currently don't support defaults. This is a legitimate feature request.

**Comment by yuvaltassa** [comment]
This is unfortunately infeasible or rather, very hard. The "class" attribute of bodies is being reused for "childclass", so there is no way (without a significant refactor) to implement this.
