### ISSUE TITLE
IOException, Error loading the XML, unsigned integer with an option suffix{K, M, G, T, P, E}

### ISSUE THREAD

**Issue by lzs0603** [google-deepmind/mujoco#807]
Hi,

I noticed that for mujoco 2.3.2 and 2.3.3, while simulating the humanoid.xml using the Unity plugin with an intel chip Mac, the below error appeared and system paused. I tried using unityeditor 2021.3.21, 2021.3.1 and 2020.3.46, received the same error. For mujoco 2.3.1 and versions earlier, it seems to work just fine with not problem.

Here is a screenshot for the error:
<img width="1364" alt="Screen Shot 2023-04-09 at 10 09 48 AM" src="https://user-images.githubusercontent.com/33793693/230750824-e74a43aa-f115-424a-8c1a-c34724c9cfaf.png">

**Comment by erez-tom** [comment]
Is this a fresh import of an MJCF, or a saved scene?
If it's a fresh import, what's the value in the XML of `size`->`memory` (if at all)?
If it's a saved scene, do you have a `MjGlobalSettings` component?  What's the value in the field `Global Sizes`->`Memory`?

**Comment by gpzhaome** [comment]
> Is this a fresh import of an MJCF, or a saved scene? If it's a fresh import, what's the value in the XML of `size`->`memory` (if at all)? If it's a saved scene, do you have a `MjGlobalSettings` component? What's the value in the field `Global Sizes`->`Memory`?

I had the same issue. I'm using a fresh import of MJCF humanoid.xml model. The memory is not set in the xml file. 

I fixed the issue by setting the `Global Sizes`->`Memory` to `2M` in the `MjGlobalSettings`.

**Comment by News0412** [comment]
> > Is this a fresh import of an MJCF, or a saved scene? If it's a fresh import, what's the value in the XML of `size`->`memory` (if at all)? If it's a saved scene, do you have a `MjGlobalSettings` component? What's the value in the field `Global Sizes`->`Memory`?
> 
> I had the same issue. I'm using a fresh import of MJCF humanoid.xml model. The memory is not set in the xml file.
> 
> I fixed the issue by setting the `Global Sizes`->`Memory` to `2M` in the `MjGlobalSettings`.

I met the same issue after importing the example model (humanoid.xml). And I tried to set the `Global Sizes`->`Memory` to `-1`(the default setting) in the `Mj Global Settings` of `Global Settings`, it run well. So I think this might be a problem of parameter transmission between the mujoco and the unity.

**Comment by Balint-H** [comment]
This issue has now been solved, and can be closed @erez-tom
