### ISSUE TITLE
Attaching two Independent Bodies

### ISSUE THREAD

**Issue by lalmofee** [google-deepmind/mujoco#853]
Hi,
I'm trying to attach a rotational crank handle to an arm and they are two different bodies within the worldbody. I tried using a tendon to attach the hand to the handle of the crank, but the tendon's length isn't fixed during the movement. What are ways to connect bodies the are far apart and not a child of the other?

**Comment by yuvaltassa** [comment]
You can put equality constraints on tendon length, making them stiff.
