### ISSUE TITLE
Maximize default viewing area of the python viewer.

### ISSUE THREAD

**Issue by vikashplus** [google-deepmind/mujoco#857]
**Is your feature request related to a problem? Please describe.**
Python viewer: There is very small surface left to view the model 
- The python visualizer starts with both left and right pane open. 
- The default font size are somewhat big on my Ubuntu laptop with 4k external screen.

**Describe the solution you'd like**
- Left and right pane should start hidden/ programmatic way to start them in hidden mode 
- Any way to specify the default font size of the viewer.

**Comment by yuvaltassa** [comment]
Starting the panes hidden is bad for discoverability, I don't think that's a good idea. Also hiding them is very easy.

Controlling the default font size would be valuable though. Maybe also initial window size and location? Anything else?

**Comment by saran-t** [comment]
I think @vikashplus just wants an option in `launch_passive` to have the viewer start with UI hidden, which I think is a fair request.

**Comment by saran-t** [comment]
PRs are also always welcome if any of your users feels strongly enough to implement these features. :)

**Comment by saran-t** [comment]
Sorry that it's taken so long to roll this out. We're planning to release a new version that incorporates a1d0cbd6543e41ebb2612fcff3b9d3b0a0c1e9ea in the middle of next week.

If you want to try this out before then, you can `pip install mujoco --pre -f https://py.mujoco.org/`.

**Comment by GF-Huang** [comment]
How to change font size when `launch_passive`?
