### ISSUE TITLE
Render successful on clean environment fails on subsequent runs

### ISSUE THREAD

**Issue by snibo13** [google-deepmind/mujoco#863]
Hi,
I'm a student and I'm trying to get a handle on MuJoCo so I have it in my toolset for future research.  I'm working through the tutorials on my laptop (XPS 15 i9-12900k 3050 Ti Mobile) and the render only succeeds if I restart the Python kernel in my notebook. On any runs after the first one, the result is noise. My code is below. Any help in understanding what I am doing wrong would be appreciated.
My model is just a box and a sphere.

Cheers

```
%env MUJUCO_GL=glx
 %env PYOPENGL_PLATFORM=egl
 %env DISABLE_RENDER_THREAD_OFFLOADING=1
 import mujoco
 import mediapy as media
 import matplotlib.pyplot as plt
 import numpy as np
 import time
 import itertools
 from PIL import Image
 xml = """
 <mujoco>
  <worldbody>
     <light name="top" pos="0 0 1"/>
     <geom name="red_box" type="box" size=".2 .2 .2" rgba="1 0 0 1"/>
     <geom name="green_sphere" pos=".2 .2 .2" size=".1" rgba="0 1 0 1"/>
   </worldbody>
 </mujoco>
 """
 
 model = mujoco.MjModel.from_xml_string(xml)
 data = mujoco.MjData(model)
 renderer = mujoco.Renderer(model)
 
 mujoco.mj_forward(model, data)
 renderer.update_scene(data)
 
 media.show_image(renderer.render())
```

First Run
![image](https://github.com/deepmind/mujoco/assets/29949873/01009753-3274-41ed-9004-53d5ced7a26c)

Second Run
![image](https://github.com/deepmind/mujoco/assets/29949873/72f5c065-2048-4108-815a-43550bc0647f)

Model Text
![image](https://github.com/deepmind/mujoco/assets/29949873/4492a55a-fbed-4509-a29f-0a4bb43695bf)

**Comment by snibo13** [comment]
Seems like if I clear the renderer variable there is no issue, I don't know if that would work for videos.
model = mujoco.MjModel.from_xml_string(xml)
data = mujoco.MjData(model)
renderer = None
renderer = mujoco.Renderer(model)

mujoco.mj_forward(model, data)
renderer.update_scene(data)

media.show_image(renderer.render())

**Comment by yuvaltassa** [comment]
This is interesting.

Note that MUJOCO_GL is misspelled, though I doubt that's related to what you are reporting.

**Comment by happygaoxiao** [comment]
I have the same issue and image output. The first image is correctly shown. But the second one from the next cell will show nothing.

**Comment by kevinzakka** [comment]
I can't seem to reproduce this locally on my M1 in a jupyter notebook. Note I didn't have to set any environment variables.

**Comment by snibo13** [comment]
I think it might be a driver issue with Intel Arc graphics cards

**Comment by kevinzakka** [comment]
Yeah we've seen similar issues with AMD graphics cards...

**Comment by saran-t** [comment]
The AMD issue only occurred on Windows though IIRC.

**Comment by snibo13** [comment]
It was windows only on my computer as well worked in Ubuntu
