### ISSUE TITLE
How to get a fine-tuned robot model?

### ISSUE THREAD

**Issue by zichunxx** [google-deepmind/mujoco#866]
Hi!

I am trying to get a finely tuned KUKA LBR IIWA 14 R820 model (.xml) from the [urdf file](https://github.com/ros-industrial/kuka_experimental/tree/e78bbd15edb2b39c9053ff3b963ef2947e10a531/kuka_lbr_iiwa_support).

However, due to the lack of official documentation, I have to start from scratch to get the adjusted joint damping, inertia, and other relevant dynamics parameters. I get a basic kuka model through `mujoco200 complie command` to convert the urdf to xml.

Currently, the problem I am experiencing is that there is a significant gap between the input joint angle (rad) and the actual joint position (rad), which is not allowed. 

Here is a figure to briefly illustrate my situation: 

![kuka_mujoco](https://github.com/deepmind/mujoco/assets/72594017/520b44e4-6dbe-4a3c-9559-7545e9e61bbd)

where there is a difference of about 0.1 rad between `qpos[1]` and `joint_a2_T (actuator)`.

In my XML file, the actuators are set with

```
  <actuator>
      <position name="joint_a1_T" ctrllimited="true" ctrlrange="-2.9668 2.9668" joint="joint_a1" kp="500"/>
      <position name="joint_a2_T" ctrllimited="true" ctrlrange="-2.0942 2.0942" joint="joint_a2" kp="500"/>
      <position name="joint_a3_T" ctrllimited="true" ctrlrange="-2.9668 2.9668" joint="joint_a3" kp="500"/>
      <position name="joint_a4_T" ctrllimited="true" ctrlrange="-2.0942 2.0942" joint="joint_a4" kp="500"/>
      <position name="joint_a5_T" ctrllimited="true" ctrlrange="-2.9668 2.9668" joint="joint_a5" kp="500"/>
      <position name="joint_a6_T" ctrllimited="true" ctrlrange="-2.0942 2.0942" joint="joint_a6" kp="500"/>
      <position name="joint_a7_T" ctrllimited="true" ctrlrange="-3.0541 3.0541" joint="joint_a7" kp="500"/>
  </actuator>
```

Could you give me a hint or some help on how to solve this problem and get a fine-tuned model?

Thanks in advance!

**Comment by kevinzakka** [comment]
Hi @QUIlToT, fyi we have a kuka 14 model that will be released very soon in menagerie so stay on the lookout for that!

**Comment by saran-t** [comment]
This is now available at https://github.com/deepmind/mujoco_menagerie/tree/main/kuka_iiwa_14
