### ISSUE TITLE
Object being placed on a surface with varying friction underneath

### ISSUE THREAD

**Issue by ShuoZheLi** [google-deepmind/mujoco#887]
If I have a body such as a box is placed on the top of the plane with two surfaces with different friction connecting, and the object is place in the middle. What will be the friction that the box is experiencing? Consider the box has a very little friction and less than the two surface frictions.
![image](https://github.com/deepmind/mujoco/assets/37442704/fa1b1a59-7df1-401f-8ebe-9562ec568501)

**Comment by Balint-H** [comment]
I'm not from the MuJoCo team but I'll have a go at it. As far as I understand friction is calculated at contact points (see https://mujoco.readthedocs.io/en/stable/XMLreference.html#body-geom). For a box lying flat, 4 contact points are calculated at the touching face's vertices (see image). The effective friction will be mixed based on the touching surfaces' `solmix` parameter. Alternatively if one geom has higher priority then it will determine the contact dynamics.

Assuming the box is aligned with the boundary, and starts completely on surf 1 sliding towards surf 2, it will effectively experience friction 1 only, then the average of friction 1 and 2 as the first 2 vertices cross over, then finally friction 2 only.
![image](https://github.com/deepmind/mujoco/assets/41113387/43fc1b47-6f01-4036-934b-188c36cd3c4a)

**Comment by ShuoZheLi** [comment]
> 

I think your answer make sense to me!
