### ISSUE TITLE
Abnormal joint variations when using robotiq_2f85 menagerie model

### ISSUE THREAD

**Issue by zichunxx** [google-deepmind/mujoco#906]
Hi!

I create a gymnasium env and attach the `robotiq_2f85` gripper to the end of the manipulator to grasp objects.

I control each joint of the manipulator and the gripper tendon actuator to step to desired positions via         `data.ctrl[:] = action` and the tendon action is clipped in the ctrlrange ([0, 255]).

The `n_substeps` of `mujoco.mj_step(self.model, self.data, nstep=self.n_substeps)` is 50. 

 However, when I observe each step process, I notice the abnormal variation in gripper joints, as shown in the following figure.

![robotiq](https://github.com/deepmind/mujoco/assets/72594017/f164e0f5-ae5d-4f53-b92b-950f40b9e40a)

Any advice and help would be appreciated! Thanks!

**Comment by kevinzakka** [comment]
Could you post a minimal reproducible example?

**Comment by yuvaltassa** [comment]
Hi @STAY-Melody I will have time to look at this soon.

If you can post your model (zip file with XML and assets), that would be helpful.

**Comment by kevinzakka** [comment]
Hi @STAY-Melody, just want to update you that I loaded your model and I can see the instabilities but haven't been able to debug why. I'll keep you posted.

**Comment by yuvaltassa** [comment]
Hi @STAY-Melody. At long last, we are now looking carefully at this model to understand what's wrong.

Unfortunately, the link to your reproducing code is now dead. Could you please re-post the link?

Apologies again for the extreme delay.

**Comment by yuvaltassa** [comment]
Hi @STAY-Melody, okay, finally, I've been able to reproduce! 

So, contrary to my [comment](https://github.com/google-deepmind/mujoco/issues/786#issuecomment-1849009946), there is some remaining issue with the Robotiq. 

Leaving this issue open.

**Comment by yuvaltassa** [comment]
Okay, I have a temporary fix, but I need you to test it.

In the Robotiq [joint defaults](https://github.com/google-deepmind/mujoco_menagerie/blob/main/robotiq_2f85/2f85.xml#L31), add `armature="0.001"` to all the joints that don't have armature (follower, link, coupler). Does that fix your issue?

A related temporary fix which has a similar effect is, in the [equality constraint section](https://github.com/google-deepmind/mujoco_menagerie/blob/main/robotiq_2f85/2f85.xml#L173), change `solimp[0]` from 0.9 to 0.0.

I would write more about what is actually happening here and why the above changes fix the issue, but I am currently digging deeper to better understand the true source, there might be a design bug in how equality constraints compute the effective inertia of the coupling mechanism, but that will take a bit more time to resolve. 

Will update here, in the meantime one or both of the above changes should hopefully resolve your issue.

**Comment by yuvaltassa** [comment]
This change is now at head I believe (has been for a while). Closing.
