### ISSUE TITLE
UI. A way to zero an actuator in simulate

### ISSUE THREAD

**Issue by Melanol** [google-deepmind/mujoco#945]
Not very important. Also accidentally wrote this FR for dm_control. Reposting here, so as it is not forgotten.

There is a "Clear all" button in simulate to zero all actuators, but I sometimes find it frustrating that there is no way to zero a particular actuator, and I have to try to click as close to 0 as possible, and it is not helpful, as even the smallest value results in movement. This would be useful for manual tests.

![246648235-a8b20703-29ab-44f6-8c7c-a9679131786c](https://github.com/deepmind/mujoco/assets/33939307/b0c8d85c-ff34-4b41-a638-1ae6c062dd47)

**Comment by yuvaltassa** [comment]
I tried a while back to make double-clicking do this, but it was too hard, sorry.
Maybe you can figure it out? 🙂

**Comment by Melanol** [comment]
How about right click? My C/C++ skills aren't great.

**Comment by yuvaltassa** [comment]
Hmmm okay, I'll look at right click.
